"""add tenancy identity brand and knowledge

Revision ID: 0002_tenancy_auth_knowledge
Revises: 0001_foundation
Create Date: 2026-08-23 11:54:05.962740
"""

from collections.abc import Sequence

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_tenancy_auth_knowledge'
down_revision: str | None = '0001_foundation'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_brands_brand_status')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_brands_brand_lock_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('workspace_id', 'name', name='brand_workspace_name')
    )
    op.create_index(op.f('ix_brands_current_version_id'), 'brands', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_brands_workspace_id'), 'brands', ['workspace_id'], unique=False)
    op.create_index('ix_brands_workspace_status', 'brands', ['workspace_id', 'status'], unique=False)
    op.create_table('knowledge_sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('uri', sa.Text(), nullable=True),
    sa.Column('canonical_uri_hash', sa.String(length=64), nullable=True),
    sa.Column('rights_status', sa.String(length=32), nullable=False),
    sa.Column('use_scope', sa.String(length=32), nullable=False),
    sa.Column('quality_grade', sa.String(length=1), nullable=False),
    sa.Column('rights_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('etag', sa.String(length=512), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_sources')),
    sa.UniqueConstraint('workspace_id', 'canonical_uri_hash', name='knowledge_source_uri_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='knowledge_source_workspace_id')
    )
    op.create_index(op.f('ix_knowledge_sources_created_by'), 'knowledge_sources', ['created_by'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_current_version_id'), 'knowledge_sources', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_workspace_id'), 'knowledge_sources', ['workspace_id'], unique=False)
    op.create_index('ix_knowledge_sources_workspace_state', 'knowledge_sources', ['workspace_id', 'state'], unique=False)
    op.create_table('terms_document_versions',
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_version', sa.String(length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms_document_versions')),
    sa.UniqueConstraint('document_type', 'document_version', name='uq_terms_document_versions_identity')
    )
    op.create_index('ix_terms_document_versions_effective', 'terms_document_versions', ['required', 'effective_at'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('date_format', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inactive_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('audience_personas',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('age_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('situations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('challenges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_level', sa.String(length=16), nullable=False),
    sa.Column('search_intents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('journey_stage', sa.String(length=24), nullable=False),
    sa.Column('prohibited_targeting', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("journey_stage IN ('AWARENESS', 'CONSIDERATION', 'PURCHASE', 'RETENTION')", name=op.f('ck_audience_personas_persona_journey_stage')),
    sa.CheckConstraint("knowledge_level IN ('BEGINNER', 'GENERAL', 'EXPERT')", name=op.f('ck_audience_personas_persona_knowledge_level')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_audience_personas_persona_status')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_audience_personas_persona_lock_version_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_audience_personas_brand_id_brands'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audience_personas'))
    )
    op.create_index(op.f('ix_audience_personas_brand_id'), 'audience_personas', ['brand_id'], unique=False)
    op.create_index('ix_audience_personas_workspace_brand', 'audience_personas', ['workspace_id', 'brand_id'], unique=False)
    op.create_index(op.f('ix_audience_personas_workspace_id'), 'audience_personas', ['workspace_id'], unique=False)
    op.create_index('ix_audience_personas_workspace_status', 'audience_personas', ['workspace_id', 'status'], unique=False)
    op.create_table('authentication_challenges',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_authentication_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_authentication_challenges')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_authentication_challenges_token_hash'))
    )
    op.create_index('ix_authentication_challenges_expiry', 'authentication_challenges', ['expires_at'], unique=False)
    op.create_index('ix_authentication_challenges_lookup', 'authentication_challenges', ['purpose', 'token_hash'], unique=False)
    op.create_index(op.f('ix_authentication_challenges_user_id'), 'authentication_challenges', ['user_id'], unique=False)
    op.create_table('brand_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_expressions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_dictionary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visual_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('style_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_style_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_brand_versions_brand_version_lock_positive')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_brand_versions_brand_version_number_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brand_versions_brand_id_brands'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_versions')),
    sa.UniqueConstraint('workspace_id', 'brand_id', 'content_hash', name='brand_version_hash'),
    sa.UniqueConstraint('workspace_id', 'brand_id', 'version_number', name='brand_version_no')
    )
    op.create_index(op.f('ix_brand_versions_brand_id'), 'brand_versions', ['brand_id'], unique=False)
    op.create_index('ix_brand_versions_workspace_effective', 'brand_versions', ['workspace_id', 'brand_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_brand_versions_workspace_id'), 'brand_versions', ['workspace_id'], unique=False)
    op.create_table('identity_one_time_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identity_one_time_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_one_time_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_identity_one_time_tokens_token_hash'))
    )
    op.create_index('ix_identity_one_time_tokens_expiry', 'identity_one_time_tokens', ['expires_at'], unique=False)
    op.create_index('ix_identity_one_time_tokens_lookup', 'identity_one_time_tokens', ['purpose', 'token_hash'], unique=False)
    op.create_index(op.f('ix_identity_one_time_tokens_user_id'), 'identity_one_time_tokens', ['user_id'], unique=False)
    op.create_table('knowledge_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['knowledge_sources.workspace_id', 'knowledge_sources.id'], name=op.f('fk_knowledge_jobs_workspace_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_jobs'))
    )
    op.create_index(op.f('ix_knowledge_jobs_requested_by'), 'knowledge_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_knowledge_jobs_source_id'), 'knowledge_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_knowledge_jobs_workspace_id'), 'knowledge_jobs', ['workspace_id'], unique=False)
    op.create_index('ix_knowledge_jobs_workspace_state', 'knowledge_jobs', ['workspace_id', 'state'], unique=False)
    op.create_table('login_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('device_id_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('authentication_methods', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mfa_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_sessions'))
    )
    op.create_index('ix_login_sessions_expiry', 'login_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_login_sessions_family_id'), 'login_sessions', ['family_id'], unique=False)
    op.create_index(op.f('ix_login_sessions_user_id'), 'login_sessions', ['user_id'], unique=False)
    op.create_index('ix_login_sessions_user_status', 'login_sessions', ['user_id', 'status'], unique=False)
    op.create_table('mfa_factors',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('secret_ciphertext', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_step', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_factors_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_factors'))
    )
    op.create_index(op.f('ix_mfa_factors_user_id'), 'mfa_factors', ['user_id'], unique=False)
    op.create_index('ix_mfa_factors_user_status', 'mfa_factors', ['user_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('MANUAL', 'CSV', 'API', 'SHOPIFY', 'CAFE24')", name=op.f('ck_products_product_source')),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_products_product_status')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_products_product_lock_version_positive')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('workspace_id', 'brand_id', 'sku', name='product_brand_sku')
    )
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_current_version_id'), 'products', ['current_version_id'], unique=False)
    op.create_index('ix_products_workspace_brand', 'products', ['workspace_id', 'brand_id'], unique=False)
    op.create_index(op.f('ix_products_workspace_id'), 'products', ['workspace_id'], unique=False)
    op.create_index('ix_products_workspace_status', 'products', ['workspace_id', 'status'], unique=False)
    op.create_table('source_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_object_key', sa.Text(), nullable=True),
    sa.Column('source_etag', sa.String(length=512), nullable=True),
    sa.Column('source_last_modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['knowledge_sources.workspace_id', 'knowledge_sources.id'], name=op.f('fk_source_versions_workspace_id_knowledge_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_versions')),
    sa.UniqueConstraint('workspace_id', 'id', name='source_version_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'source_id', 'content_hash', name='source_version_hash'),
    sa.UniqueConstraint('workspace_id', 'source_id', 'version', name='source_version_number')
    )
    op.create_index(op.f('ix_source_versions_source_id'), 'source_versions', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_versions_workspace_id'), 'source_versions', ['workspace_id'], unique=False)
    op.create_table('terms_consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('document_version', sa.String(length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_terms_consents_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms_consents')),
    sa.UniqueConstraint('user_id', 'document_type', 'document_version', name='uq_terms_consents_version')
    )
    op.create_index(op.f('ix_terms_consents_user_id'), 'terms_consents', ['user_id'], unique=False)
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('last_failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_credentials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_credentials')),
    sa.UniqueConstraint('user_id', 'kind', name='uq_user_credentials_user_kind')
    )
    op.create_index(op.f('ix_user_credentials_user_id'), 'user_credentials', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_locale', sa.String(length=16), nullable=False),
    sa.Column('data_region', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('retention_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_channel_ref', sa.String(length=255), nullable=True),
    sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_workspaces_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index(op.f('ix_workspaces_status'), 'workspaces', ['status'], unique=False)
    op.create_table('agencies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('white_label_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('common_template_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agencies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agencies')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_agencies_workspace_id'))
    )
    op.create_table('federated_provider_connections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=True),
    sa.Column('discovery_url', sa.String(length=1000), nullable=True),
    sa.Column('client_id', sa.String(length=500), nullable=True),
    sa.Column('secret_ref', sa.String(length=500), nullable=True),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('jit_provisioning_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_federated_provider_connections_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_federated_provider_connections')),
    sa.UniqueConstraint('workspace_id', 'provider_key', name='uq_federated_provider_key')
    )
    op.create_index(op.f('ix_federated_provider_connections_workspace_id'), 'federated_provider_connections', ['workspace_id'], unique=False)
    op.create_table('mfa_recovery_codes',
    sa.Column('factor_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['factor_id'], ['mfa_factors.id'], name=op.f('fk_mfa_recovery_codes_factor_id_mfa_factors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_recovery_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_mfa_recovery_codes_code_hash'))
    )
    op.create_index(op.f('ix_mfa_recovery_codes_factor_id'), 'mfa_recovery_codes', ['factor_id'], unique=False)
    op.create_table('product_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_url', sa.String(length=2048), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comparison_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('shipping_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_product_versions_product_version_lock_positive')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_product_versions_product_version_number_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_versions_product_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_versions')),
    sa.UniqueConstraint('workspace_id', 'product_id', 'content_hash', name='product_version_hash'),
    sa.UniqueConstraint('workspace_id', 'product_id', 'version_number', name='product_version_no')
    )
    op.create_index(op.f('ix_product_versions_product_id'), 'product_versions', ['product_id'], unique=False)
    op.create_index('ix_product_versions_workspace_effective', 'product_versions', ['workspace_id', 'product_id', 'effective_from'], unique=False)
    op.create_index(op.f('ix_product_versions_workspace_id'), 'product_versions', ['workspace_id'], unique=False)
    op.create_table('roles',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_roles_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_roles_workspace_key'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_roles_workspace_name')
    )
    op.create_index(op.f('ix_roles_workspace_id'), 'roles', ['workspace_id'], unique=False)
    op.create_table('scim_configurations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('bearer_token_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_ref', sa.String(length=500), nullable=True),
    sa.Column('attribute_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_role_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scim_configurations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scim_configurations')),
    sa.UniqueConstraint('bearer_token_hash', name=op.f('uq_scim_configurations_bearer_token_hash')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_scim_configurations_workspace_id'))
    )
    op.create_table('session_refresh_tokens',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['session_refresh_tokens.id'], name=op.f('fk_session_refresh_tokens_replaced_by_id_session_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['login_sessions.id'], name=op.f('fk_session_refresh_tokens_session_id_login_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_refresh_tokens')),
    sa.UniqueConstraint('session_id', 'generation', name='uq_session_refresh_generation'),
    sa.UniqueConstraint('token_hash', name=op.f('uq_session_refresh_tokens_token_hash'))
    )
    op.create_index('ix_session_refresh_tokens_expiry', 'session_refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_refresh_tokens_session_id'), 'session_refresh_tokens', ['session_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('structure_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(text, ''))", persisted=True), nullable=True),
    sa.Column('parse_quality_score', sa.Float(), nullable=False),
    sa.Column('pii_detected', sa.Boolean(), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'source_version_id'], ['source_versions.workspace_id', 'source_versions.id'], name=op.f('fk_source_documents_workspace_id_source_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('workspace_id', 'source_version_id', 'id', name='source_document_lineage_id')
    )
    op.create_index('ix_source_documents_search', 'source_documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_source_documents_source_version_id'), 'source_documents', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_source_documents_workspace_id'), 'source_documents', ['workspace_id'], unique=False)
    op.create_index('ix_source_documents_workspace_version', 'source_documents', ['workspace_id', 'source_version_id'], unique=False)
    op.create_table('workspace_authentication_policies',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=False),
    sa.Column('max_login_failures', sa.Integer(), nullable=False),
    sa.Column('lockout_seconds', sa.Integer(), nullable=False),
    sa.Column('access_token_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('session_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('require_mfa_role_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('password_login_enabled', sa.Boolean(), nullable=False),
    sa.Column('sso_enforced_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_authentication_policies_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_authentication_policies')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_workspace_authentication_policies_workspace_id'))
    )
    op.create_table('agency_clients',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('client_workspace_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('billing_allocation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name=op.f('fk_agency_clients_agency_id_agencies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_workspace_id'], ['workspaces.id'], name=op.f('fk_agency_clients_client_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agency_clients_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agency_clients')),
    sa.UniqueConstraint('agency_id', 'client_workspace_id', name='uq_agency_client_workspace'),
    sa.UniqueConstraint('client_workspace_id', name='uq_agency_clients_client_workspace')
    )
    op.create_index(op.f('ix_agency_clients_agency_id'), 'agency_clients', ['agency_id'], unique=False)
    op.create_index(op.f('ix_agency_clients_client_workspace_id'), 'agency_clients', ['client_workspace_id'], unique=False)
    op.create_index(op.f('ix_agency_clients_workspace_id'), 'agency_clients', ['workspace_id'], unique=False)
    op.create_table('external_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('email_at_link', sa.String(length=320), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['federated_provider_connections.id'], name=op.f('fk_external_identities_connection_id_federated_provider_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_external_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_identities')),
    sa.UniqueConstraint('issuer', 'subject', name='uq_external_identities_subject'),
    sa.UniqueConstraint('user_id', 'connection_id', name='uq_external_identities_user_connection')
    )
    op.create_index(op.f('ix_external_identities_connection_id'), 'external_identities', ['connection_id'], unique=False)
    op.create_index(op.f('ix_external_identities_user_id'), 'external_identities', ['user_id'], unique=False)
    op.create_table('memberships',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_memberships_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_memberships_workspace_user')
    )
    op.create_index(op.f('ix_memberships_role_id'), 'memberships', ['role_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index('ix_memberships_user_status', 'memberships', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_memberships_workspace_id'), 'memberships', ['workspace_id'], unique=False)
    op.create_table('product_assets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_version_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('uri', sa.String(length=2048), nullable=False),
    sa.Column('usage_scope', sa.String(length=120), nullable=False),
    sa.Column('license_name', sa.String(length=160), nullable=False),
    sa.Column('license_reference', sa.String(length=2048), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_product_assets_product_asset_lock_positive')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_product_assets_product_asset_sort_nonnegative')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name=op.f('ck_product_assets_product_asset_validity_ordered')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_assets_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], name=op.f('fk_product_assets_product_version_id_product_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_assets'))
    )
    op.create_index(op.f('ix_product_assets_media_asset_id'), 'product_assets', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_product_assets_product_id'), 'product_assets', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_assets_product_version_id'), 'product_assets', ['product_version_id'], unique=False)
    op.create_index(op.f('ix_product_assets_workspace_id'), 'product_assets', ['workspace_id'], unique=False)
    op.create_index('ix_product_assets_workspace_version', 'product_assets', ['workspace_id', 'product_version_id'], unique=False)
    op.create_table('product_links',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_version_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('disclosure_required', sa.Boolean(), nullable=False),
    sa.Column('disclosure_text', sa.String(length=500), nullable=True),
    sa.Column('tracking', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("kind <> 'AFFILIATE' OR disclosure_required", name=op.f('ck_product_links_affiliate_disclosure_required')),
    sa.CheckConstraint("kind IN ('OFFICIAL', 'AFFILIATE', 'TRACKED')", name=op.f('ck_product_links_product_link_kind')),
    sa.CheckConstraint('NOT disclosure_required OR disclosure_text IS NOT NULL', name=op.f('ck_product_links_product_link_disclosure_text_required')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_product_links_product_link_lock_positive')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_product_links_product_link_sort_nonnegative')),
    sa.CheckConstraint('valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from', name=op.f('ck_product_links_product_link_validity_ordered')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_links_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], name=op.f('fk_product_links_product_version_id_product_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_links'))
    )
    op.create_index(op.f('ix_product_links_product_id'), 'product_links', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_links_product_version_id'), 'product_links', ['product_version_id'], unique=False)
    op.create_index(op.f('ix_product_links_workspace_id'), 'product_links', ['workspace_id'], unique=False)
    op.create_index('ix_product_links_workspace_version', 'product_links', ['workspace_id', 'product_version_id'], unique=False)
    op.create_table('product_variants',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_version_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('option_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_product_variants_product_variant_lock_positive')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_product_variants_product_variant_sort_nonnegative')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], name=op.f('fk_product_variants_product_version_id_product_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    sa.UniqueConstraint('workspace_id', 'product_version_id', 'sku', name='product_variant_sku')
    )
    op.create_index(op.f('ix_product_variants_product_id'), 'product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_variants_product_version_id'), 'product_variants', ['product_version_id'], unique=False)
    op.create_index(op.f('ix_product_variants_workspace_id'), 'product_variants', ['workspace_id'], unique=False)
    op.create_index('ix_product_variants_workspace_version', 'product_variants', ['workspace_id', 'product_version_id'], unique=False)
    op.create_table('scim_resource_links',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('configuration_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['scim_configurations.id'], name=op.f('fk_scim_resource_links_configuration_id_scim_configurations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_scim_resource_links_role_id_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scim_resource_links_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_scim_resource_links_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scim_resource_links')),
    sa.UniqueConstraint('configuration_id', 'resource_type', 'external_id', name='uq_scim_resource_external_id')
    )
    op.create_index(op.f('ix_scim_resource_links_workspace_id'), 'scim_resource_links', ['workspace_id'], unique=False)
    op.create_table('source_chunks',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('locator_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('quality_grade', sa.String(length=1), nullable=False),
    sa.Column('pii_masked', sa.Boolean(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'source_version_id', 'document_id'], ['source_documents.workspace_id', 'source_documents.source_version_id', 'source_documents.id'], name=op.f('fk_source_chunks_workspace_id_source_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_chunks')),
    sa.UniqueConstraint('workspace_id', 'document_id', 'sequence', name='source_chunk_sequence')
    )
    op.create_index(op.f('ix_source_chunks_document_id'), 'source_chunks', ['document_id'], unique=False)
    op.create_index('ix_source_chunks_embedding_hnsw', 'source_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_source_chunks_source_version_id'), 'source_chunks', ['source_version_id'], unique=False)
    op.create_index('ix_source_chunks_workspace_hash', 'source_chunks', ['workspace_id', 'text_hash'], unique=False)
    op.create_index(op.f('ix_source_chunks_workspace_id'), 'source_chunks', ['workspace_id'], unique=False)
    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('invited_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], name=op.f('fk_workspace_invitations_accepted_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_workspace_invitations_invited_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_workspace_invitations_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_invitations_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_workspace_invitations_token_hash'))
    )
    op.create_index('ix_workspace_invitations_expiry', 'workspace_invitations', ['expires_at'], unique=False)
    op.create_index('ix_workspace_invitations_pending', 'workspace_invitations', ['workspace_id', 'email', 'status'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('product_prices',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_version_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('compare_at_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_product_prices_product_price_amount_nonnegative')),
    sa.CheckConstraint('char_length(currency) = 3 AND currency = upper(currency)', name=op.f('ck_product_prices_product_price_currency')),
    sa.CheckConstraint('compare_at_amount IS NULL OR compare_at_amount >= amount', name=op.f('ck_product_prices_product_price_comparison_valid')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_product_prices_product_price_lock_positive')),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name=op.f('ck_product_prices_product_price_validity_ordered')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_prices_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_version_id'], ['product_versions.id'], name=op.f('fk_product_prices_product_version_id_product_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_product_prices_variant_id_product_variants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_prices'))
    )
    op.create_index(op.f('ix_product_prices_product_id'), 'product_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_prices_product_version_id'), 'product_prices', ['product_version_id'], unique=False)
    op.create_index(op.f('ix_product_prices_variant_id'), 'product_prices', ['variant_id'], unique=False)
    op.create_index(op.f('ix_product_prices_workspace_id'), 'product_prices', ['workspace_id'], unique=False)
    op.create_index('ix_product_prices_workspace_validity', 'product_prices', ['workspace_id', 'product_id', 'valid_from', 'valid_to'], unique=False)
    op.create_foreign_key(
        "fk_brands_current_version_id_brand_versions",
        "brands",
        "brand_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_products_current_version_id_product_versions",
        "products",
        "product_versions",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_knowledge_sources_current_version",
        "knowledge_sources",
        "source_versions",
        ["workspace_id", "current_version_id"],
        ["workspace_id", "id"],
        ondelete="RESTRICT",
        deferrable=True,
        initially="DEFERRED",
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.current_user_id()
        RETURNS uuid
        LANGUAGE sql
        STABLE
        AS $$
            SELECT NULLIF(current_setting('app.current_user_id', true), '')::uuid
        $$
        """
    )

    tenant_tables = (
        "agencies",
        "agency_clients",
        "audience_personas",
        "brand_versions",
        "brands",
        "federated_provider_connections",
        "knowledge_jobs",
        "knowledge_sources",
        "product_assets",
        "product_links",
        "product_prices",
        "product_variants",
        "product_versions",
        "products",
        "scim_configurations",
        "scim_resource_links",
        "source_chunks",
        "source_documents",
        "source_versions",
        "workspace_authentication_policies",
        "workspace_invitations",
    )
    for table_name in tenant_tables:
        op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {table_name}_workspace_isolation ON {table_name}
            USING (workspace_id = app.current_workspace_id())
            WITH CHECK (workspace_id = app.current_workspace_id())
            """
        )

    op.execute("ALTER TABLE memberships ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE memberships FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY memberships_self_or_workspace_read ON memberships
        FOR SELECT
        USING (
            workspace_id = app.current_workspace_id()
            OR user_id = app.current_user_id()
        )
        """
    )
    op.execute(
        """
        CREATE POLICY memberships_workspace_insert ON memberships
        FOR INSERT
        WITH CHECK (workspace_id = app.current_workspace_id())
        """
    )
    op.execute(
        """
        CREATE POLICY memberships_workspace_update ON memberships
        FOR UPDATE
        USING (workspace_id = app.current_workspace_id())
        WITH CHECK (workspace_id = app.current_workspace_id())
        """
    )
    op.execute(
        """
        CREATE POLICY memberships_workspace_delete ON memberships
        FOR DELETE
        USING (workspace_id = app.current_workspace_id())
        """
    )

    op.execute("ALTER TABLE roles ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE roles FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY roles_member_read ON roles
        FOR SELECT
        USING (
            workspace_id = app.current_workspace_id()
            OR EXISTS (
                SELECT 1
                FROM memberships
                WHERE memberships.workspace_id = roles.workspace_id
                  AND memberships.user_id = app.current_user_id()
            )
        )
        """
    )
    op.execute(
        """
        CREATE POLICY roles_workspace_write ON roles
        FOR ALL
        USING (workspace_id = app.current_workspace_id())
        WITH CHECK (workspace_id = app.current_workspace_id())
        """
    )

    op.execute("ALTER TABLE workspaces ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE workspaces FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY workspaces_member_read ON workspaces
        FOR SELECT
        USING (
            id = app.current_workspace_id()
            OR EXISTS (
                SELECT 1
                FROM memberships
                WHERE memberships.workspace_id = workspaces.id
                  AND memberships.user_id = app.current_user_id()
            )
        )
        """
    )
    for command in ("INSERT", "UPDATE", "DELETE"):
        using = "" if command == "INSERT" else "USING (id = app.current_workspace_id())"
        check = "" if command == "DELETE" else "WITH CHECK (id = app.current_workspace_id())"
        op.execute(
            f"""
            CREATE POLICY workspaces_tenant_{command.casefold()} ON workspaces
            FOR {command}
            {using}
            {check}
            """
        )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION app.reject_snapshot_update()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'immutable snapshot rows cannot be updated';
        END;
        $$
        """
    )
    immutable_tables = (
        "brand_versions",
        "product_assets",
        "product_links",
        "product_prices",
        "product_variants",
        "product_versions",
        "source_chunks",
        "source_documents",
        "source_versions",
        "terms_consents",
    )
    for table_name in immutable_tables:
        op.execute(
            f"""
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
            """
        )

    app_mutable_tables = (
        "agencies",
        "agency_clients",
        "audience_personas",
        "authentication_challenges",
        "brand_versions",
        "brands",
        "external_identities",
        "federated_provider_connections",
        "identity_one_time_tokens",
        "knowledge_jobs",
        "knowledge_sources",
        "login_sessions",
        "memberships",
        "mfa_factors",
        "mfa_recovery_codes",
        "product_assets",
        "product_links",
        "product_prices",
        "product_variants",
        "product_versions",
        "products",
        "roles",
        "scim_configurations",
        "scim_resource_links",
        "session_refresh_tokens",
        "source_chunks",
        "source_documents",
        "source_versions",
        "terms_consents",
        "user_credentials",
        "users",
        "workspace_authentication_policies",
        "workspace_invitations",
        "workspaces",
    )
    worker_tables = (
        "knowledge_jobs",
        "knowledge_sources",
        "source_chunks",
        "source_documents",
        "source_versions",
    )
    op.execute(
        f"""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_app') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_app;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(app_mutable_tables)} TO blogops_app;
                GRANT SELECT ON terms_document_versions TO blogops_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_worker') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_worker;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(worker_tables)} TO blogops_worker;
            END IF;
        END
        $$
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_knowledge_sources_current_version", "knowledge_sources", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_products_current_version_id_product_versions", "products", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_brands_current_version_id_brand_versions", "brands", type_="foreignkey"
    )
    op.drop_index('ix_product_prices_workspace_validity', table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_workspace_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_variant_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_product_version_id'), table_name='product_prices')
    op.drop_index(op.f('ix_product_prices_product_id'), table_name='product_prices')
    op.drop_table('product_prices')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_pending', table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_expiry', table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_index(op.f('ix_source_chunks_workspace_id'), table_name='source_chunks')
    op.drop_index('ix_source_chunks_workspace_hash', table_name='source_chunks')
    op.drop_index(op.f('ix_source_chunks_source_version_id'), table_name='source_chunks')
    op.drop_index('ix_source_chunks_embedding_hnsw', table_name='source_chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_source_chunks_document_id'), table_name='source_chunks')
    op.drop_table('source_chunks')
    op.drop_index(op.f('ix_scim_resource_links_workspace_id'), table_name='scim_resource_links')
    op.drop_table('scim_resource_links')
    op.drop_index('ix_product_variants_workspace_version', table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_workspace_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_version_id'), table_name='product_variants')
    op.drop_index(op.f('ix_product_variants_product_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_index('ix_product_links_workspace_version', table_name='product_links')
    op.drop_index(op.f('ix_product_links_workspace_id'), table_name='product_links')
    op.drop_index(op.f('ix_product_links_product_version_id'), table_name='product_links')
    op.drop_index(op.f('ix_product_links_product_id'), table_name='product_links')
    op.drop_table('product_links')
    op.drop_index('ix_product_assets_workspace_version', table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_workspace_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_product_version_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_product_id'), table_name='product_assets')
    op.drop_index(op.f('ix_product_assets_media_asset_id'), table_name='product_assets')
    op.drop_table('product_assets')
    op.drop_index(op.f('ix_memberships_workspace_id'), table_name='memberships')
    op.drop_index('ix_memberships_user_status', table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_role_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_external_identities_user_id'), table_name='external_identities')
    op.drop_index(op.f('ix_external_identities_connection_id'), table_name='external_identities')
    op.drop_table('external_identities')
    op.drop_index(op.f('ix_agency_clients_workspace_id'), table_name='agency_clients')
    op.drop_index(op.f('ix_agency_clients_client_workspace_id'), table_name='agency_clients')
    op.drop_index(op.f('ix_agency_clients_agency_id'), table_name='agency_clients')
    op.drop_table('agency_clients')
    op.drop_table('workspace_authentication_policies')
    op.drop_index('ix_source_documents_workspace_version', table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_workspace_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_source_version_id'), table_name='source_documents')
    op.drop_index('ix_source_documents_search', table_name='source_documents', postgresql_using='gin')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_session_refresh_tokens_session_id'), table_name='session_refresh_tokens')
    op.drop_index('ix_session_refresh_tokens_expiry', table_name='session_refresh_tokens')
    op.drop_table('session_refresh_tokens')
    op.drop_table('scim_configurations')
    op.drop_index(op.f('ix_roles_workspace_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_product_versions_workspace_id'), table_name='product_versions')
    op.drop_index('ix_product_versions_workspace_effective', table_name='product_versions')
    op.drop_index(op.f('ix_product_versions_product_id'), table_name='product_versions')
    op.drop_table('product_versions')
    op.drop_index(op.f('ix_mfa_recovery_codes_factor_id'), table_name='mfa_recovery_codes')
    op.drop_table('mfa_recovery_codes')
    op.drop_index(op.f('ix_federated_provider_connections_workspace_id'), table_name='federated_provider_connections')
    op.drop_table('federated_provider_connections')
    op.drop_table('agencies')
    op.drop_index(op.f('ix_workspaces_status'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_user_credentials_user_id'), table_name='user_credentials')
    op.drop_table('user_credentials')
    op.drop_index(op.f('ix_terms_consents_user_id'), table_name='terms_consents')
    op.drop_table('terms_consents')
    op.drop_index(op.f('ix_source_versions_workspace_id'), table_name='source_versions')
    op.drop_index(op.f('ix_source_versions_source_id'), table_name='source_versions')
    op.drop_table('source_versions')
    op.drop_index('ix_products_workspace_status', table_name='products')
    op.drop_index(op.f('ix_products_workspace_id'), table_name='products')
    op.drop_index('ix_products_workspace_brand', table_name='products')
    op.drop_index(op.f('ix_products_current_version_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_mfa_factors_user_status', table_name='mfa_factors')
    op.drop_index(op.f('ix_mfa_factors_user_id'), table_name='mfa_factors')
    op.drop_table('mfa_factors')
    op.drop_index('ix_login_sessions_user_status', table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_user_id'), table_name='login_sessions')
    op.drop_index(op.f('ix_login_sessions_family_id'), table_name='login_sessions')
    op.drop_index('ix_login_sessions_expiry', table_name='login_sessions')
    op.drop_table('login_sessions')
    op.drop_index('ix_knowledge_jobs_workspace_state', table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_workspace_id'), table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_source_id'), table_name='knowledge_jobs')
    op.drop_index(op.f('ix_knowledge_jobs_requested_by'), table_name='knowledge_jobs')
    op.drop_table('knowledge_jobs')
    op.drop_index(op.f('ix_identity_one_time_tokens_user_id'), table_name='identity_one_time_tokens')
    op.drop_index('ix_identity_one_time_tokens_lookup', table_name='identity_one_time_tokens')
    op.drop_index('ix_identity_one_time_tokens_expiry', table_name='identity_one_time_tokens')
    op.drop_table('identity_one_time_tokens')
    op.drop_index(op.f('ix_brand_versions_workspace_id'), table_name='brand_versions')
    op.drop_index('ix_brand_versions_workspace_effective', table_name='brand_versions')
    op.drop_index(op.f('ix_brand_versions_brand_id'), table_name='brand_versions')
    op.drop_table('brand_versions')
    op.drop_index(op.f('ix_authentication_challenges_user_id'), table_name='authentication_challenges')
    op.drop_index('ix_authentication_challenges_lookup', table_name='authentication_challenges')
    op.drop_index('ix_authentication_challenges_expiry', table_name='authentication_challenges')
    op.drop_table('authentication_challenges')
    op.drop_index('ix_audience_personas_workspace_status', table_name='audience_personas')
    op.drop_index(op.f('ix_audience_personas_workspace_id'), table_name='audience_personas')
    op.drop_index('ix_audience_personas_workspace_brand', table_name='audience_personas')
    op.drop_index(op.f('ix_audience_personas_brand_id'), table_name='audience_personas')
    op.drop_table('audience_personas')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_terms_document_versions_effective', table_name='terms_document_versions')
    op.drop_table('terms_document_versions')
    op.drop_index('ix_knowledge_sources_workspace_state', table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_workspace_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_current_version_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_created_by'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    op.drop_index('ix_brands_workspace_status', table_name='brands')
    op.drop_index(op.f('ix_brands_workspace_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_current_version_id'), table_name='brands')
    op.drop_table('brands')
    op.execute("DROP FUNCTION IF EXISTS app.reject_snapshot_update()")
    op.execute("DROP FUNCTION IF EXISTS app.current_user_id()")
    # ### end Alembic commands ###
