"""add keywords and planning

Revision ID: e05c23a4bbb7
Revises: 0002_tenancy_auth_knowledge
Create Date: 2026-08-23 12:55:08.658014
"""

from collections.abc import Sequence

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e05c23a4bbb7'
down_revision: str | None = '0002_tenancy_auth_knowledge'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('brand_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('brand_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('budget_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_enforcement', sa.String(length=16), nullable=False),
    sa.Column('generation_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_campaigns_planning_campaign_dates_ordered')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_campaigns_planning_campaign_lock_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_campaign_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'name', name='planning_campaign_workspace_name')
    )
    op.create_index(op.f('ix_campaigns_brand_id'), 'campaigns', ['brand_id'], unique=False)
    op.create_index(op.f('ix_campaigns_created_by'), 'campaigns', ['created_by'], unique=False)
    op.create_index(op.f('ix_campaigns_workspace_id'), 'campaigns', ['workspace_id'], unique=False)
    op.create_index('ix_planning_campaign_workspace_dates', 'campaigns', ['workspace_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_planning_campaign_workspace_status', 'campaigns', ['workspace_id', 'status'], unique=False)
    op.create_table('content_board_columns',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_board_columns_planning_board_column_lock_positive')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_content_board_columns_board_position_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_board_columns')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_board_column_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'key', name='planning_board_column_key'),
    sa.UniqueConstraint('workspace_id', 'position', name='planning_board_column_position')
    )
    op.create_index(op.f('ix_content_board_columns_workspace_id'), 'content_board_columns', ['workspace_id'], unique=False)
    op.create_table('keyword_collections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('campaign_opaque_ref', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_collections')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_collection_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'kind', 'name', name='keyword_collection_kind_name')
    )
    op.create_index(op.f('ix_keyword_collections_campaign_opaque_ref'), 'keyword_collections', ['campaign_opaque_ref'], unique=False)
    op.create_index(op.f('ix_keyword_collections_workspace_id'), 'keyword_collections', ['workspace_id'], unique=False)
    op.create_table('keyword_provider_connections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('source_class', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('credential_owner', sa.String(length=16), nullable=False),
    sa.Column('secret_ref', sa.String(length=512), nullable=True),
    sa.Column('license_ref', sa.String(length=512), nullable=True),
    sa.Column('license_valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('circuit_open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_quota IS NULL OR daily_quota > 0', name=op.f('ck_keyword_provider_connections_keyword_provider_quota_positive')),
    sa.CheckConstraint('quota_remaining IS NULL OR quota_remaining >= 0', name=op.f('ck_keyword_provider_connections_provider_remaining_nonnegative')),
    sa.CheckConstraint('ttl_seconds > 0', name=op.f('ck_keyword_provider_connections_keyword_provider_ttl_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_provider_connections')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_provider_connection_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'name', name='keyword_provider_connection_name')
    )
    op.create_index(op.f('ix_keyword_provider_connections_workspace_id'), 'keyword_provider_connections', ['workspace_id'], unique=False)
    op.create_index('ix_keyword_provider_quota_reset', 'keyword_provider_connections', ['workspace_id', 'quota_reset_at'], unique=False)
    op.create_index('ix_keyword_provider_workspace_state', 'keyword_provider_connections', ['workspace_id', 'state'], unique=False)
    op.create_table('keyword_saved_views',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('filters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_saved_views')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_saved_view_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'owner_id', 'name', name='keyword_saved_view_owner_name')
    )
    op.create_index(op.f('ix_keyword_saved_views_owner_id'), 'keyword_saved_views', ['owner_id'], unique=False)
    op.create_index(op.f('ix_keyword_saved_views_workspace_id'), 'keyword_saved_views', ['workspace_id'], unique=False)
    op.create_table('keyword_score_profiles',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('weights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_keyword_score_profiles_score_profile_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_score_profiles')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_score_profile_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'name', 'version', name='keyword_score_profile_version')
    )
    op.create_index('ix_keyword_score_profiles_active', 'keyword_score_profiles', ['workspace_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_keyword_score_profiles_workspace_id'), 'keyword_score_profiles', ['workspace_id'], unique=False)
    op.create_table('keywords',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('display_text', sa.String(length=1000), nullable=False),
    sa.Column('normalized', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('intent', sa.String(length=24), nullable=False),
    sa.Column('intent_source', sa.String(length=24), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=False),
    sa.Column('intent_signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_alignment', sa.Float(), nullable=False),
    sa.Column('risk_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=240), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('embedding_model', sa.String(length=160), nullable=True),
    sa.Column('embedding_version', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('brand_alignment >= 0 AND brand_alignment <= 1', name=op.f('ck_keywords_keyword_brand_alignment_range')),
    sa.CheckConstraint('intent_confidence >= 0 AND intent_confidence <= 1', name=op.f('ck_keywords_keyword_intent_confidence_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keywords')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'language', 'region', 'normalized', name='keyword_workspace_language_region_normalized')
    )
    op.create_index(op.f('ix_keywords_created_by'), 'keywords', ['created_by'], unique=False)
    op.create_index(op.f('ix_keywords_workspace_id'), 'keywords', ['workspace_id'], unique=False)
    op.create_index('ix_keywords_workspace_intent', 'keywords', ['workspace_id', 'intent'], unique=False)
    op.create_index('ix_keywords_workspace_normalized', 'keywords', ['workspace_id', 'normalized'], unique=False)
    op.create_table('planning_comments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_planning_comments_planning_comment_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_comment_id'], ['planning_comments.workspace_id', 'planning_comments.id'], name=op.f('fk_planning_comments_workspace_id_planning_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_comments')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_comment_workspace_id')
    )
    op.create_index('ix_planning_comment_target', 'planning_comments', ['workspace_id', 'target_type', 'target_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_planning_comments_target_id'), 'planning_comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_planning_comments_workspace_id'), 'planning_comments', ['workspace_id'], unique=False)
    op.create_table('campaign_spend_ledger',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('amount >= 0', name=op.f('ck_campaign_spend_ledger_campaign_spend_nonnegative')),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_campaign_spend_ledger_campaign_spend_currency_length')),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_campaign_spend_ledger_workspace_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_spend_ledger')),
    sa.UniqueConstraint('workspace_id', 'campaign_id', 'source_ref', name='campaign_spend_source')
    )
    op.create_index(op.f('ix_campaign_spend_ledger_campaign_id'), 'campaign_spend_ledger', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_spend_ledger_recorded_by'), 'campaign_spend_ledger', ['recorded_by'], unique=False)
    op.create_index(op.f('ix_campaign_spend_ledger_workspace_id'), 'campaign_spend_ledger', ['workspace_id'], unique=False)
    op.create_index('ix_campaign_spend_workspace_campaign', 'campaign_spend_ledger', ['workspace_id', 'campaign_id', 'occurred_at'], unique=False)
    op.create_table('keyword_alert_rules',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('kinds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thresholds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cadence_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_evaluate_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_alert_rules_workspace_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_alert_rules')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_alert_rule_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'keyword_id', 'owner_id', name='keyword_alert_owner')
    )
    op.create_index(op.f('ix_keyword_alert_rules_keyword_id'), 'keyword_alert_rules', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_alert_rules_owner_id'), 'keyword_alert_rules', ['owner_id'], unique=False)
    op.create_index(op.f('ix_keyword_alert_rules_workspace_id'), 'keyword_alert_rules', ['workspace_id'], unique=False)
    op.create_index('ix_keyword_alerts_due', 'keyword_alert_rules', ['workspace_id', 'enabled', 'next_evaluate_at'], unique=False)
    op.create_table('keyword_clusters',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('primary_keyword_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decision_state', sa.String(length=24), nullable=False),
    sa.Column('decision_required', sa.Boolean(), nullable=False),
    sa.Column('signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_keyword_clusters_keyword_cluster_confidence')),
    sa.CheckConstraint('version > 0', name=op.f('ck_keyword_clusters_keyword_cluster_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'primary_keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_clusters_workspace_id_keywords'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_clusters')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_cluster_workspace_id')
    )
    op.create_index(op.f('ix_keyword_clusters_primary_keyword_id'), 'keyword_clusters', ['primary_keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_clusters_workspace_id'), 'keyword_clusters', ['workspace_id'], unique=False)
    op.create_index('ix_keyword_clusters_workspace_kind', 'keyword_clusters', ['workspace_id', 'kind'], unique=False)
    op.create_table('keyword_collection_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('added_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'collection_id'], ['keyword_collections.workspace_id', 'keyword_collections.id'], name=op.f('fk_keyword_collection_members_workspace_id_keyword_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_collection_members_workspace_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_collection_members')),
    sa.UniqueConstraint('workspace_id', 'collection_id', 'keyword_id', name='keyword_collection_member_identity')
    )
    op.create_index(op.f('ix_keyword_collection_members_collection_id'), 'keyword_collection_members', ['collection_id'], unique=False)
    op.create_index(op.f('ix_keyword_collection_members_keyword_id'), 'keyword_collection_members', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_collection_members_workspace_id'), 'keyword_collection_members', ['workspace_id'], unique=False)
    op.create_table('keyword_content_links',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.String(length=24), nullable=False),
    sa.Column('target_ref', sa.String(length=2048), nullable=False),
    sa.Column('target_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('mapped_intent', sa.String(length=24), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=24), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('similarity >= 0 AND similarity <= 1', name=op.f('ck_keyword_content_links_keyword_target_similarity')),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_content_links_workspace_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_content_links')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_content_link_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'keyword_id', 'target_kind', 'target_ref', name='keyword_target_identity')
    )
    op.create_index(op.f('ix_keyword_content_links_keyword_id'), 'keyword_content_links', ['keyword_id'], unique=False)
    op.create_index('ix_keyword_content_links_target', 'keyword_content_links', ['workspace_id', 'target_kind', 'target_ref'], unique=False)
    op.create_index(op.f('ix_keyword_content_links_workspace_id'), 'keyword_content_links', ['workspace_id'], unique=False)
    op.create_table('keyword_intent_revisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('previous_intent', sa.String(length=24), nullable=False),
    sa.Column('next_intent', sa.String(length=24), nullable=False),
    sa.Column('previous_source', sa.String(length=24), nullable=False),
    sa.Column('next_source', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_intent_revisions_workspace_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_intent_revisions')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_intent_revision_workspace_id')
    )
    op.create_index('ix_keyword_intent_history', 'keyword_intent_revisions', ['workspace_id', 'keyword_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_keyword_intent_revisions_keyword_id'), 'keyword_intent_revisions', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_intent_revisions_workspace_id'), 'keyword_intent_revisions', ['workspace_id'], unique=False)
    op.create_table('keyword_research_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('input_kind', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_keys_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requested_capabilities_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_profile_id', sa.Uuid(), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('excluded_items', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_after_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_keyword_research_jobs_keyword_job_attempt_nonnegative')),
    sa.CheckConstraint('failed_items >= 0', name=op.f('ck_keyword_research_jobs_keyword_job_failed_nonnegative')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_keyword_research_jobs_keyword_job_max_attempts_positive')),
    sa.CheckConstraint('processed_items >= 0', name=op.f('ck_keyword_research_jobs_keyword_job_processed_nonnegative')),
    sa.CheckConstraint('total_items >= 0', name=op.f('ck_keyword_research_jobs_keyword_job_total_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'score_profile_id'], ['keyword_score_profiles.workspace_id', 'keyword_score_profiles.id'], name=op.f('fk_keyword_research_jobs_workspace_id_keyword_score_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_research_jobs')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_research_job_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'input_kind', 'requested_by', 'idempotency_key', name='keyword_research_idempotency')
    )
    op.create_index('ix_keyword_jobs_workspace_state', 'keyword_research_jobs', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_keyword_research_jobs_requested_by'), 'keyword_research_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_keyword_research_jobs_score_profile_id'), 'keyword_research_jobs', ['score_profile_id'], unique=False)
    op.create_index(op.f('ix_keyword_research_jobs_workspace_id'), 'keyword_research_jobs', ['workspace_id'], unique=False)
    op.create_table('monthly_plan_proposals',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('requested_budget', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('provider_version', sa.String(length=80), nullable=False),
    sa.Column('generation_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('proposal_version', sa.Integer(), nullable=False),
    sa.Column('proposal_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_version', sa.Integer(), nullable=True),
    sa.Column('approved_hash', sa.String(length=64), nullable=True),
    sa.Column('rejected_by', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_monthly_plan_proposals_monthly_plan_lock_positive')),
    sa.CheckConstraint('proposal_version > 0', name=op.f('ck_monthly_plan_proposals_monthly_plan_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_monthly_plan_proposals_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_plan_proposals')),
    sa.UniqueConstraint('workspace_id', 'campaign_id', 'month', 'proposal_version', name='monthly_plan_version'),
    sa.UniqueConstraint('workspace_id', 'id', name='monthly_plan_workspace_id')
    )
    op.create_index(op.f('ix_monthly_plan_proposals_campaign_id'), 'monthly_plan_proposals', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_monthly_plan_proposals_workspace_id'), 'monthly_plan_proposals', ['workspace_id'], unique=False)
    op.create_index('ix_monthly_plan_workspace_month', 'monthly_plan_proposals', ['workspace_id', 'month', 'status'], unique=False)
    op.create_table('topic_clusters',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keyword_id', sa.Uuid(), nullable=True),
    sa.Column('keyword_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('keyword_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('search_intent', sa.String(length=24), nullable=False),
    sa.Column('intent_source', sa.String(length=16), nullable=False),
    sa.Column('journey_stage', sa.String(length=24), nullable=False),
    sa.Column('cta_recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('existing_content_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internal_link_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_gap_summary', sa.Text(), nullable=True),
    sa.Column('seasonality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('refresh_interval_days', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('merged_into_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_topic_clusters_planning_topic_node_lock_positive')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_topic_clusters_planning_topic_node_sort_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_topic_clusters_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'merged_into_id'], ['topic_clusters.workspace_id', 'topic_clusters.id'], name='fk_planning_topic_merged_into', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_id'], ['topic_clusters.workspace_id', 'topic_clusters.id'], name='fk_planning_topic_parent', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_clusters')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_topic_node_workspace_id')
    )
    op.create_index('ix_planning_topic_keyword_cluster', 'topic_clusters', ['workspace_id', 'keyword_cluster_id'], unique=False)
    op.create_index('ix_planning_topic_tree', 'topic_clusters', ['workspace_id', 'parent_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_topic_clusters_campaign_id'), 'topic_clusters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_topic_clusters_keyword_cluster_id'), 'topic_clusters', ['keyword_cluster_id'], unique=False)
    op.create_index(op.f('ix_topic_clusters_keyword_id'), 'topic_clusters', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_topic_clusters_parent_id'), 'topic_clusters', ['parent_id'], unique=False)
    op.create_index(op.f('ix_topic_clusters_workspace_id'), 'topic_clusters', ['workspace_id'], unique=False)
    op.create_table('content_ideas',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('topic_node_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('primary_keyword_id', sa.Uuid(), nullable=True),
    sa.Column('keyword_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('search_intent', sa.String(length=24), nullable=False),
    sa.Column('journey_stage', sa.String(length=24), nullable=False),
    sa.Column('recommended_cta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('performance_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('duplicate_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_ideas_planning_idea_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_content_ideas_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'topic_node_id'], ['topic_clusters.workspace_id', 'topic_clusters.id'], name=op.f('fk_content_ideas_workspace_id_topic_clusters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_ideas')),
    sa.UniqueConstraint('workspace_id', 'duplicate_key', name='planning_idea_duplicate_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_idea_workspace_id')
    )
    op.create_index(op.f('ix_content_ideas_campaign_id'), 'content_ideas', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_keyword_cluster_id'), 'content_ideas', ['keyword_cluster_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_primary_keyword_id'), 'content_ideas', ['primary_keyword_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_topic_node_id'), 'content_ideas', ['topic_node_id'], unique=False)
    op.create_index(op.f('ix_content_ideas_workspace_id'), 'content_ideas', ['workspace_id'], unique=False)
    op.create_index('ix_planning_idea_campaign', 'content_ideas', ['workspace_id', 'campaign_id'], unique=False)
    op.create_index('ix_planning_idea_workspace_status', 'content_ideas', ['workspace_id', 'status'], unique=False)
    op.create_table('keyword_cluster_members',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('cluster_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('signals_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('similarity_score >= 0 AND similarity_score <= 1', name=op.f('ck_keyword_cluster_members_keyword_cluster_similarity_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'cluster_id'], ['keyword_clusters.workspace_id', 'keyword_clusters.id'], name=op.f('fk_keyword_cluster_members_workspace_id_keyword_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_cluster_members_workspace_id_keywords'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_cluster_members')),
    sa.UniqueConstraint('workspace_id', 'cluster_id', 'keyword_id', name='keyword_cluster_member_identity')
    )
    op.create_index(op.f('ix_keyword_cluster_members_cluster_id'), 'keyword_cluster_members', ['cluster_id'], unique=False)
    op.create_index('ix_keyword_cluster_members_keyword', 'keyword_cluster_members', ['workspace_id', 'keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_cluster_members_keyword_id'), 'keyword_cluster_members', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_cluster_members_workspace_id'), 'keyword_cluster_members', ['workspace_id'], unique=False)
    op.create_table('keyword_metrics',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('provider_connection_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('source_class', sa.String(length=24), nullable=False),
    sa.Column('source_label', sa.String(length=160), nullable=False),
    sa.Column('value_kind', sa.String(length=24), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dimensions_hash', sa.String(length=64), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trend_points_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('demographics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('serp_samples_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('limitations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('adapter_name', sa.String(length=120), nullable=False),
    sa.Column('adapter_version', sa.String(length=32), nullable=False),
    sa.Column('transform_version', sa.String(length=32), nullable=False),
    sa.Column('raw_object_ref', sa.Text(), nullable=True),
    sa.Column('raw_response_hash', sa.String(length=64), nullable=True),
    sa.Column('is_cached', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_keyword_metrics_keyword_metric_confidence')),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['keyword_research_jobs.workspace_id', 'keyword_research_jobs.id'], name=op.f('fk_keyword_metrics_workspace_id_keyword_research_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_metrics_workspace_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'provider_connection_id'], ['keyword_provider_connections.workspace_id', 'keyword_provider_connections.id'], name=op.f('fk_keyword_metrics_workspace_id_keyword_provider_connections'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metrics')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_metric_snapshot_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'keyword_id', 'provider', 'dimensions_hash', 'measured_at', name='keyword_metric_snapshot_identity')
    )
    op.create_index('ix_keyword_metrics_expiry', 'keyword_metrics', ['workspace_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_job_id'), 'keyword_metrics', ['job_id'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_keyword_id'), 'keyword_metrics', ['keyword_id'], unique=False)
    op.create_index('ix_keyword_metrics_latest', 'keyword_metrics', ['workspace_id', 'keyword_id', 'provider', 'measured_at'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_provider_connection_id'), 'keyword_metrics', ['provider_connection_id'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_workspace_id'), 'keyword_metrics', ['workspace_id'], unique=False)
    op.create_table('keyword_provider_calls',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('capability', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('stale_returned', sa.Boolean(), nullable=False),
    sa.Column('quota_remaining_before', sa.Integer(), nullable=True),
    sa.Column('quota_remaining_after', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('retry_after_seconds', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'connection_id'], ['keyword_provider_connections.workspace_id', 'keyword_provider_connections.id'], name=op.f('fk_keyword_provider_calls_workspace_id_keyword_provider_connections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['keyword_research_jobs.workspace_id', 'keyword_research_jobs.id'], name=op.f('fk_keyword_provider_calls_workspace_id_keyword_research_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_provider_calls')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_provider_call_workspace_id')
    )
    op.create_index(op.f('ix_keyword_provider_calls_connection_id'), 'keyword_provider_calls', ['connection_id'], unique=False)
    op.create_index(op.f('ix_keyword_provider_calls_job_id'), 'keyword_provider_calls', ['job_id'], unique=False)
    op.create_index('ix_keyword_provider_calls_started', 'keyword_provider_calls', ['workspace_id', 'started_at'], unique=False)
    op.create_index('ix_keyword_provider_calls_status', 'keyword_provider_calls', ['workspace_id', 'provider', 'state'], unique=False)
    op.create_index(op.f('ix_keyword_provider_calls_workspace_id'), 'keyword_provider_calls', ['workspace_id'], unique=False)
    op.create_table('keyword_research_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('original_text_masked', sa.String(length=1000), nullable=False),
    sa.Column('normalized', sa.String(length=1000), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_of_item_id', sa.Uuid(), nullable=True),
    sa.Column('expansion_reason', sa.String(length=120), nullable=True),
    sa.Column('input_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_status_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_keyword_research_items_research_item_attempt_nonnegative')),
    sa.CheckConstraint('row_no > 0', name=op.f('ck_keyword_research_items_keyword_research_row_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id', 'duplicate_of_item_id'], ['keyword_research_items.workspace_id', 'keyword_research_items.job_id', 'keyword_research_items.id'], name=op.f('fk_keyword_research_items_workspace_id_keyword_research_items'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['keyword_research_jobs.workspace_id', 'keyword_research_jobs.id'], name=op.f('fk_keyword_research_items_workspace_id_keyword_research_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_research_items_workspace_id_keywords'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_research_items')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_research_item_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'id', name='keyword_research_item_job_identity'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'row_no', name='keyword_research_job_row')
    )
    op.create_index('ix_keyword_items_job_state', 'keyword_research_items', ['workspace_id', 'job_id', 'state'], unique=False)
    op.create_index(op.f('ix_keyword_research_items_duplicate_of_item_id'), 'keyword_research_items', ['duplicate_of_item_id'], unique=False)
    op.create_index(op.f('ix_keyword_research_items_job_id'), 'keyword_research_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_keyword_research_items_keyword_id'), 'keyword_research_items', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_research_items_workspace_id'), 'keyword_research_items', ['workspace_id'], unique=False)
    op.create_table('topic_intent_revisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('topic_node_id', sa.Uuid(), nullable=False),
    sa.Column('previous_intent', sa.String(length=24), nullable=False),
    sa.Column('revised_intent', sa.String(length=24), nullable=False),
    sa.Column('previous_journey_stage', sa.String(length=24), nullable=False),
    sa.Column('revised_journey_stage', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('revised_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'topic_node_id'], ['topic_clusters.workspace_id', 'topic_clusters.id'], name=op.f('fk_topic_intent_revisions_workspace_id_topic_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_intent_revisions'))
    )
    op.create_index('ix_topic_intent_revision_node', 'topic_intent_revisions', ['workspace_id', 'topic_node_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_topic_intent_revisions_topic_node_id'), 'topic_intent_revisions', ['topic_node_id'], unique=False)
    op.create_index(op.f('ix_topic_intent_revisions_workspace_id'), 'topic_intent_revisions', ['workspace_id'], unique=False)
    op.create_table('content_briefs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('idea_id', sa.Uuid(), nullable=True),
    sa.Column('topic_node_id', sa.Uuid(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('board_column_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approval_stage_index', sa.Integer(), nullable=False),
    sa.Column('next_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('approval_stage_index >= 0', name=op.f('ck_content_briefs_planning_brief_stage_nonnegative')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_briefs_planning_brief_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'board_column_id'], ['content_board_columns.workspace_id', 'content_board_columns.id'], name=op.f('fk_content_briefs_workspace_id_content_board_columns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_content_briefs_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'idea_id'], ['content_ideas.workspace_id', 'content_ideas.id'], name=op.f('fk_content_briefs_workspace_id_content_ideas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'topic_node_id'], ['topic_clusters.workspace_id', 'topic_clusters.id'], name=op.f('fk_content_briefs_workspace_id_topic_clusters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_briefs')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_brief_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'idea_id', name='planning_brief_workspace_idea')
    )
    op.create_index(op.f('ix_content_briefs_board_column_id'), 'content_briefs', ['board_column_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_campaign_id'), 'content_briefs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_current_version_id'), 'content_briefs', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_idea_id'), 'content_briefs', ['idea_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_next_refresh_at'), 'content_briefs', ['next_refresh_at'], unique=False)
    op.create_index(op.f('ix_content_briefs_topic_node_id'), 'content_briefs', ['topic_node_id'], unique=False)
    op.create_index(op.f('ix_content_briefs_workspace_id'), 'content_briefs', ['workspace_id'], unique=False)
    op.create_index('ix_planning_brief_campaign', 'content_briefs', ['workspace_id', 'campaign_id'], unique=False)
    op.create_index('ix_planning_brief_refresh', 'content_briefs', ['workspace_id', 'next_refresh_at'], unique=False)
    op.create_index('ix_planning_brief_workspace_status', 'content_briefs', ['workspace_id', 'status'], unique=False)
    op.create_table('keyword_score_snapshots',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('metric_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('saturation_score', sa.Float(), nullable=True),
    sa.Column('difficulty_lower', sa.Float(), nullable=True),
    sa.Column('difficulty_upper', sa.Float(), nullable=True),
    sa.Column('difficulty_confidence', sa.Float(), nullable=False),
    sa.Column('commerciality_score', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('score_version', sa.String(length=32), nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_keyword_score_snapshots_keyword_score_confidence')),
    sa.CheckConstraint('coverage >= 0 AND coverage <= 1', name=op.f('ck_keyword_score_snapshots_keyword_score_coverage_range')),
    sa.CheckConstraint('opportunity_score IS NULL OR (opportunity_score >= 0 AND opportunity_score <= 100)', name=op.f('ck_keyword_score_snapshots_keyword_opportunity_score_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_keyword_score_snapshots_workspace_id_keywords'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'metric_snapshot_id'], ['keyword_metrics.workspace_id', 'keyword_metrics.id'], name=op.f('fk_keyword_score_snapshots_workspace_id_keyword_metrics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'profile_id'], ['keyword_score_profiles.workspace_id', 'keyword_score_profiles.id'], name=op.f('fk_keyword_score_snapshots_workspace_id_keyword_score_profiles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_score_snapshots')),
    sa.UniqueConstraint('workspace_id', 'id', name='keyword_score_snapshot_workspace_id')
    )
    op.create_index(op.f('ix_keyword_score_snapshots_keyword_id'), 'keyword_score_snapshots', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_keyword_score_snapshots_metric_snapshot_id'), 'keyword_score_snapshots', ['metric_snapshot_id'], unique=False)
    op.create_index(op.f('ix_keyword_score_snapshots_profile_id'), 'keyword_score_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_keyword_score_snapshots_workspace_id'), 'keyword_score_snapshots', ['workspace_id'], unique=False)
    op.create_index('ix_keyword_scores_latest', 'keyword_score_snapshots', ['workspace_id', 'keyword_id', 'scored_at'], unique=False)
    op.create_index('ix_keyword_scores_rank', 'keyword_score_snapshots', ['workspace_id', 'opportunity_score', 'id'], unique=False)
    op.create_table('content_brief_assignments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assigned_by', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_brief_assignments_planning_assignment_lock_positive')),
    sa.CheckConstraint('sla_seconds IS NULL OR sla_seconds > 0', name=op.f('ck_content_brief_assignments_planning_assignment_sla_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_content_brief_assignments_workspace_id_content_briefs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_brief_assignments')),
    sa.UniqueConstraint('workspace_id', 'brief_id', 'stage', 'user_id', name='planning_assignment_identity')
    )
    op.create_index(op.f('ix_content_brief_assignments_brief_id'), 'content_brief_assignments', ['brief_id'], unique=False)
    op.create_index(op.f('ix_content_brief_assignments_user_id'), 'content_brief_assignments', ['user_id'], unique=False)
    op.create_index(op.f('ix_content_brief_assignments_workspace_id'), 'content_brief_assignments', ['workspace_id'], unique=False)
    op.create_index('ix_planning_assignment_user_due', 'content_brief_assignments', ['workspace_id', 'user_id', 'due_at'], unique=False)
    op.create_table('content_brief_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('template_ref', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('audience_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_intent', sa.String(length=24), nullable=False),
    sa.Column('journey_stage', sa.String(length=24), nullable=False),
    sa.Column('keyword_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_source_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_gap_summary', sa.Text(), nullable=True),
    sa.Column('required_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cta_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('internal_link_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('tone', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_length_min', sa.Integer(), nullable=False),
    sa.Column('target_length_max', sa.Integer(), nullable=False),
    sa.Column('disclosures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('generation_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('target_length_max >= target_length_min', name=op.f('ck_content_brief_versions_planning_brief_target_ordered')),
    sa.CheckConstraint('target_length_min > 0', name=op.f('ck_content_brief_versions_planning_brief_target_min_positive')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_content_brief_versions_planning_brief_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_content_brief_versions_workspace_id_content_briefs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_brief_versions')),
    sa.UniqueConstraint('workspace_id', 'brief_id', 'snapshot_hash', name='planning_brief_snapshot_hash'),
    sa.UniqueConstraint('workspace_id', 'brief_id', 'version_number', name='planning_brief_version_no'),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_brief_version_workspace_id')
    )
    op.create_index(op.f('ix_content_brief_versions_brief_id'), 'content_brief_versions', ['brief_id'], unique=False)
    op.create_index(op.f('ix_content_brief_versions_workspace_id'), 'content_brief_versions', ['workspace_id'], unique=False)
    op.create_index('ix_planning_brief_version_brief', 'content_brief_versions', ['workspace_id', 'brief_id', 'version_number'], unique=False)
    op.create_foreign_key(
        'fk_planning_brief_current_version',
        'content_briefs',
        'content_brief_versions',
        ['workspace_id', 'current_version_id'],
        ['workspace_id', 'id'],
        ondelete='RESTRICT',
        deferrable=True,
        initially='DEFERRED',
    )
    op.create_table('content_calendar_recurrences',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('brief_id', sa.Uuid(), nullable=True),
    sa.Column('frequency', sa.String(length=24), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exception_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at > starts_at', name=op.f('ck_content_calendar_recurrences_recurrence_dates_ordered')),
    sa.CheckConstraint('interval > 0', name=op.f('ck_content_calendar_recurrences_recurrence_interval_positive')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_calendar_recurrences_recurrence_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_content_calendar_recurrences_workspace_id_content_briefs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_content_calendar_recurrences_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_calendar_recurrences')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_recurrence_workspace_id')
    )
    op.create_index(op.f('ix_content_calendar_recurrences_brief_id'), 'content_calendar_recurrences', ['brief_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_recurrences_campaign_id'), 'content_calendar_recurrences', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_recurrences_workspace_id'), 'content_calendar_recurrences', ['workspace_id'], unique=False)
    op.create_index('ix_planning_recurrence_workspace_active', 'content_calendar_recurrences', ['workspace_id', 'active'], unique=False)
    op.create_table('content_brief_decisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('brief_version_id', sa.Uuid(), nullable=False),
    sa.Column('stage_key', sa.String(length=80), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_content_brief_decisions_workspace_id_content_briefs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_version_id'], ['content_brief_versions.workspace_id', 'content_brief_versions.id'], name=op.f('fk_content_brief_decisions_workspace_id_content_brief_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_brief_decisions'))
    )
    op.create_index(op.f('ix_content_brief_decisions_brief_id'), 'content_brief_decisions', ['brief_id'], unique=False)
    op.create_index(op.f('ix_content_brief_decisions_workspace_id'), 'content_brief_decisions', ['workspace_id'], unique=False)
    op.create_index('ix_planning_brief_decision_timeline', 'content_brief_decisions', ['workspace_id', 'brief_id', 'decided_at'], unique=False)
    op.create_table('content_calendar_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('idea_id', sa.Uuid(), nullable=True),
    sa.Column('brief_id', sa.Uuid(), nullable=True),
    sa.Column('brief_version_id', sa.Uuid(), nullable=True),
    sa.Column('recurrence_id', sa.Uuid(), nullable=True),
    sa.Column('title_snapshot', sa.String(length=500), nullable=False),
    sa.Column('brief_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('conflict_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_calendar_items_planning_calendar_entry_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_content_calendar_items_workspace_id_content_briefs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_version_id'], ['content_brief_versions.workspace_id', 'content_brief_versions.id'], name=op.f('fk_content_calendar_items_workspace_id_content_brief_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_content_calendar_items_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'idea_id'], ['content_ideas.workspace_id', 'content_ideas.id'], name=op.f('fk_content_calendar_items_workspace_id_content_ideas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'recurrence_id'], ['content_calendar_recurrences.workspace_id', 'content_calendar_recurrences.id'], name=op.f('fk_content_calendar_items_workspace_id_content_calendar_recurrences'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_calendar_items')),
    sa.UniqueConstraint('workspace_id', 'id', name='planning_calendar_entry_workspace_id')
    )
    op.create_index(op.f('ix_content_calendar_items_brief_id'), 'content_calendar_items', ['brief_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_items_brief_version_id'), 'content_calendar_items', ['brief_version_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_items_campaign_id'), 'content_calendar_items', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_items_idea_id'), 'content_calendar_items', ['idea_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_items_recurrence_id'), 'content_calendar_items', ['recurrence_id'], unique=False)
    op.create_index(op.f('ix_content_calendar_items_workspace_id'), 'content_calendar_items', ['workspace_id'], unique=False)
    op.create_index('ix_planning_calendar_campaign', 'content_calendar_items', ['workspace_id', 'campaign_id', 'scheduled_at'], unique=False)
    op.create_index('ix_planning_calendar_channel_time', 'content_calendar_items', ['workspace_id', 'channel', 'scheduled_at'], unique=False)
    op.create_index('ix_planning_calendar_workspace_time', 'content_calendar_items', ['workspace_id', 'scheduled_at'], unique=False)
    op.add_column('idempotency_records', sa.Column('actor_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('idempotency_identity'), 'idempotency_records', type_='unique')
    op.create_unique_constraint('idempotency_identity', 'idempotency_records', ['workspace_id', 'actor_id', 'namespace', 'operation', 'key'], postgresql_nulls_not_distinct=True)
    op.create_index(op.f('ix_idempotency_records_actor_id'), 'idempotency_records', ['actor_id'], unique=False)

    tenant_tables = (
        'campaigns',
        'campaign_spend_ledger',
        'content_board_columns',
        'content_brief_assignments',
        'content_brief_decisions',
        'content_brief_versions',
        'content_briefs',
        'content_calendar_items',
        'content_calendar_recurrences',
        'content_ideas',
        'keyword_alert_rules',
        'keyword_cluster_members',
        'keyword_clusters',
        'keyword_collection_members',
        'keyword_collections',
        'keyword_content_links',
        'keyword_intent_revisions',
        'keyword_metrics',
        'keyword_provider_calls',
        'keyword_provider_connections',
        'keyword_research_items',
        'keyword_research_jobs',
        'keyword_saved_views',
        'keyword_score_profiles',
        'keyword_score_snapshots',
        'keywords',
        'monthly_plan_proposals',
        'planning_comments',
        'topic_clusters',
        'topic_intent_revisions',
    )
    for table_name in tenant_tables:
        op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY')
        op.execute(
            f'''
            CREATE POLICY {table_name}_workspace_isolation ON {table_name}
            USING (workspace_id = app.current_workspace_id())
            WITH CHECK (workspace_id = app.current_workspace_id())
            '''
        )

    immutable_tables = (
        'campaign_spend_ledger',
        'content_brief_decisions',
        'content_brief_versions',
        'keyword_intent_revisions',
        'keyword_metrics',
        'keyword_score_snapshots',
        'topic_intent_revisions',
    )
    for table_name in immutable_tables:
        op.execute(
            f'''
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
            '''
        )
    op.execute(
        '''
        CREATE TRIGGER keyword_provider_calls_no_delete
        BEFORE DELETE ON keyword_provider_calls
        FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
        '''
    )
    op.execute(
        '''
        CREATE OR REPLACE FUNCTION app.guard_monthly_plan_proposal_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            IF TG_OP = 'DELETE' THEN
                RAISE EXCEPTION 'monthly plan proposal rows cannot be deleted';
            END IF;
            IF OLD.status <> 'PENDING_APPROVAL' THEN
                RAISE EXCEPTION 'decided monthly plan proposal rows are immutable';
            END IF;
            RETURN NEW;
        END;
        $$
        '''
    )
    op.execute(
        '''
        CREATE TRIGGER monthly_plan_proposals_guard
        BEFORE UPDATE OR DELETE ON monthly_plan_proposals
        FOR EACH ROW EXECUTE FUNCTION app.guard_monthly_plan_proposal_mutation()
        '''
    )

    op.execute(
        '''
        WITH additions(role_key, permission_values) AS (
            VALUES
                ('owner', '["keyword:read","keyword:write","keyword:export","planning:read","planning:write","planning:approve","planning:export"]'::jsonb),
                ('admin', '["keyword:read","keyword:write","keyword:export","planning:read","planning:write","planning:approve","planning:export"]'::jsonb),
                ('strategist', '["keyword:read","keyword:write","keyword:export","planning:read","planning:write","planning:approve","planning:export"]'::jsonb),
                ('writer', '["keyword:read","planning:read"]'::jsonb),
                ('reviewer', '["keyword:read","planning:read"]'::jsonb),
                ('approver', '["keyword:read","planning:read","planning:approve"]'::jsonb),
                ('publisher', '["keyword:read","planning:read"]'::jsonb),
                ('analyst', '["keyword:read","planning:read"]'::jsonb),
                ('viewer', '["keyword:read","planning:read"]'::jsonb)
        )
        UPDATE roles
        SET permissions = (
            SELECT jsonb_agg(value ORDER BY value)
            FROM (
                SELECT DISTINCT jsonb_array_elements_text(
                    roles.permissions || additions.permission_values
                ) AS value
            ) AS merged
        )
        FROM additions
        WHERE roles.is_system IS TRUE AND roles.key = additions.role_key
        '''
    )

    worker_tables = (
        'keyword_alert_rules',
        'keyword_cluster_members',
        'keyword_clusters',
        'keyword_metrics',
        'keyword_provider_calls',
        'keyword_provider_connections',
        'keyword_research_items',
        'keyword_research_jobs',
        'keyword_score_profiles',
        'keyword_score_snapshots',
        'keywords',
    )
    op.execute(
        f'''
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_app') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_app;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(tenant_tables)} TO blogops_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_worker') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_worker;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(worker_tables)} TO blogops_worker;
            END IF;
        END
        $$
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        UPDATE roles
        SET permissions = permissions
            - 'keyword:read'
            - 'keyword:write'
            - 'keyword:export'
            - 'planning:read'
            - 'planning:write'
            - 'planning:approve'
            - 'planning:export'
        '''
    )
    op.drop_constraint(
        'fk_planning_brief_current_version', 'content_briefs', type_='foreignkey'
    )
    op.drop_index(op.f('ix_idempotency_records_actor_id'), table_name='idempotency_records')
    op.drop_constraint('idempotency_identity', 'idempotency_records', type_='unique')
    op.create_unique_constraint(op.f('idempotency_identity'), 'idempotency_records', ['namespace', 'operation', 'key'], postgresql_nulls_not_distinct=False)
    op.drop_column('idempotency_records', 'actor_id')
    op.drop_index('ix_planning_calendar_workspace_time', table_name='content_calendar_items')
    op.drop_index('ix_planning_calendar_channel_time', table_name='content_calendar_items')
    op.drop_index('ix_planning_calendar_campaign', table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_workspace_id'), table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_recurrence_id'), table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_idea_id'), table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_campaign_id'), table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_brief_version_id'), table_name='content_calendar_items')
    op.drop_index(op.f('ix_content_calendar_items_brief_id'), table_name='content_calendar_items')
    op.drop_table('content_calendar_items')
    op.drop_index('ix_planning_brief_decision_timeline', table_name='content_brief_decisions')
    op.drop_index(op.f('ix_content_brief_decisions_workspace_id'), table_name='content_brief_decisions')
    op.drop_index(op.f('ix_content_brief_decisions_brief_id'), table_name='content_brief_decisions')
    op.drop_table('content_brief_decisions')
    op.drop_index('ix_planning_recurrence_workspace_active', table_name='content_calendar_recurrences')
    op.drop_index(op.f('ix_content_calendar_recurrences_workspace_id'), table_name='content_calendar_recurrences')
    op.drop_index(op.f('ix_content_calendar_recurrences_campaign_id'), table_name='content_calendar_recurrences')
    op.drop_index(op.f('ix_content_calendar_recurrences_brief_id'), table_name='content_calendar_recurrences')
    op.drop_table('content_calendar_recurrences')
    op.drop_index('ix_planning_brief_version_brief', table_name='content_brief_versions')
    op.drop_index(op.f('ix_content_brief_versions_workspace_id'), table_name='content_brief_versions')
    op.drop_index(op.f('ix_content_brief_versions_brief_id'), table_name='content_brief_versions')
    op.drop_table('content_brief_versions')
    op.drop_index('ix_planning_assignment_user_due', table_name='content_brief_assignments')
    op.drop_index(op.f('ix_content_brief_assignments_workspace_id'), table_name='content_brief_assignments')
    op.drop_index(op.f('ix_content_brief_assignments_user_id'), table_name='content_brief_assignments')
    op.drop_index(op.f('ix_content_brief_assignments_brief_id'), table_name='content_brief_assignments')
    op.drop_table('content_brief_assignments')
    op.drop_index('ix_keyword_scores_rank', table_name='keyword_score_snapshots')
    op.drop_index('ix_keyword_scores_latest', table_name='keyword_score_snapshots')
    op.drop_index(op.f('ix_keyword_score_snapshots_workspace_id'), table_name='keyword_score_snapshots')
    op.drop_index(op.f('ix_keyword_score_snapshots_profile_id'), table_name='keyword_score_snapshots')
    op.drop_index(op.f('ix_keyword_score_snapshots_metric_snapshot_id'), table_name='keyword_score_snapshots')
    op.drop_index(op.f('ix_keyword_score_snapshots_keyword_id'), table_name='keyword_score_snapshots')
    op.drop_table('keyword_score_snapshots')
    op.drop_index('ix_planning_brief_workspace_status', table_name='content_briefs')
    op.drop_index('ix_planning_brief_refresh', table_name='content_briefs')
    op.drop_index('ix_planning_brief_campaign', table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_workspace_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_topic_node_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_next_refresh_at'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_idea_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_current_version_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_campaign_id'), table_name='content_briefs')
    op.drop_index(op.f('ix_content_briefs_board_column_id'), table_name='content_briefs')
    op.drop_table('content_briefs')
    op.drop_index(op.f('ix_topic_intent_revisions_workspace_id'), table_name='topic_intent_revisions')
    op.drop_index(op.f('ix_topic_intent_revisions_topic_node_id'), table_name='topic_intent_revisions')
    op.drop_index('ix_topic_intent_revision_node', table_name='topic_intent_revisions')
    op.drop_table('topic_intent_revisions')
    op.drop_index(op.f('ix_keyword_research_items_workspace_id'), table_name='keyword_research_items')
    op.drop_index(op.f('ix_keyword_research_items_keyword_id'), table_name='keyword_research_items')
    op.drop_index(op.f('ix_keyword_research_items_job_id'), table_name='keyword_research_items')
    op.drop_index(op.f('ix_keyword_research_items_duplicate_of_item_id'), table_name='keyword_research_items')
    op.drop_index('ix_keyword_items_job_state', table_name='keyword_research_items')
    op.drop_table('keyword_research_items')
    op.drop_index(op.f('ix_keyword_provider_calls_workspace_id'), table_name='keyword_provider_calls')
    op.drop_index('ix_keyword_provider_calls_status', table_name='keyword_provider_calls')
    op.drop_index('ix_keyword_provider_calls_started', table_name='keyword_provider_calls')
    op.drop_index(op.f('ix_keyword_provider_calls_job_id'), table_name='keyword_provider_calls')
    op.drop_index(op.f('ix_keyword_provider_calls_connection_id'), table_name='keyword_provider_calls')
    op.drop_table('keyword_provider_calls')
    op.drop_index(op.f('ix_keyword_metrics_workspace_id'), table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_provider_connection_id'), table_name='keyword_metrics')
    op.drop_index('ix_keyword_metrics_latest', table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_keyword_id'), table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_job_id'), table_name='keyword_metrics')
    op.drop_index('ix_keyword_metrics_expiry', table_name='keyword_metrics')
    op.drop_table('keyword_metrics')
    op.drop_index(op.f('ix_keyword_cluster_members_workspace_id'), table_name='keyword_cluster_members')
    op.drop_index(op.f('ix_keyword_cluster_members_keyword_id'), table_name='keyword_cluster_members')
    op.drop_index('ix_keyword_cluster_members_keyword', table_name='keyword_cluster_members')
    op.drop_index(op.f('ix_keyword_cluster_members_cluster_id'), table_name='keyword_cluster_members')
    op.drop_table('keyword_cluster_members')
    op.drop_index('ix_planning_idea_workspace_status', table_name='content_ideas')
    op.drop_index('ix_planning_idea_campaign', table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_workspace_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_topic_node_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_primary_keyword_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_keyword_cluster_id'), table_name='content_ideas')
    op.drop_index(op.f('ix_content_ideas_campaign_id'), table_name='content_ideas')
    op.drop_table('content_ideas')
    op.drop_index(op.f('ix_topic_clusters_workspace_id'), table_name='topic_clusters')
    op.drop_index(op.f('ix_topic_clusters_parent_id'), table_name='topic_clusters')
    op.drop_index(op.f('ix_topic_clusters_keyword_id'), table_name='topic_clusters')
    op.drop_index(op.f('ix_topic_clusters_keyword_cluster_id'), table_name='topic_clusters')
    op.drop_index(op.f('ix_topic_clusters_campaign_id'), table_name='topic_clusters')
    op.drop_index('ix_planning_topic_tree', table_name='topic_clusters')
    op.drop_index('ix_planning_topic_keyword_cluster', table_name='topic_clusters')
    op.drop_table('topic_clusters')
    op.drop_index('ix_monthly_plan_workspace_month', table_name='monthly_plan_proposals')
    op.drop_index(op.f('ix_monthly_plan_proposals_workspace_id'), table_name='monthly_plan_proposals')
    op.drop_index(op.f('ix_monthly_plan_proposals_campaign_id'), table_name='monthly_plan_proposals')
    op.drop_table('monthly_plan_proposals')
    op.drop_index(op.f('ix_keyword_research_jobs_workspace_id'), table_name='keyword_research_jobs')
    op.drop_index(op.f('ix_keyword_research_jobs_score_profile_id'), table_name='keyword_research_jobs')
    op.drop_index(op.f('ix_keyword_research_jobs_requested_by'), table_name='keyword_research_jobs')
    op.drop_index('ix_keyword_jobs_workspace_state', table_name='keyword_research_jobs')
    op.drop_table('keyword_research_jobs')
    op.drop_index(op.f('ix_keyword_intent_revisions_workspace_id'), table_name='keyword_intent_revisions')
    op.drop_index(op.f('ix_keyword_intent_revisions_keyword_id'), table_name='keyword_intent_revisions')
    op.drop_index('ix_keyword_intent_history', table_name='keyword_intent_revisions')
    op.drop_table('keyword_intent_revisions')
    op.drop_index(op.f('ix_keyword_content_links_workspace_id'), table_name='keyword_content_links')
    op.drop_index('ix_keyword_content_links_target', table_name='keyword_content_links')
    op.drop_index(op.f('ix_keyword_content_links_keyword_id'), table_name='keyword_content_links')
    op.drop_table('keyword_content_links')
    op.drop_index(op.f('ix_keyword_collection_members_workspace_id'), table_name='keyword_collection_members')
    op.drop_index(op.f('ix_keyword_collection_members_keyword_id'), table_name='keyword_collection_members')
    op.drop_index(op.f('ix_keyword_collection_members_collection_id'), table_name='keyword_collection_members')
    op.drop_table('keyword_collection_members')
    op.drop_index('ix_keyword_clusters_workspace_kind', table_name='keyword_clusters')
    op.drop_index(op.f('ix_keyword_clusters_workspace_id'), table_name='keyword_clusters')
    op.drop_index(op.f('ix_keyword_clusters_primary_keyword_id'), table_name='keyword_clusters')
    op.drop_table('keyword_clusters')
    op.drop_index('ix_keyword_alerts_due', table_name='keyword_alert_rules')
    op.drop_index(op.f('ix_keyword_alert_rules_workspace_id'), table_name='keyword_alert_rules')
    op.drop_index(op.f('ix_keyword_alert_rules_owner_id'), table_name='keyword_alert_rules')
    op.drop_index(op.f('ix_keyword_alert_rules_keyword_id'), table_name='keyword_alert_rules')
    op.drop_table('keyword_alert_rules')
    op.drop_index('ix_campaign_spend_workspace_campaign', table_name='campaign_spend_ledger')
    op.drop_index(op.f('ix_campaign_spend_ledger_workspace_id'), table_name='campaign_spend_ledger')
    op.drop_index(op.f('ix_campaign_spend_ledger_recorded_by'), table_name='campaign_spend_ledger')
    op.drop_index(op.f('ix_campaign_spend_ledger_campaign_id'), table_name='campaign_spend_ledger')
    op.drop_table('campaign_spend_ledger')
    op.drop_index(op.f('ix_planning_comments_workspace_id'), table_name='planning_comments')
    op.drop_index(op.f('ix_planning_comments_target_id'), table_name='planning_comments')
    op.drop_index('ix_planning_comment_target', table_name='planning_comments')
    op.drop_table('planning_comments')
    op.drop_index('ix_keywords_workspace_normalized', table_name='keywords')
    op.drop_index('ix_keywords_workspace_intent', table_name='keywords')
    op.drop_index(op.f('ix_keywords_workspace_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_created_by'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_index(op.f('ix_keyword_score_profiles_workspace_id'), table_name='keyword_score_profiles')
    op.drop_index('ix_keyword_score_profiles_active', table_name='keyword_score_profiles')
    op.drop_table('keyword_score_profiles')
    op.drop_index(op.f('ix_keyword_saved_views_workspace_id'), table_name='keyword_saved_views')
    op.drop_index(op.f('ix_keyword_saved_views_owner_id'), table_name='keyword_saved_views')
    op.drop_table('keyword_saved_views')
    op.drop_index('ix_keyword_provider_workspace_state', table_name='keyword_provider_connections')
    op.drop_index('ix_keyword_provider_quota_reset', table_name='keyword_provider_connections')
    op.drop_index(op.f('ix_keyword_provider_connections_workspace_id'), table_name='keyword_provider_connections')
    op.drop_table('keyword_provider_connections')
    op.drop_index(op.f('ix_keyword_collections_workspace_id'), table_name='keyword_collections')
    op.drop_index(op.f('ix_keyword_collections_campaign_opaque_ref'), table_name='keyword_collections')
    op.drop_table('keyword_collections')
    op.drop_index(op.f('ix_content_board_columns_workspace_id'), table_name='content_board_columns')
    op.drop_table('content_board_columns')
    op.drop_index('ix_planning_campaign_workspace_status', table_name='campaigns')
    op.drop_index('ix_planning_campaign_workspace_dates', table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_workspace_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_by'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_brand_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.execute('DROP FUNCTION IF EXISTS app.guard_monthly_plan_proposal_mutation()')
    # ### end Alembic commands ###
