"""research generation

Revision ID: 4fd7a4ed3cfb
Revises: e05c23a4bbb7
Create Date: 2026-08-23 13:32:17.606313
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4fd7a4ed3cfb'
down_revision: str | None = 'e05c23a4bbb7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_catalog',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('quality_grades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_limit', sa.Integer(), nullable=True),
    sa.Column('parameter_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('retirement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replacement_entry_id', sa.Uuid(), nullable=True),
    sa.Column('customer_managed_key', sa.Boolean(), nullable=False),
    sa.Column('secret_ref', sa.String(length=512), nullable=True),
    sa.Column('configured_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('context_limit IS NULL OR context_limit > 0', name=op.f('ck_model_catalog_model_context_limit_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'replacement_entry_id'], ['model_catalog.workspace_id', 'model_catalog.id'], name=op.f('fk_model_catalog_workspace_id_model_catalog'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_catalog')),
    sa.UniqueConstraint('workspace_id', 'id', name='model_catalog_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'model', 'model_version', 'region', name='model_catalog_identity')
    )
    op.create_index(op.f('ix_model_catalog_replacement_entry_id'), 'model_catalog', ['replacement_entry_id'], unique=False)
    op.create_index('ix_model_catalog_status', 'model_catalog', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_model_catalog_workspace_id'), 'model_catalog', ['workspace_id'], unique=False)
    op.create_table('prompts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('workspace_id', 'id', name='prompt_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'key', name='prompt_workspace_key')
    )
    op.create_index(op.f('ix_prompts_current_version_id'), 'prompts', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_prompts_workspace_id'), 'prompts', ['workspace_id'], unique=False)
    op.create_table('research_cache_entries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_hash', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_cache_entries')),
    sa.UniqueConstraint('workspace_id', 'id', name='research_cache_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'request_hash', 'policy_hash', name='research_cache_identity')
    )
    op.create_index(op.f('ix_research_cache_entries_workspace_id'), 'research_cache_entries', ['workspace_id'], unique=False)
    op.create_index('ix_research_cache_expiry', 'research_cache_entries', ['workspace_id', 'expires_at'], unique=False)
    op.create_table('templates',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=24), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates')),
    sa.UniqueConstraint('workspace_id', 'id', name='template_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'scope', 'owner_id', 'name', name='template_name')
    )
    op.create_index(op.f('ix_templates_current_version_id'), 'templates', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_templates_owner_id'), 'templates', ['owner_id'], unique=False)
    op.create_index(op.f('ix_templates_workspace_id'), 'templates', ['workspace_id'], unique=False)
    op.create_index('ix_templates_workspace_type', 'templates', ['workspace_id', 'content_type'], unique=False)
    op.create_table('model_pricing_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('model_entry_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_model_pricing_versions_model_pricing_currency_length')),
    sa.ForeignKeyConstraint(['workspace_id', 'model_entry_id'], ['model_catalog.workspace_id', 'model_catalog.id'], name=op.f('fk_model_pricing_versions_workspace_id_model_catalog'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_pricing_versions')),
    sa.UniqueConstraint('workspace_id', 'id', name='model_pricing_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'model_entry_id', 'effective_at', name='model_pricing_effective')
    )
    op.create_index(op.f('ix_model_pricing_versions_model_entry_id'), 'model_pricing_versions', ['model_entry_id'], unique=False)
    op.create_index(op.f('ix_model_pricing_versions_workspace_id'), 'model_pricing_versions', ['workspace_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('system_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('task_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_policy_version', sa.String(length=80), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_prompt_versions_prompt_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'prompt_id'], ['prompts.workspace_id', 'prompts.id'], name=op.f('fk_prompt_versions_workspace_id_prompts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('workspace_id', 'id', name='prompt_version_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'prompt_id', 'version', name='prompt_version_no')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_id'), 'prompt_versions', ['prompt_id'], unique=False)
    op.create_index('ix_prompt_versions_status', 'prompt_versions', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_prompt_versions_workspace_id'), 'prompt_versions', ['workspace_id'], unique=False)
    op.create_table('template_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('structure_blocks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_template_versions_template_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'prompt_version_id'], ['prompt_versions.workspace_id', 'prompt_versions.id'], name=op.f('fk_template_versions_workspace_id_prompt_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'template_id'], ['templates.workspace_id', 'templates.id'], name=op.f('fk_template_versions_workspace_id_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_versions')),
    sa.UniqueConstraint('workspace_id', 'id', name='template_version_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'template_id', 'version', name='template_version_no')
    )
    op.create_index(op.f('ix_template_versions_prompt_version_id'), 'template_versions', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_template_versions_template_id'), 'template_versions', ['template_id'], unique=False)
    op.create_index(op.f('ix_template_versions_workspace_id'), 'template_versions', ['workspace_id'], unique=False)
    op.create_unique_constraint('brand_workspace_id', 'brands', ['workspace_id', 'id'])
    op.create_table('contents',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('folder_path', sa.String(length=1000), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_hold', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_contents_content_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'brand_id'], ['brands.workspace_id', 'brands.id'], name=op.f('fk_contents_workspace_id_brands'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_contents_workspace_id_content_briefs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contents')),
    sa.UniqueConstraint('workspace_id', 'id', name='content_workspace_id')
    )
    op.create_index(op.f('ix_contents_brand_id'), 'contents', ['brand_id'], unique=False)
    op.create_index(op.f('ix_contents_brief_id'), 'contents', ['brief_id'], unique=False)
    op.create_index(op.f('ix_contents_created_by'), 'contents', ['created_by'], unique=False)
    op.create_index(op.f('ix_contents_current_version_id'), 'contents', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_contents_deleted_at'), 'contents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contents_expires_at'), 'contents', ['expires_at'], unique=False)
    op.create_index('ix_contents_workspace_author', 'contents', ['workspace_id', 'created_by'], unique=False)
    op.create_index(op.f('ix_contents_workspace_id'), 'contents', ['workspace_id'], unique=False)
    op.create_index('ix_contents_workspace_state', 'contents', ['workspace_id', 'state', 'updated_at'], unique=False)
    op.create_index('ix_contents_workspace_type', 'contents', ['workspace_id', 'content_type'], unique=False)
    op.create_table('content_edit_leases',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('holder_id', sa.Uuid(), nullable=False),
    sa.Column('lease_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_edit_leases_workspace_id_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_edit_leases')),
    sa.UniqueConstraint('workspace_id', 'content_id', name='content_edit_active_lease'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_lease_workspace_id')
    )
    op.create_index('ix_content_edit_lease_expiry', 'content_edit_leases', ['workspace_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_content_edit_leases_content_id'), 'content_edit_leases', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_edit_leases_workspace_id'), 'content_edit_leases', ['workspace_id'], unique=False)
    op.create_table('content_library_markers',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('marker', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_library_markers_workspace_id_contents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_library_markers')),
    sa.UniqueConstraint('workspace_id', 'content_id', 'actor_id', 'marker', name='content_marker_identity'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_marker_workspace_id')
    )
    op.create_index(op.f('ix_content_library_markers_actor_id'), 'content_library_markers', ['actor_id'], unique=False)
    op.create_index(op.f('ix_content_library_markers_content_id'), 'content_library_markers', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_library_markers_workspace_id'), 'content_library_markers', ['workspace_id'], unique=False)
    op.create_table('generation_input_snapshots',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('brief_id', sa.Uuid(), nullable=False),
    sa.Column('brief_version_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=False),
    sa.Column('model_entry_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('brief_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('product_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('persona_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_version_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('keyword_metric_snapshots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pricing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type_input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variables_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('safety_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('contract_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_id'], ['content_briefs.workspace_id', 'content_briefs.id'], name=op.f('fk_generation_input_snapshots_workspace_id_content_briefs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_version_id'], ['content_brief_versions.workspace_id', 'content_brief_versions.id'], name=op.f('fk_generation_input_snapshots_workspace_id_content_brief_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'model_entry_id'], ['model_catalog.workspace_id', 'model_catalog.id'], name=op.f('fk_generation_input_snapshots_workspace_id_model_catalog'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'pricing_version_id'], ['model_pricing_versions.workspace_id', 'model_pricing_versions.id'], name=op.f('fk_generation_input_snapshots_workspace_id_model_pricing_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'prompt_version_id'], ['prompt_versions.workspace_id', 'prompt_versions.id'], name=op.f('fk_generation_input_snapshots_workspace_id_prompt_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'template_version_id'], ['template_versions.workspace_id', 'template_versions.id'], name=op.f('fk_generation_input_snapshots_workspace_id_template_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_input_snapshots')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_snapshot_workspace_id')
    )
    op.create_index(op.f('ix_generation_input_snapshots_brief_id'), 'generation_input_snapshots', ['brief_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_brief_version_id'), 'generation_input_snapshots', ['brief_version_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_model_entry_id'), 'generation_input_snapshots', ['model_entry_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_pricing_version_id'), 'generation_input_snapshots', ['pricing_version_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_prompt_version_id'), 'generation_input_snapshots', ['prompt_version_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_template_version_id'), 'generation_input_snapshots', ['template_version_id'], unique=False)
    op.create_index(op.f('ix_generation_input_snapshots_workspace_id'), 'generation_input_snapshots', ['workspace_id'], unique=False)
    op.create_index('ix_generation_snapshot_brief', 'generation_input_snapshots', ['workspace_id', 'brief_version_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('restored_from_version_id', sa.Uuid(), nullable=True),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('generation_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('change_kind', sa.String(length=24), nullable=False),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_content_versions_content_version_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_versions_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'generation_snapshot_id'], ['generation_input_snapshots.workspace_id', 'generation_input_snapshots.id'], name=op.f('fk_content_versions_workspace_id_generation_input_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name='fk_content_version_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'restored_from_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name='fk_content_version_restored', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions')),
    sa.UniqueConstraint('workspace_id', 'content_id', 'version_number', name='content_version_no'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_version_workspace_id')
    )
    op.create_index('ix_content_versions_content', 'content_versions', ['workspace_id', 'content_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_content_versions_content_id'), 'content_versions', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_versions_generation_job_id'), 'content_versions', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_content_versions_generation_snapshot_id'), 'content_versions', ['generation_snapshot_id'], unique=False)
    op.create_index(op.f('ix_content_versions_parent_version_id'), 'content_versions', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_content_versions_restored_from_version_id'), 'content_versions', ['restored_from_version_id'], unique=False)
    op.create_index(op.f('ix_content_versions_workspace_id'), 'content_versions', ['workspace_id'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('input_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('quality', sa.String(length=24), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('budget_reservation_ref', sa.String(length=512), nullable=False),
    sa.Column('entitlement_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('estimate_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('cancel_requested_by', sa.Uuid(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name=op.f('ck_generation_jobs_generation_actual_cost_nonnegative')),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_generation_jobs_generation_job_attempt_nonnegative')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_generation_jobs_generation_estimated_cost_nonnegative')),
    sa.CheckConstraint('max_attempts IS NULL OR max_attempts > 0', name=op.f('ck_generation_jobs_generation_job_max_attempts_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_generation_jobs_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'input_snapshot_id'], ['generation_input_snapshots.workspace_id', 'generation_input_snapshots.id'], name=op.f('fk_generation_jobs_workspace_id_generation_input_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_jobs')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_job_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'requested_by', 'operation', 'idempotency_key', name='generation_job_idempotency')
    )
    op.create_index(op.f('ix_generation_jobs_content_id'), 'generation_jobs', ['content_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_input_snapshot_id'), 'generation_jobs', ['input_snapshot_id'], unique=False)
    op.create_index(op.f('ix_generation_jobs_requested_by'), 'generation_jobs', ['requested_by'], unique=False)
    op.create_index('ix_generation_jobs_state', 'generation_jobs', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_generation_jobs_workspace_id'), 'generation_jobs', ['workspace_id'], unique=False)
    op.create_table('generation_snapshot_keyword_metrics',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('keyword_id', sa.Uuid(), nullable=False),
    sa.Column('metric_snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'keyword_id'], ['keywords.workspace_id', 'keywords.id'], name=op.f('fk_generation_snapshot_keyword_metrics_workspace_id_keywords'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'metric_snapshot_id'], ['keyword_metrics.workspace_id', 'keyword_metrics.id'], name=op.f('fk_generation_snapshot_keyword_metrics_workspace_id_keyword_metrics'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'snapshot_id'], ['generation_input_snapshots.workspace_id', 'generation_input_snapshots.id'], name=op.f('fk_generation_snapshot_keyword_metrics_workspace_id_generation_input_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_snapshot_keyword_metrics')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_metric_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'snapshot_id', 'metric_snapshot_id', name='generation_metric_once')
    )
    op.create_index(op.f('ix_generation_snapshot_keyword_metrics_metric_snapshot_id'), 'generation_snapshot_keyword_metrics', ['metric_snapshot_id'], unique=False)
    op.create_index(op.f('ix_generation_snapshot_keyword_metrics_snapshot_id'), 'generation_snapshot_keyword_metrics', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_generation_snapshot_keyword_metrics_workspace_id'), 'generation_snapshot_keyword_metrics', ['workspace_id'], unique=False)
    op.create_table('generation_snapshot_sources',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('source_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'snapshot_id'], ['generation_input_snapshots.workspace_id', 'generation_input_snapshots.id'], name=op.f('fk_generation_snapshot_sources_workspace_id_generation_input_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_id'], ['knowledge_sources.workspace_id', 'knowledge_sources.id'], name=op.f('fk_generation_snapshot_sources_workspace_id_knowledge_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_version_id'], ['source_versions.workspace_id', 'source_versions.id'], name=op.f('fk_generation_snapshot_sources_workspace_id_source_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_snapshot_sources')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_source_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'snapshot_id', 'source_version_id', name='generation_source_once')
    )
    op.create_index(op.f('ix_generation_snapshot_sources_snapshot_id'), 'generation_snapshot_sources', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_generation_snapshot_sources_source_version_id'), 'generation_snapshot_sources', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_generation_snapshot_sources_workspace_id'), 'generation_snapshot_sources', ['workspace_id'], unique=False)
    op.create_table('content_blocks',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('block_key', sa.Uuid(), nullable=False),
    sa.Column('block_type', sa.String(length=40), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('locked_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_anchors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('position >= 0', name=op.f('ck_content_blocks_content_block_position_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_content_blocks_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_blocks')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'block_key', name='content_block_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_block_workspace_id')
    )
    op.create_index(op.f('ix_content_blocks_content_version_id'), 'content_blocks', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_blocks_workspace_id'), 'content_blocks', ['workspace_id'], unique=False)
    op.create_table('content_collaboration_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('client_operation_id', sa.String(length=255), nullable=False),
    sa.Column('event_kind', sa.String(length=40), nullable=False),
    sa.Column('block_key', sa.Uuid(), nullable=True),
    sa.Column('text_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_collaboration_events_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_content_collaboration_events_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_collaboration_events')),
    sa.UniqueConstraint('workspace_id', 'actor_id', 'client_operation_id', name='content_event_client_op'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_event_workspace_id')
    )
    op.create_index(op.f('ix_content_collaboration_events_content_id'), 'content_collaboration_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_collaboration_events_content_version_id'), 'content_collaboration_events', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_collaboration_events_workspace_id'), 'content_collaboration_events', ['workspace_id'], unique=False)
    op.create_index('ix_content_events_timeline', 'content_collaboration_events', ['workspace_id', 'content_id', 'created_at'], unique=False)
    op.create_table('content_comments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('block_key', sa.Uuid(), nullable=True),
    sa.Column('text_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('mentions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_comments_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_content_comments_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_comment_id'], ['content_comments.workspace_id', 'content_comments.id'], name=op.f('fk_content_comments_workspace_id_content_comments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_comments')),
    sa.UniqueConstraint('workspace_id', 'id', name='content_comment_workspace_id')
    )
    op.create_index(op.f('ix_content_comments_content_id'), 'content_comments', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_comments_content_version_id'), 'content_comments', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_comments_parent_comment_id'), 'content_comments', ['parent_comment_id'], unique=False)
    op.create_index('ix_content_comments_target', 'content_comments', ['workspace_id', 'content_id', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_content_comments_workspace_id'), 'content_comments', ['workspace_id'], unique=False)
    op.create_table('content_feedback',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_feedback_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_content_feedback_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'generation_job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_content_feedback_workspace_id_generation_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_feedback')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'actor_id', 'kind', name='content_feedback_once'),
    sa.UniqueConstraint('workspace_id', 'id', name='content_feedback_workspace_id')
    )
    op.create_index(op.f('ix_content_feedback_content_id'), 'content_feedback', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_feedback_content_version_id'), 'content_feedback', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_feedback_generation_job_id'), 'content_feedback', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_content_feedback_workspace_id'), 'content_feedback', ['workspace_id'], unique=False)
    op.create_table('content_lineage',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('parent_content_version_id', sa.Uuid(), nullable=False),
    sa.Column('child_content_version_id', sa.Uuid(), nullable=False),
    sa.Column('lineage_kind', sa.String(length=24), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'child_content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name='fk_content_lineage_child', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name='fk_content_lineage_parent', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_lineage')),
    sa.UniqueConstraint('workspace_id', 'id', name='content_lineage_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'parent_content_version_id', 'child_content_version_id', 'lineage_kind', name='content_lineage_identity')
    )
    op.create_index(op.f('ix_content_lineage_child_content_version_id'), 'content_lineage', ['child_content_version_id'], unique=False)
    op.create_index(op.f('ix_content_lineage_parent_content_version_id'), 'content_lineage', ['parent_content_version_id'], unique=False)
    op.create_index(op.f('ix_content_lineage_workspace_id'), 'content_lineage', ['workspace_id'], unique=False)
    op.create_table('generation_job_commands',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('command_kind', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_generation_job_commands_workspace_id_generation_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_job_commands')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_command_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'actor_id', 'command_kind', 'idempotency_key', name='generation_command_idempotency')
    )
    op.create_index(op.f('ix_generation_job_commands_job_id'), 'generation_job_commands', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_job_commands_workspace_id'), 'generation_job_commands', ['workspace_id'], unique=False)
    op.create_table('generation_job_steps',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('step_key', sa.String(length=240), nullable=False),
    sa.Column('step_kind', sa.String(length=48), nullable=False),
    sa.Column('section_key', sa.String(length=160), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('partial_content_version_id', sa.Uuid(), nullable=True),
    sa.Column('output_ref', sa.String(length=1000), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_generation_job_steps_generation_step_attempt_nonnegative')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_generation_job_steps_generation_step_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_generation_job_steps_workspace_id_generation_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generation_job_steps')),
    sa.UniqueConstraint('workspace_id', 'id', name='generation_step_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'id', name='generation_step_job_identity'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'step_key', 'input_snapshot_hash', name='generation_step_idempotency')
    )
    op.create_index(op.f('ix_generation_job_steps_job_id'), 'generation_job_steps', ['job_id'], unique=False)
    op.create_index(op.f('ix_generation_job_steps_partial_content_version_id'), 'generation_job_steps', ['partial_content_version_id'], unique=False)
    op.create_index(op.f('ix_generation_job_steps_workspace_id'), 'generation_job_steps', ['workspace_id'], unique=False)
    op.create_index('ix_generation_steps_state', 'generation_job_steps', ['workspace_id', 'job_id', 'state', 'ordinal'], unique=False)
    op.create_table('research_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('brief_version_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('search_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('search_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('source_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_source_set_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'brief_version_id'], ['content_brief_versions.workspace_id', 'content_brief_versions.id'], name=op.f('fk_research_runs_workspace_id_content_brief_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_research_runs_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'generation_job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_research_runs_workspace_id_generation_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_runs')),
    sa.UniqueConstraint('workspace_id', 'id', name='research_run_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'requested_by', 'operation', 'idempotency_key', name='research_run_idempotency')
    )
    op.create_index(op.f('ix_research_runs_brief_version_id'), 'research_runs', ['brief_version_id'], unique=False)
    op.create_index('ix_research_runs_content', 'research_runs', ['workspace_id', 'content_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_content_id'), 'research_runs', ['content_id'], unique=False)
    op.create_index(op.f('ix_research_runs_generation_job_id'), 'research_runs', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_research_runs_requested_by'), 'research_runs', ['requested_by'], unique=False)
    op.create_index('ix_research_runs_state', 'research_runs', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_research_runs_workspace_id'), 'research_runs', ['workspace_id'], unique=False)
    op.create_table('claims',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=True),
    sa.Column('claim_key', sa.String(length=160), nullable=False),
    sa.Column('block_key', sa.Uuid(), nullable=True),
    sa.Column('text_range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('temporal_validity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_policy_version', sa.String(length=80), nullable=False),
    sa.Column('claim_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_claims_claim_confidence_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_claims_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'research_run_id'], ['research_runs.workspace_id', 'research_runs.id'], name=op.f('fk_claims_workspace_id_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'claim_key', name='claim_version_key'),
    sa.UniqueConstraint('workspace_id', 'id', name='claim_workspace_id')
    )
    op.create_index(op.f('ix_claims_block_key'), 'claims', ['block_key'], unique=False)
    op.create_index(op.f('ix_claims_content_version_id'), 'claims', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_claims_research_run_id'), 'claims', ['research_run_id'], unique=False)
    op.create_index('ix_claims_status', 'claims', ['workspace_id', 'content_version_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_workspace_id'), 'claims', ['workspace_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('model_entry_id', sa.Uuid(), nullable=False),
    sa.Column('pricing_version_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_version_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('routing_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fallback_from', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('response_object_ref', sa.String(length=1000), nullable=True),
    sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_transmission_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_model_runs_model_run_cost_nonnegative')),
    sa.CheckConstraint('input_tokens >= 0', name=op.f('ck_model_runs_model_run_input_tokens_nonnegative')),
    sa.CheckConstraint('output_tokens >= 0', name=op.f('ck_model_runs_model_run_output_tokens_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id', 'step_id'], ['generation_job_steps.workspace_id', 'generation_job_steps.job_id', 'generation_job_steps.id'], name=op.f('fk_model_runs_workspace_id_generation_job_steps'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'model_entry_id'], ['model_catalog.workspace_id', 'model_catalog.id'], name=op.f('fk_model_runs_workspace_id_model_catalog'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'pricing_version_id'], ['model_pricing_versions.workspace_id', 'model_pricing_versions.id'], name=op.f('fk_model_runs_workspace_id_model_pricing_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'prompt_version_id'], ['prompt_versions.workspace_id', 'prompt_versions.id'], name=op.f('fk_model_runs_workspace_id_prompt_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs')),
    sa.UniqueConstraint('workspace_id', 'id', name='model_run_workspace_id')
    )
    op.create_index('ix_model_runs_job', 'model_runs', ['workspace_id', 'job_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_model_runs_job_id'), 'model_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_model_runs_step_id'), 'model_runs', ['step_id'], unique=False)
    op.create_index(op.f('ix_model_runs_workspace_id'), 'model_runs', ['workspace_id'], unique=False)
    op.create_table('research_conflicts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('artifact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('positions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conflict_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'research_run_id'], ['research_runs.workspace_id', 'research_runs.id'], name=op.f('fk_research_conflicts_workspace_id_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_conflicts')),
    sa.UniqueConstraint('workspace_id', 'id', name='research_conflict_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'research_run_id', 'conflict_hash', name='research_conflict_hash')
    )
    op.create_index(op.f('ix_research_conflicts_research_run_id'), 'research_conflicts', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_conflicts_workspace_id'), 'research_conflicts', ['workspace_id'], unique=False)
    op.create_table('research_queries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('provider_version', sa.String(length=80), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'research_run_id'], ['research_runs.workspace_id', 'research_runs.id'], name=op.f('fk_research_queries_workspace_id_research_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_queries')),
    sa.UniqueConstraint('workspace_id', 'id', name='research_query_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'research_run_id', 'request_hash', name='research_query_request')
    )
    op.create_index(op.f('ix_research_queries_research_run_id'), 'research_queries', ['research_run_id'], unique=False)
    op.create_index('ix_research_queries_run', 'research_queries', ['workspace_id', 'research_run_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_research_queries_workspace_id'), 'research_queries', ['workspace_id'], unique=False)
    op.create_table('claim_decisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('replacement_claim_id', sa.Uuid(), nullable=True),
    sa.Column('decision', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'claim_id'], ['claims.workspace_id', 'claims.id'], name='fk_claim_decision_claim', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'replacement_claim_id'], ['claims.workspace_id', 'claims.id'], name='fk_claim_decision_replacement', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_decisions')),
    sa.UniqueConstraint('workspace_id', 'id', name='claim_decision_workspace_id')
    )
    op.create_index('ix_claim_decisions_claim', 'claim_decisions', ['workspace_id', 'claim_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_claim_decisions_claim_id'), 'claim_decisions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_decisions_replacement_claim_id'), 'claim_decisions', ['replacement_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_decisions_workspace_id'), 'claim_decisions', ['workspace_id'], unique=False)
    op.create_table('research_artifacts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('research_run_id', sa.Uuid(), nullable=False),
    sa.Column('query_id', sa.Uuid(), nullable=True),
    sa.Column('source_version_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_kind', sa.String(length=40), nullable=False),
    sa.Column('selection', sa.String(length=24), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('grade', sa.String(length=1), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('canonical_uri', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('freshness_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights_status', sa.String(length=32), nullable=False),
    sa.Column('use_scope', sa.String(length=32), nullable=False),
    sa.Column('quote_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('excerpt_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_object_ref', sa.String(length=1000), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('provider_version', sa.String(length=80), nullable=True),
    sa.Column('artifact_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('freshness_score IS NULL OR (freshness_score >= 0 AND freshness_score <= 1)', name=op.f('ck_research_artifacts_research_artifact_freshness_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'query_id'], ['research_queries.workspace_id', 'research_queries.id'], name=op.f('fk_research_artifacts_workspace_id_research_queries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'research_run_id'], ['research_runs.workspace_id', 'research_runs.id'], name=op.f('fk_research_artifacts_workspace_id_research_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_version_id'], ['source_versions.workspace_id', 'source_versions.id'], name=op.f('fk_research_artifacts_workspace_id_source_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_artifacts')),
    sa.UniqueConstraint('workspace_id', 'id', name='research_artifact_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'research_run_id', 'artifact_hash', name='research_artifact_hash')
    )
    op.create_index('ix_research_artifacts_grade', 'research_artifacts', ['workspace_id', 'research_run_id', 'grade'], unique=False)
    op.create_index(op.f('ix_research_artifacts_query_id'), 'research_artifacts', ['query_id'], unique=False)
    op.create_index(op.f('ix_research_artifacts_research_run_id'), 'research_artifacts', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_research_artifacts_source_version_id'), 'research_artifacts', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_research_artifacts_workspace_id'), 'research_artifacts', ['workspace_id'], unique=False)
    op.create_table('citations',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('research_artifact_id', sa.Uuid(), nullable=True),
    sa.Column('source_version_id', sa.Uuid(), nullable=True),
    sa.Column('canonical_uri', sa.Text(), nullable=True),
    sa.Column('locator', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('excerpt_hash', sa.String(length=64), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('style', sa.String(length=24), nullable=False),
    sa.Column('quote_word_count', sa.Integer(), nullable=False),
    sa.Column('quote_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('quote_word_count >= 0', name=op.f('ck_citations_citation_quote_words_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'claim_id'], ['claims.workspace_id', 'claims.id'], name=op.f('fk_citations_workspace_id_claims'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'research_artifact_id'], ['research_artifacts.workspace_id', 'research_artifacts.id'], name=op.f('fk_citations_workspace_id_research_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_version_id'], ['source_versions.workspace_id', 'source_versions.id'], name=op.f('fk_citations_workspace_id_source_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations')),
    sa.UniqueConstraint('workspace_id', 'claim_id', 'evidence_hash', name='citation_claim_evidence'),
    sa.UniqueConstraint('workspace_id', 'id', name='citation_workspace_id')
    )
    op.create_index('ix_citations_claim', 'citations', ['workspace_id', 'claim_id'], unique=False)
    op.create_index(op.f('ix_citations_claim_id'), 'citations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_citations_research_artifact_id'), 'citations', ['research_artifact_id'], unique=False)
    op.create_index(op.f('ix_citations_source_version_id'), 'citations', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_citations_workspace_id'), 'citations', ['workspace_id'], unique=False)
    op.create_foreign_key(
        'fk_prompt_current_version', 'prompts', 'prompt_versions',
        ['workspace_id', 'current_version_id'], ['workspace_id', 'id'],
        ondelete='RESTRICT', deferrable=True, initially='DEFERRED'
    )
    op.create_foreign_key(
        'fk_template_current_version', 'templates', 'template_versions',
        ['workspace_id', 'current_version_id'], ['workspace_id', 'id'],
        ondelete='RESTRICT', deferrable=True, initially='DEFERRED'
    )
    op.create_foreign_key(
        'fk_content_current_version', 'contents', 'content_versions',
        ['workspace_id', 'current_version_id'], ['workspace_id', 'id'],
        ondelete='RESTRICT', deferrable=True, initially='DEFERRED'
    )
    op.create_foreign_key(
        'fk_content_version_generation_job', 'content_versions', 'generation_jobs',
        ['workspace_id', 'generation_job_id'], ['workspace_id', 'id'],
        ondelete='RESTRICT'
    )
    op.create_foreign_key(
        'fk_generation_step_partial_version', 'generation_job_steps', 'content_versions',
        ['workspace_id', 'partial_content_version_id'], ['workspace_id', 'id'],
        ondelete='RESTRICT'
    )

    tenant_tables = (
        'citations',
        'claim_decisions',
        'claims',
        'content_blocks',
        'content_collaboration_events',
        'content_comments',
        'content_edit_leases',
        'content_feedback',
        'content_library_markers',
        'content_lineage',
        'content_versions',
        'contents',
        'generation_input_snapshots',
        'generation_job_commands',
        'generation_job_steps',
        'generation_jobs',
        'generation_snapshot_keyword_metrics',
        'generation_snapshot_sources',
        'model_catalog',
        'model_pricing_versions',
        'model_runs',
        'prompt_versions',
        'prompts',
        'research_artifacts',
        'research_cache_entries',
        'research_conflicts',
        'research_queries',
        'research_runs',
        'template_versions',
        'templates',
    )
    for table_name in tenant_tables:
        op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY')
        op.execute(
            f'''
            CREATE POLICY {table_name}_workspace_isolation ON {table_name}
            USING (workspace_id = app.current_workspace_id())
            WITH CHECK (workspace_id = app.current_workspace_id())
            '''
        )

    immutable_tables = (
        'citations',
        'claim_decisions',
        'claims',
        'content_blocks',
        'content_collaboration_events',
        'content_feedback',
        'content_library_markers',
        'content_lineage',
        'content_versions',
        'generation_input_snapshots',
        'generation_job_commands',
        'generation_snapshot_keyword_metrics',
        'generation_snapshot_sources',
        'model_pricing_versions',
        'model_runs',
        'prompt_versions',
        'research_artifacts',
        'research_cache_entries',
        'research_conflicts',
        'research_queries',
        'template_versions',
    )
    for table_name in immutable_tables:
        op.execute(
            f'''
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
            '''
        )

    op.execute(
        f'''
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_app') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_app;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(tenant_tables)} TO blogops_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_worker') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_worker;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(tenant_tables)} TO blogops_worker;
            END IF;
        END
        $$
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_generation_step_partial_version', 'generation_job_steps', type_='foreignkey'
    )
    op.drop_constraint(
        'fk_content_version_generation_job', 'content_versions', type_='foreignkey'
    )
    op.drop_constraint('fk_content_current_version', 'contents', type_='foreignkey')
    op.drop_constraint('fk_template_current_version', 'templates', type_='foreignkey')
    op.drop_constraint('fk_prompt_current_version', 'prompts', type_='foreignkey')
    op.drop_index(op.f('ix_citations_workspace_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_source_version_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_research_artifact_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_claim_id'), table_name='citations')
    op.drop_index('ix_citations_claim', table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_research_artifacts_workspace_id'), table_name='research_artifacts')
    op.drop_index(op.f('ix_research_artifacts_source_version_id'), table_name='research_artifacts')
    op.drop_index(op.f('ix_research_artifacts_research_run_id'), table_name='research_artifacts')
    op.drop_index(op.f('ix_research_artifacts_query_id'), table_name='research_artifacts')
    op.drop_index('ix_research_artifacts_grade', table_name='research_artifacts')
    op.drop_table('research_artifacts')
    op.drop_index(op.f('ix_claim_decisions_workspace_id'), table_name='claim_decisions')
    op.drop_index(op.f('ix_claim_decisions_replacement_claim_id'), table_name='claim_decisions')
    op.drop_index(op.f('ix_claim_decisions_claim_id'), table_name='claim_decisions')
    op.drop_index('ix_claim_decisions_claim', table_name='claim_decisions')
    op.drop_table('claim_decisions')
    op.drop_index(op.f('ix_research_queries_workspace_id'), table_name='research_queries')
    op.drop_index('ix_research_queries_run', table_name='research_queries')
    op.drop_index(op.f('ix_research_queries_research_run_id'), table_name='research_queries')
    op.drop_table('research_queries')
    op.drop_index(op.f('ix_research_conflicts_workspace_id'), table_name='research_conflicts')
    op.drop_index(op.f('ix_research_conflicts_research_run_id'), table_name='research_conflicts')
    op.drop_table('research_conflicts')
    op.drop_index(op.f('ix_model_runs_workspace_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_step_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_job_id'), table_name='model_runs')
    op.drop_index('ix_model_runs_job', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_claims_workspace_id'), table_name='claims')
    op.drop_index('ix_claims_status', table_name='claims')
    op.drop_index(op.f('ix_claims_research_run_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_content_version_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_block_key'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_research_runs_workspace_id'), table_name='research_runs')
    op.drop_index('ix_research_runs_state', table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_requested_by'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_generation_job_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_content_id'), table_name='research_runs')
    op.drop_index('ix_research_runs_content', table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_brief_version_id'), table_name='research_runs')
    op.drop_table('research_runs')
    op.drop_index('ix_generation_steps_state', table_name='generation_job_steps')
    op.drop_index(op.f('ix_generation_job_steps_workspace_id'), table_name='generation_job_steps')
    op.drop_index(op.f('ix_generation_job_steps_partial_content_version_id'), table_name='generation_job_steps')
    op.drop_index(op.f('ix_generation_job_steps_job_id'), table_name='generation_job_steps')
    op.drop_table('generation_job_steps')
    op.drop_index(op.f('ix_generation_job_commands_workspace_id'), table_name='generation_job_commands')
    op.drop_index(op.f('ix_generation_job_commands_job_id'), table_name='generation_job_commands')
    op.drop_table('generation_job_commands')
    op.drop_index(op.f('ix_content_lineage_workspace_id'), table_name='content_lineage')
    op.drop_index(op.f('ix_content_lineage_parent_content_version_id'), table_name='content_lineage')
    op.drop_index(op.f('ix_content_lineage_child_content_version_id'), table_name='content_lineage')
    op.drop_table('content_lineage')
    op.drop_index(op.f('ix_content_feedback_workspace_id'), table_name='content_feedback')
    op.drop_index(op.f('ix_content_feedback_generation_job_id'), table_name='content_feedback')
    op.drop_index(op.f('ix_content_feedback_content_version_id'), table_name='content_feedback')
    op.drop_index(op.f('ix_content_feedback_content_id'), table_name='content_feedback')
    op.drop_table('content_feedback')
    op.drop_index(op.f('ix_content_comments_workspace_id'), table_name='content_comments')
    op.drop_index('ix_content_comments_target', table_name='content_comments')
    op.drop_index(op.f('ix_content_comments_parent_comment_id'), table_name='content_comments')
    op.drop_index(op.f('ix_content_comments_content_version_id'), table_name='content_comments')
    op.drop_index(op.f('ix_content_comments_content_id'), table_name='content_comments')
    op.drop_table('content_comments')
    op.drop_index('ix_content_events_timeline', table_name='content_collaboration_events')
    op.drop_index(op.f('ix_content_collaboration_events_workspace_id'), table_name='content_collaboration_events')
    op.drop_index(op.f('ix_content_collaboration_events_content_version_id'), table_name='content_collaboration_events')
    op.drop_index(op.f('ix_content_collaboration_events_content_id'), table_name='content_collaboration_events')
    op.drop_table('content_collaboration_events')
    op.drop_index(op.f('ix_content_blocks_workspace_id'), table_name='content_blocks')
    op.drop_index(op.f('ix_content_blocks_content_version_id'), table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_generation_snapshot_sources_workspace_id'), table_name='generation_snapshot_sources')
    op.drop_index(op.f('ix_generation_snapshot_sources_source_version_id'), table_name='generation_snapshot_sources')
    op.drop_index(op.f('ix_generation_snapshot_sources_snapshot_id'), table_name='generation_snapshot_sources')
    op.drop_table('generation_snapshot_sources')
    op.drop_index(op.f('ix_generation_snapshot_keyword_metrics_workspace_id'), table_name='generation_snapshot_keyword_metrics')
    op.drop_index(op.f('ix_generation_snapshot_keyword_metrics_snapshot_id'), table_name='generation_snapshot_keyword_metrics')
    op.drop_index(op.f('ix_generation_snapshot_keyword_metrics_metric_snapshot_id'), table_name='generation_snapshot_keyword_metrics')
    op.drop_table('generation_snapshot_keyword_metrics')
    op.drop_index(op.f('ix_generation_jobs_workspace_id'), table_name='generation_jobs')
    op.drop_index('ix_generation_jobs_state', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_requested_by'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_input_snapshot_id'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_content_id'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_content_versions_workspace_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_restored_from_version_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_parent_version_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_generation_snapshot_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_generation_job_id'), table_name='content_versions')
    op.drop_index(op.f('ix_content_versions_content_id'), table_name='content_versions')
    op.drop_index('ix_content_versions_content', table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index('ix_generation_snapshot_brief', table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_workspace_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_template_version_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_prompt_version_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_pricing_version_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_model_entry_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_brief_version_id'), table_name='generation_input_snapshots')
    op.drop_index(op.f('ix_generation_input_snapshots_brief_id'), table_name='generation_input_snapshots')
    op.drop_table('generation_input_snapshots')
    op.drop_index(op.f('ix_content_library_markers_workspace_id'), table_name='content_library_markers')
    op.drop_index(op.f('ix_content_library_markers_content_id'), table_name='content_library_markers')
    op.drop_index(op.f('ix_content_library_markers_actor_id'), table_name='content_library_markers')
    op.drop_table('content_library_markers')
    op.drop_index(op.f('ix_content_edit_leases_workspace_id'), table_name='content_edit_leases')
    op.drop_index(op.f('ix_content_edit_leases_content_id'), table_name='content_edit_leases')
    op.drop_index('ix_content_edit_lease_expiry', table_name='content_edit_leases')
    op.drop_table('content_edit_leases')
    op.drop_index('ix_contents_workspace_type', table_name='contents')
    op.drop_index('ix_contents_workspace_state', table_name='contents')
    op.drop_index(op.f('ix_contents_workspace_id'), table_name='contents')
    op.drop_index('ix_contents_workspace_author', table_name='contents')
    op.drop_index(op.f('ix_contents_expires_at'), table_name='contents')
    op.drop_index(op.f('ix_contents_deleted_at'), table_name='contents')
    op.drop_index(op.f('ix_contents_current_version_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_created_by'), table_name='contents')
    op.drop_index(op.f('ix_contents_brief_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_brand_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_constraint('brand_workspace_id', 'brands', type_='unique')
    op.drop_index(op.f('ix_template_versions_workspace_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_template_id'), table_name='template_versions')
    op.drop_index(op.f('ix_template_versions_prompt_version_id'), table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_prompt_versions_workspace_id'), table_name='prompt_versions')
    op.drop_index('ix_prompt_versions_status', table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_prompt_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_model_pricing_versions_workspace_id'), table_name='model_pricing_versions')
    op.drop_index(op.f('ix_model_pricing_versions_model_entry_id'), table_name='model_pricing_versions')
    op.drop_table('model_pricing_versions')
    op.drop_index('ix_templates_workspace_type', table_name='templates')
    op.drop_index(op.f('ix_templates_workspace_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_owner_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_current_version_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index('ix_research_cache_expiry', table_name='research_cache_entries')
    op.drop_index(op.f('ix_research_cache_entries_workspace_id'), table_name='research_cache_entries')
    op.drop_table('research_cache_entries')
    op.drop_index(op.f('ix_prompts_workspace_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_current_version_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_model_catalog_workspace_id'), table_name='model_catalog')
    op.drop_index('ix_model_catalog_status', table_name='model_catalog')
    op.drop_index(op.f('ix_model_catalog_replacement_entry_id'), table_name='model_catalog')
    op.drop_table('model_catalog')
    # ### end Alembic commands ###
