"""media_bulk

Revision ID: b386e9e57103
Revises: f56325b3586e
Create Date: 2026-08-23 15:08:33.898617
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b386e9e57103'
down_revision: str | None = 'f56325b3586e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    'bulk_callback_deliveries',
    'bulk_export_artifacts',
    'bulk_input_files',
    'bulk_job_commands',
    'bulk_jobs',
    'bulk_mappings',
    'bulk_row_attempts',
    'bulk_rows',
    'bulk_schedules',
    'media_assets',
    'media_inspections',
    'media_job_commands',
    'media_license_revisions',
    'media_licenses',
    'media_operation_jobs',
    'media_plan_items',
    'media_plan_versions',
    'media_provider_connections',
    'media_scan_results',
    'media_usages',
    'media_versions',
)

IMMUTABLE_TABLES = (
    'bulk_callback_deliveries',
    'bulk_export_artifacts',
    'bulk_input_files',
    'bulk_job_commands',
    'bulk_mappings',
    'bulk_row_attempts',
    'media_inspections',
    'media_job_commands',
    'media_license_revisions',
    'media_plan_versions',
    'media_scan_results',
    'media_usages',
    'media_versions',
)

FROZEN_COLUMNS = {
    'bulk_jobs': (
        'workspace_id',
        'campaign_id',
        'input_file_id',
        'mapping_id',
        'template_version_id',
        'requested_by',
        'operation',
        'priority',
        'idempotency_key',
        'request_hash',
        'input_snapshot_hash',
        'mapping_snapshot',
        'mapping_snapshot_hash',
        'template_snapshot',
        'template_snapshot_hash',
        'brand_snapshot',
        'brand_snapshot_hash',
        'model_policy_snapshot',
        'model_policy_hash',
        'quality_policy_snapshot',
        'quality_policy_hash',
        'approval_policy_snapshot',
        'approval_policy_hash',
        'publishing_policy_snapshot',
        'publishing_policy_hash',
        'retry_policy_snapshot',
        'concurrency_policy_snapshot',
        'callback_endpoint_ref',
        'callback_secret_ref',
        'dry_run',
        'sample_size',
        'total_rows',
        'estimated_cost',
        'maximum_cost',
        'authorized_cost',
        'currency',
        'budget_reservation_ref',
        'max_row_attempts',
        'concurrency_limit',
        'daily_throughput_limit',
    ),
    'bulk_rows': (
        'workspace_id',
        'job_id',
        'row_no',
        'row_idempotency_key',
        'input_hash',
        'input_json',
        'estimated_cost',
    ),
    'media_operation_jobs': (
        'workspace_id',
        'requested_by',
        'operation',
        'provider_connection_id',
        'source_asset_id',
        'source_version_id',
        'idempotency_key',
        'request_hash',
        'input_snapshot',
        'input_snapshot_hash',
        'policy_snapshot',
        'policy_snapshot_hash',
        'prompt_snapshot',
        'prompt_hash',
        'estimated_cost',
        'currency',
        'budget_reservation_ref',
        'budget_limit',
        'provider_quota_reserved',
        'max_attempts',
    ),
    'media_plan_items': (
        'workspace_id',
        'plan_id',
        'sequence',
        'section_key',
        'need_kind',
        'reason',
        'requires_real_photo',
        'generation_allowed',
        'generation_prompt',
        'prohibited_elements',
        'alt_text_plan',
        'caption_plan',
        'aspect_ratio',
        'placement_json',
        'candidate_asset_ids',
        'duplicate_warning',
        'performance_ref',
    ),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'approval_request_exact_identity',
        'content_approval_requests',
        ['workspace_id', 'id', 'content_id', 'content_version_id', 'content_hash'],
    )
    op.create_unique_constraint(
        'content_version_exact_identity',
        'content_versions',
        ['workspace_id', 'content_id', 'id', 'content_hash'],
    )
    op.create_unique_constraint(
        'quality_assessment_exact_identity',
        'quality_assessments',
        ['workspace_id', 'id', 'content_id', 'content_version_id', 'content_hash'],
    )
    op.create_table('bulk_input_files',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('input_kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('object_ref', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('encoding', sa.String(length=40), nullable=True),
    sa.Column('delimiter', sa.String(length=8), nullable=True),
    sa.Column('sheet_name', sa.String(length=240), nullable=True),
    sa.Column('sheet_range', sa.String(length=240), nullable=True),
    sa.Column('header_row', sa.Integer(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_locator', sa.Text(), nullable=True),
    sa.Column('source_locator_hash', sa.String(length=64), nullable=True),
    sa.Column('source_connection_ref', sa.String(length=512), nullable=True),
    sa.Column('source_secret_ref', sa.String(length=512), nullable=True),
    sa.Column('malware_scan_status', sa.String(length=24), nullable=False),
    sa.Column('malware_scanner', sa.String(length=120), nullable=True),
    sa.Column('malware_scanner_version', sa.String(length=80), nullable=True),
    sa.Column('malware_scan_result_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("malware_scan_status IN ('CLEAN', 'NOT_REQUIRED')", name=op.f('ck_bulk_input_files_bulk_input_scan_status_valid')),
    sa.CheckConstraint('header_row > 0', name=op.f('ck_bulk_input_files_bulk_input_header_positive')),
    sa.CheckConstraint('row_count > 0', name=op.f('ck_bulk_input_files_bulk_input_rows_positive')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_bulk_input_files_bulk_input_size_nonnegative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_input_files')),
    sa.UniqueConstraint('workspace_id', 'content_hash', name='bulk_input_content_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_input_workspace_id')
    )
    op.create_index(op.f('ix_bulk_input_files_workspace_id'), 'bulk_input_files', ['workspace_id'], unique=False)
    op.create_index('ix_bulk_input_workspace_time', 'bulk_input_files', ['workspace_id', 'created_at'], unique=False)
    op.create_table('bulk_mappings',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('variable_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalization_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_mappings')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_mapping_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'mapping_hash', name='bulk_mapping_hash')
    )
    op.create_index('ix_bulk_mapping_workspace_name', 'bulk_mappings', ['workspace_id', 'name'], unique=False)
    op.create_index(op.f('ix_bulk_mappings_workspace_id'), 'bulk_mappings', ['workspace_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('declared_mime_type', sa.String(length=120), nullable=False),
    sa.Column('declared_size_bytes', sa.Integer(), nullable=False),
    sa.Column('quarantine_object_ref', sa.String(length=1000), nullable=True),
    sa.Column('quarantine_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_content_hash', sa.String(length=64), nullable=True),
    sa.Column('original_version_id', sa.Uuid(), nullable=True),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('folder_path', sa.String(length=1000), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('ai_disclosure_required', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('declared_size_bytes > 0', name=op.f('ck_media_assets_media_asset_size_positive')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_media_assets_media_asset_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'id', 'current_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name='fk_media_asset_current_version', ondelete='RESTRICT', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id', 'id', 'original_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name='fk_media_asset_original_version', ondelete='RESTRICT', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_asset_workspace_id')
    )
    op.create_index('ix_media_asset_folder', 'media_assets', ['workspace_id', 'folder_path'], unique=False)
    op.create_index('ix_media_asset_original_hash', 'media_assets', ['workspace_id', 'original_content_hash'], unique=False)
    op.create_index('ix_media_asset_state', 'media_assets', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_created_by'), 'media_assets', ['created_by'], unique=False)
    op.create_index(op.f('ix_media_assets_current_version_id'), 'media_assets', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_media_assets_deleted_at'), 'media_assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_assets_original_version_id'), 'media_assets', ['original_version_id'], unique=False)
    op.create_index(op.f('ix_media_assets_workspace_id'), 'media_assets', ['workspace_id'], unique=False)
    op.create_table('media_provider_connections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('secret_ref', sa.String(length=512), nullable=False),
    sa.Column('license_ref', sa.String(length=512), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('circuit_open_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consecutive_failures >= 0', name=op.f('ck_media_provider_connections_provider_failures_nonnegative')),
    sa.CheckConstraint('daily_quota IS NULL OR daily_quota > 0', name=op.f('ck_media_provider_connections_media_provider_quota_positive')),
    sa.CheckConstraint('quota_remaining IS NULL OR quota_remaining >= 0', name=op.f('ck_media_provider_connections_media_provider_quota_remaining')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_provider_connections')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_provider_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'provider', 'name', name='media_provider_name')
    )
    op.create_index(op.f('ix_media_provider_connections_workspace_id'), 'media_provider_connections', ['workspace_id'], unique=False)
    op.create_index('ix_media_provider_state', 'media_provider_connections', ['workspace_id', 'state'], unique=False)
    op.create_table('media_licenses',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('current_revision_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_media_licenses_media_license_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id', 'current_revision_id'], ['media_license_revisions.workspace_id', 'media_license_revisions.asset_id', 'media_license_revisions.id'], name='fk_media_license_current_revision', ondelete='RESTRICT', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id'], ['media_assets.workspace_id', 'media_assets.id'], name=op.f('fk_media_licenses_workspace_id_media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_licenses')),
    sa.UniqueConstraint('workspace_id', 'asset_id', name='media_license_asset_once'),
    sa.UniqueConstraint('workspace_id', 'id', 'asset_id', name='media_license_asset_identity'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_license_workspace_id')
    )
    op.create_index('ix_media_license_expiry', 'media_licenses', ['workspace_id', 'state', 'valid_until'], unique=False)
    op.create_index(op.f('ix_media_licenses_asset_id'), 'media_licenses', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_licenses_current_revision_id'), 'media_licenses', ['current_revision_id'], unique=False)
    op.create_index(op.f('ix_media_licenses_valid_until'), 'media_licenses', ['valid_until'], unique=False)
    op.create_index(op.f('ix_media_licenses_workspace_id'), 'media_licenses', ['workspace_id'], unique=False)
    op.create_table('media_scan_results',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('quarantine_object_ref', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('detected_mime_type', sa.String(length=120), nullable=False),
    sa.Column('scanner', sa.String(length=120), nullable=False),
    sa.Column('scanner_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('signature', sa.String(length=500), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_media_scan_results_media_scan_size_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id'], ['media_assets.workspace_id', 'media_assets.id'], name=op.f('fk_media_scan_results_workspace_id_media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_scan_results')),
    sa.UniqueConstraint('workspace_id', 'asset_id', 'content_hash', 'scanner', 'scanner_version', name='media_scan_exact_file'),
    sa.UniqueConstraint('workspace_id', 'asset_id', 'id', name='media_scan_asset_identity'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_scan_workspace_id')
    )
    op.create_index('ix_media_scan_asset', 'media_scan_results', ['workspace_id', 'asset_id', 'scanned_at'], unique=False)
    op.create_index(op.f('ix_media_scan_results_asset_id'), 'media_scan_results', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_scan_results_workspace_id'), 'media_scan_results', ['workspace_id'], unique=False)
    op.create_table('media_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_kind', sa.String(length=16), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('object_ref', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('prompt_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('provider_version', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('edit_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sanitized_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('removed_metadata_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pii_detected', sa.Boolean(), nullable=False),
    sa.Column('face_detected', sa.Boolean(), nullable=False),
    sa.Column('trademark_detected', sa.Boolean(), nullable=False),
    sa.Column('safety_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('disclosure_text', sa.Text(), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_media_versions_media_version_cost_nonnegative')),
    sa.CheckConstraint('height > 0', name=op.f('ck_media_versions_media_version_height_positive')),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_media_versions_media_version_size_positive')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_media_versions_media_version_number_positive')),
    sa.CheckConstraint('width > 0', name=op.f('ck_media_versions_media_version_width_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id', 'parent_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name='fk_media_version_parent', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id'], ['media_assets.workspace_id', 'media_assets.id'], name=op.f('fk_media_versions_workspace_id_media_assets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_versions')),
    sa.UniqueConstraint('workspace_id', 'asset_id', 'id', name='media_version_asset_identity'),
    sa.UniqueConstraint('workspace_id', 'asset_id', 'version_number', name='media_version_no'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_version_workspace_id')
    )
    op.create_index('ix_media_version_asset', 'media_versions', ['workspace_id', 'asset_id', 'version_number'], unique=False)
    op.create_index('ix_media_version_hash', 'media_versions', ['workspace_id', 'content_hash'], unique=False)
    op.create_index(op.f('ix_media_versions_asset_id'), 'media_versions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_versions_model_run_id'), 'media_versions', ['model_run_id'], unique=False)
    op.create_index(op.f('ix_media_versions_parent_version_id'), 'media_versions', ['parent_version_id'], unique=False)
    op.create_index(op.f('ix_media_versions_workspace_id'), 'media_versions', ['workspace_id'], unique=False)
    op.create_table('media_inspections',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('scan_result_id', sa.Uuid(), nullable=False),
    sa.Column('inspector', sa.String(length=120), nullable=False),
    sa.Column('inspector_version', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('sanitized_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('removed_metadata_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pii_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('face_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trademark_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transformation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sanitized_object_ref', sa.String(length=1000), nullable=True),
    sa.Column('sanitized_content_hash', sa.String(length=64), nullable=False),
    sa.Column('sanitized_size_bytes', sa.Integer(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('height > 0', name=op.f('ck_media_inspections_media_inspection_height_positive')),
    sa.CheckConstraint('sanitized_size_bytes > 0', name=op.f('ck_media_inspections_media_inspection_size_positive')),
    sa.CheckConstraint('width > 0', name=op.f('ck_media_inspections_media_inspection_width_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id', 'scan_result_id'], ['media_scan_results.workspace_id', 'media_scan_results.asset_id', 'media_scan_results.id'], name=op.f('fk_media_inspections_workspace_id_media_scan_results'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_inspections')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_inspection_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'scan_result_id', 'inspector', 'inspector_version', name='media_inspection_scan_version')
    )
    op.create_index('ix_media_inspection_asset', 'media_inspections', ['workspace_id', 'asset_id', 'inspected_at'], unique=False)
    op.create_index(op.f('ix_media_inspections_asset_id'), 'media_inspections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_inspections_scan_result_id'), 'media_inspections', ['scan_result_id'], unique=False)
    op.create_index(op.f('ix_media_inspections_workspace_id'), 'media_inspections', ['workspace_id'], unique=False)
    op.create_table('media_license_revisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('license_id', sa.Uuid(), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('license_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_asset_ref', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commercial_allowed', sa.Boolean(), nullable=False),
    sa.Column('editorial_allowed', sa.Boolean(), nullable=False),
    sa.Column('allowed_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derivative_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_object_ref', sa.String(length=1000), nullable=True),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('revision > 0', name=op.f('ck_media_license_revisions_media_license_revision_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'license_id', 'asset_id'], ['media_licenses.workspace_id', 'media_licenses.id', 'media_licenses.asset_id'], name=op.f('fk_media_license_revisions_workspace_id_media_licenses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_license_revisions')),
    sa.UniqueConstraint('workspace_id', 'asset_id', 'id', name='media_license_revision_asset_id'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_license_revision_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'license_id', 'revision', name='media_license_revision_no'),
    sa.UniqueConstraint('workspace_id', 'license_id', 'snapshot_hash', name='media_license_revision_hash')
    )
    op.create_index('ix_media_license_revision_asset', 'media_license_revisions', ['workspace_id', 'asset_id', 'revision'], unique=False)
    op.create_index(op.f('ix_media_license_revisions_asset_id'), 'media_license_revisions', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_license_revisions_license_id'), 'media_license_revisions', ['license_id'], unique=False)
    op.create_index(op.f('ix_media_license_revisions_workspace_id'), 'media_license_revisions', ['workspace_id'], unique=False)
    op.create_table('media_operation_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('provider_connection_id', sa.Uuid(), nullable=True),
    sa.Column('source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('source_version_id', sa.Uuid(), nullable=True),
    sa.Column('result_asset_id', sa.Uuid(), nullable=True),
    sa.Column('result_version_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('budget_reservation_ref', sa.String(length=512), nullable=True),
    sa.Column('budget_limit', sa.Numeric(precision=19, scale=6), nullable=True),
    sa.Column('budget_kill_switch_triggered', sa.Boolean(), nullable=False),
    sa.Column('provider_quota_reserved', sa.Boolean(), nullable=False),
    sa.Column('provider_quota_released', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(result_asset_id IS NULL) = (result_version_id IS NULL)', name=op.f('ck_media_operation_jobs_media_job_result_pair_complete')),
    sa.CheckConstraint('(source_asset_id IS NULL) = (source_version_id IS NULL)', name=op.f('ck_media_operation_jobs_media_job_source_pair_complete')),
    sa.CheckConstraint('NOT provider_quota_released OR provider_quota_reserved', name=op.f('ck_media_operation_jobs_quota_release_requires_reservation')),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name=op.f('ck_media_operation_jobs_media_job_actual_nonnegative')),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_media_operation_jobs_media_job_attempt_nonnegative')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_media_operation_jobs_media_job_estimate_nonnegative')),
    sa.CheckConstraint('max_attempts > 0', name=op.f('ck_media_operation_jobs_media_job_max_attempts_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'provider_connection_id'], ['media_provider_connections.workspace_id', 'media_provider_connections.id'], name=op.f('fk_media_operation_jobs_workspace_id_media_provider_connections'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'result_asset_id', 'result_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name='fk_media_job_result_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'source_asset_id', 'source_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name='fk_media_job_source_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_operation_jobs')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_job_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'requested_by', 'operation', 'idempotency_key', name='media_job_idempotency')
    )
    op.create_index('ix_media_job_state', 'media_operation_jobs', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_provider_connection_id'), 'media_operation_jobs', ['provider_connection_id'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_requested_by'), 'media_operation_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_result_asset_id'), 'media_operation_jobs', ['result_asset_id'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_result_version_id'), 'media_operation_jobs', ['result_version_id'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_source_asset_id'), 'media_operation_jobs', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_source_version_id'), 'media_operation_jobs', ['source_version_id'], unique=False)
    op.create_index(op.f('ix_media_operation_jobs_workspace_id'), 'media_operation_jobs', ['workspace_id'], unique=False)
    op.create_table('bulk_jobs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('input_file_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('mapping_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('brand_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('model_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('publishing_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('publishing_policy_hash', sa.String(length=64), nullable=False),
    sa.Column('retry_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concurrency_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('callback_endpoint_ref', sa.String(length=512), nullable=True),
    sa.Column('callback_secret_ref', sa.String(length=512), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('succeeded_rows', sa.Integer(), nullable=False),
    sa.Column('review_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('cancelled_rows', sa.Integer(), nullable=False),
    sa.Column('progress_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('maximum_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('authorized_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('held_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('budget_reservation_ref', sa.String(length=512), nullable=True),
    sa.Column('budget_kill_switch_triggered', sa.Boolean(), nullable=False),
    sa.Column('pause_requested', sa.Boolean(), nullable=False),
    sa.Column('pause_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_by', sa.Uuid(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Uuid(), nullable=True),
    sa.Column('max_row_attempts', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('daily_throughput_limit', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('result_manifest_ref', sa.String(length=1000), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_bulk_jobs_bulk_job_actual_nonnegative')),
    sa.CheckConstraint('authorized_cost >= 0', name=op.f('ck_bulk_jobs_bulk_job_authorized_nonnegative')),
    sa.CheckConstraint('cancelled_rows >= 0', name=op.f('ck_bulk_jobs_bulk_job_cancelled_nonnegative')),
    sa.CheckConstraint('concurrency_limit > 0', name=op.f('ck_bulk_jobs_bulk_job_concurrency_positive')),
    sa.CheckConstraint('daily_throughput_limit > 0', name=op.f('ck_bulk_jobs_bulk_job_daily_positive')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_bulk_jobs_bulk_job_estimate_nonnegative')),
    sa.CheckConstraint('failed_rows >= 0', name=op.f('ck_bulk_jobs_bulk_job_failed_nonnegative')),
    sa.CheckConstraint('held_cost >= 0', name=op.f('ck_bulk_jobs_bulk_job_held_nonnegative')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_bulk_jobs_bulk_job_lock_positive')),
    sa.CheckConstraint('max_row_attempts > 0', name=op.f('ck_bulk_jobs_bulk_job_attempts_positive')),
    sa.CheckConstraint('maximum_cost > 0', name=op.f('ck_bulk_jobs_bulk_job_max_cost_positive')),
    sa.CheckConstraint('processed_rows >= 0', name=op.f('ck_bulk_jobs_bulk_job_processed_nonnegative')),
    sa.CheckConstraint('review_rows >= 0', name=op.f('ck_bulk_jobs_bulk_job_review_nonnegative')),
    sa.CheckConstraint('succeeded_rows >= 0', name=op.f('ck_bulk_jobs_bulk_job_succeeded_nonnegative')),
    sa.CheckConstraint('total_rows > 0', name=op.f('ck_bulk_jobs_bulk_job_total_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'campaign_id'], ['campaigns.workspace_id', 'campaigns.id'], name=op.f('fk_bulk_jobs_workspace_id_campaigns'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'input_file_id'], ['bulk_input_files.workspace_id', 'bulk_input_files.id'], name=op.f('fk_bulk_jobs_workspace_id_bulk_input_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'mapping_id'], ['bulk_mappings.workspace_id', 'bulk_mappings.id'], name=op.f('fk_bulk_jobs_workspace_id_bulk_mappings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'template_version_id'], ['template_versions.workspace_id', 'template_versions.id'], name=op.f('fk_bulk_jobs_workspace_id_template_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_jobs')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_job_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'requested_by', 'operation', 'idempotency_key', name='bulk_job_idempotency')
    )
    op.create_index('ix_bulk_job_campaign', 'bulk_jobs', ['workspace_id', 'campaign_id', 'created_at'], unique=False)
    op.create_index('ix_bulk_job_state', 'bulk_jobs', ['workspace_id', 'state', 'created_at'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_campaign_id'), 'bulk_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_input_file_id'), 'bulk_jobs', ['input_file_id'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_mapping_id'), 'bulk_jobs', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_requested_by'), 'bulk_jobs', ['requested_by'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_template_version_id'), 'bulk_jobs', ['template_version_id'], unique=False)
    op.create_index(op.f('ix_bulk_jobs_workspace_id'), 'bulk_jobs', ['workspace_id'], unique=False)
    op.create_table('bulk_schedules',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('input_file_id', sa.Uuid(), nullable=False),
    sa.Column('mapping_id', sa.Uuid(), nullable=False),
    sa.Column('template_version_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('schedule_expression', sa.String(length=240), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('last_input_hash', sa.String(length=64), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_bulk_schedules_bulk_schedule_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'input_file_id'], ['bulk_input_files.workspace_id', 'bulk_input_files.id'], name=op.f('fk_bulk_schedules_workspace_id_bulk_input_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'mapping_id'], ['bulk_mappings.workspace_id', 'bulk_mappings.id'], name=op.f('fk_bulk_schedules_workspace_id_bulk_mappings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'template_version_id'], ['template_versions.workspace_id', 'template_versions.id'], name=op.f('fk_bulk_schedules_workspace_id_template_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_schedules')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_schedule_workspace_id')
    )
    op.create_index('ix_bulk_schedule_due', 'bulk_schedules', ['workspace_id', 'state', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_bulk_schedules_workspace_id'), 'bulk_schedules', ['workspace_id'], unique=False)
    op.create_table('media_job_commands',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('command_kind', sa.String(length=24), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('from_state', sa.String(length=32), nullable=False),
    sa.Column('to_state', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['media_operation_jobs.workspace_id', 'media_operation_jobs.id'], name=op.f('fk_media_job_commands_workspace_id_media_operation_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_job_commands')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_command_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'actor_id', 'command_kind', 'idempotency_key', name='media_command_idempotency')
    )
    op.create_index('ix_media_command_job', 'media_job_commands', ['workspace_id', 'job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_job_commands_job_id'), 'media_job_commands', ['job_id'], unique=False)
    op.create_index(op.f('ix_media_job_commands_workspace_id'), 'media_job_commands', ['workspace_id'], unique=False)
    op.create_table('bulk_export_artifacts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('export_kind', sa.String(length=32), nullable=False),
    sa.Column('object_ref', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manifest_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['bulk_jobs.workspace_id', 'bulk_jobs.id'], name=op.f('fk_bulk_export_artifacts_workspace_id_bulk_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_export_artifacts')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_export_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'export_kind', 'manifest_hash', name='bulk_export_manifest')
    )
    op.create_index(op.f('ix_bulk_export_artifacts_job_id'), 'bulk_export_artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_export_artifacts_workspace_id'), 'bulk_export_artifacts', ['workspace_id'], unique=False)
    op.create_index('ix_bulk_export_job', 'bulk_export_artifacts', ['workspace_id', 'job_id', 'created_at'], unique=False)
    op.create_table('bulk_job_commands',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['bulk_jobs.workspace_id', 'bulk_jobs.id'], name=op.f('fk_bulk_job_commands_workspace_id_bulk_jobs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_job_commands')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_command_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'actor_id', 'kind', 'idempotency_key', name='bulk_command_idempotency')
    )
    op.create_index('ix_bulk_command_job', 'bulk_job_commands', ['workspace_id', 'job_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bulk_job_commands_job_id'), 'bulk_job_commands', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_job_commands_workspace_id'), 'bulk_job_commands', ['workspace_id'], unique=False)
    op.create_table('media_plan_versions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('recommended_count', sa.Integer(), nullable=False),
    sa.Column('count_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('brand_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('recommended_count >= 0', name=op.f('ck_media_plan_versions_media_plan_count_nonnegative')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.content_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_media_plan_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_media_plan_versions_workspace_id_contents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_plan_versions')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'plan_hash', name='media_plan_version_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_plan_workspace_id')
    )
    op.create_index('ix_media_plan_content', 'media_plan_versions', ['workspace_id', 'content_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_media_plan_versions_content_id'), 'media_plan_versions', ['content_id'], unique=False)
    op.create_index(op.f('ix_media_plan_versions_content_version_id'), 'media_plan_versions', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_media_plan_versions_workspace_id'), 'media_plan_versions', ['workspace_id'], unique=False)
    op.create_table('media_usages',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.Uuid(), nullable=False),
    sa.Column('media_version_id', sa.Uuid(), nullable=False),
    sa.Column('license_revision_id', sa.Uuid(), nullable=False),
    sa.Column('placement_key', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=True),
    sa.Column('usage_mode', sa.String(length=24), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('rights_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rights_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id', 'license_revision_id'], ['media_license_revisions.workspace_id', 'media_license_revisions.asset_id', 'media_license_revisions.id'], name=op.f('fk_media_usages_workspace_id_media_license_revisions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'asset_id', 'media_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name=op.f('fk_media_usages_workspace_id_media_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.content_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_media_usage_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_media_usages_workspace_id_contents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_usages')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'placement_key', name='media_usage_placement'),
    sa.UniqueConstraint('workspace_id', 'id', name='media_usage_workspace_id')
    )
    op.create_index('ix_media_usage_asset', 'media_usages', ['workspace_id', 'asset_id', 'created_at'], unique=False)
    op.create_index('ix_media_usage_content', 'media_usages', ['workspace_id', 'content_version_id'], unique=False)
    op.create_index(op.f('ix_media_usages_asset_id'), 'media_usages', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_usages_content_id'), 'media_usages', ['content_id'], unique=False)
    op.create_index(op.f('ix_media_usages_content_version_id'), 'media_usages', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_media_usages_license_revision_id'), 'media_usages', ['license_revision_id'], unique=False)
    op.create_index(op.f('ix_media_usages_media_version_id'), 'media_usages', ['media_version_id'], unique=False)
    op.create_index(op.f('ix_media_usages_workspace_id'), 'media_usages', ['workspace_id'], unique=False)
    op.create_table('media_plan_items',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=160), nullable=True),
    sa.Column('need_kind', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('requires_real_photo', sa.Boolean(), nullable=False),
    sa.Column('generation_allowed', sa.Boolean(), nullable=False),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('prohibited_elements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alt_text_plan', sa.Text(), nullable=False),
    sa.Column('caption_plan', sa.Text(), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=32), nullable=True),
    sa.Column('placement_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('candidate_asset_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selection_state', sa.String(length=24), nullable=False),
    sa.Column('selected_asset_id', sa.Uuid(), nullable=True),
    sa.Column('selected_version_id', sa.Uuid(), nullable=True),
    sa.Column('selected_by', sa.Uuid(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duplicate_warning', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performance_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_media_plan_items_media_plan_item_lock_positive')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_media_plan_items_media_plan_item_sequence_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'plan_id'], ['media_plan_versions.workspace_id', 'media_plan_versions.id'], name=op.f('fk_media_plan_items_workspace_id_media_plan_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'selected_asset_id', 'selected_version_id'], ['media_versions.workspace_id', 'media_versions.asset_id', 'media_versions.id'], name=op.f('fk_media_plan_items_workspace_id_media_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_plan_items')),
    sa.UniqueConstraint('workspace_id', 'id', name='media_plan_item_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'plan_id', 'sequence', name='media_plan_item_sequence')
    )
    op.create_index('ix_media_plan_item_plan', 'media_plan_items', ['workspace_id', 'plan_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_media_plan_items_plan_id'), 'media_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_media_plan_items_selected_asset_id'), 'media_plan_items', ['selected_asset_id'], unique=False)
    op.create_index(op.f('ix_media_plan_items_selected_version_id'), 'media_plan_items', ['selected_version_id'], unique=False)
    op.create_index(op.f('ix_media_plan_items_workspace_id'), 'media_plan_items', ['workspace_id'], unique=False)
    op.create_table('bulk_rows',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('row_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_of_row_id', sa.Uuid(), nullable=True),
    sa.Column('duplicate_action', sa.String(length=24), nullable=True),
    sa.Column('semantic_duplicate_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('keyword_cluster_ref', sa.String(length=512), nullable=True),
    sa.Column('existing_content_action', sa.String(length=24), nullable=True),
    sa.Column('existing_content_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('content_version_id', sa.Uuid(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('quality_assessment_id', sa.Uuid(), nullable=True),
    sa.Column('quality_passed', sa.Boolean(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('approved_content_hash', sa.String(length=64), nullable=True),
    sa.Column('hard_blocked', sa.Boolean(), nullable=False),
    sa.Column('risk_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spam_similarity_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('value_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=120), nullable=True),
    sa.Column('last_error_detail', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(content_id IS NULL) = (content_version_id IS NULL) AND (content_version_id IS NULL) = (content_hash IS NULL)', name=op.f('ck_bulk_rows_bulk_row_content_identity_complete')),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_bulk_rows_bulk_row_actual_nonnegative')),
    sa.CheckConstraint('approval_request_id IS NULL OR content_version_id IS NOT NULL', name=op.f('ck_bulk_rows_bulk_row_approval_content_required')),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_bulk_rows_bulk_row_attempt_nonnegative')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_bulk_rows_bulk_row_estimate_nonnegative')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_bulk_rows_bulk_row_lock_positive')),
    sa.CheckConstraint('quality_assessment_id IS NULL OR content_version_id IS NOT NULL', name=op.f('ck_bulk_rows_bulk_row_quality_content_required')),
    sa.CheckConstraint('row_no > 0', name=op.f('ck_bulk_rows_bulk_row_number_positive')),
    sa.CheckConstraint('semantic_duplicate_score IS NULL OR (semantic_duplicate_score >= 0 AND semantic_duplicate_score <= 1)', name=op.f('ck_bulk_rows_bulk_row_duplicate_score_range')),
    sa.CheckConstraint('value_score IS NULL OR (value_score >= 0 AND value_score <= 100)', name=op.f('ck_bulk_rows_bulk_row_value_score_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'approval_request_id', 'content_id', 'content_version_id', 'content_hash'], ['content_approval_requests.workspace_id', 'content_approval_requests.id', 'content_approval_requests.content_id', 'content_approval_requests.content_version_id', 'content_approval_requests.content_hash'], name='fk_bulk_row_exact_approval_request', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.content_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_bulk_row_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'generation_job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_bulk_rows_workspace_id_generation_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id', 'duplicate_of_row_id'], ['bulk_rows.workspace_id', 'bulk_rows.job_id', 'bulk_rows.id'], name='fk_bulk_row_duplicate', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id'], ['bulk_jobs.workspace_id', 'bulk_jobs.id'], name=op.f('fk_bulk_rows_workspace_id_bulk_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'quality_assessment_id', 'content_id', 'content_version_id', 'content_hash'], ['quality_assessments.workspace_id', 'quality_assessments.id', 'quality_assessments.content_id', 'quality_assessments.content_version_id', 'quality_assessments.content_hash'], name='fk_bulk_row_exact_quality_assessment', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_rows')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_row_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'id', name='bulk_row_job_identity'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'row_idempotency_key', name='bulk_row_idempotency'),
    sa.UniqueConstraint('workspace_id', 'job_id', 'row_no', name='bulk_row_number')
    )
    op.create_index('ix_bulk_row_content', 'bulk_rows', ['workspace_id', 'content_id'], unique=False)
    op.create_index('ix_bulk_row_input_hash', 'bulk_rows', ['workspace_id', 'job_id', 'input_hash'], unique=False)
    op.create_index('ix_bulk_row_state', 'bulk_rows', ['workspace_id', 'job_id', 'state', 'row_no'], unique=False)
    op.create_index(op.f('ix_bulk_rows_approval_request_id'), 'bulk_rows', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_content_id'), 'bulk_rows', ['content_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_content_version_id'), 'bulk_rows', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_duplicate_of_row_id'), 'bulk_rows', ['duplicate_of_row_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_generation_job_id'), 'bulk_rows', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_job_id'), 'bulk_rows', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_quality_assessment_id'), 'bulk_rows', ['quality_assessment_id'], unique=False)
    op.create_index(op.f('ix_bulk_rows_workspace_id'), 'bulk_rows', ['workspace_id'], unique=False)
    op.create_table('bulk_callback_deliveries',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_ref', sa.String(length=512), nullable=False),
    sa.Column('secret_ref', sa.String(length=512), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_version', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('attempt > 0', name=op.f('ck_bulk_callback_deliveries_bulk_callback_attempt_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id', 'row_id'], ['bulk_rows.workspace_id', 'bulk_rows.job_id', 'bulk_rows.id'], name=op.f('fk_bulk_callback_deliveries_workspace_id_bulk_rows'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_callback_deliveries')),
    sa.UniqueConstraint('workspace_id', 'event_id', 'attempt', name='bulk_callback_event_attempt'),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_callback_workspace_id')
    )
    op.create_index(op.f('ix_bulk_callback_deliveries_job_id'), 'bulk_callback_deliveries', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_callback_deliveries_row_id'), 'bulk_callback_deliveries', ['row_id'], unique=False)
    op.create_index(op.f('ix_bulk_callback_deliveries_workspace_id'), 'bulk_callback_deliveries', ['workspace_id'], unique=False)
    op.create_index('ix_bulk_callback_state', 'bulk_callback_deliveries', ['workspace_id', 'state', 'next_attempt_at'], unique=False)
    op.create_table('bulk_row_attempts',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('content_version_id', sa.Uuid(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('quality_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approval_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=19, scale=6), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('(content_id IS NULL) = (content_version_id IS NULL) AND (content_version_id IS NULL) = (content_hash IS NULL)', name=op.f('ck_bulk_row_attempts_bulk_attempt_content_identity_complete')),
    sa.CheckConstraint('actual_cost >= 0', name=op.f('ck_bulk_row_attempts_bulk_attempt_cost_nonnegative')),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_bulk_row_attempts_bulk_attempt_number_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.content_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_bulk_attempt_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'generation_job_id'], ['generation_jobs.workspace_id', 'generation_jobs.id'], name=op.f('fk_bulk_row_attempts_workspace_id_generation_jobs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'job_id', 'row_id'], ['bulk_rows.workspace_id', 'bulk_rows.job_id', 'bulk_rows.id'], name=op.f('fk_bulk_row_attempts_workspace_id_bulk_rows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_row_attempts')),
    sa.UniqueConstraint('workspace_id', 'id', name='bulk_attempt_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'row_id', 'attempt_number', name='bulk_attempt_number')
    )
    op.create_index('ix_bulk_attempt_row', 'bulk_row_attempts', ['workspace_id', 'row_id', 'attempt_number'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_content_id'), 'bulk_row_attempts', ['content_id'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_content_version_id'), 'bulk_row_attempts', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_generation_job_id'), 'bulk_row_attempts', ['generation_job_id'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_job_id'), 'bulk_row_attempts', ['job_id'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_row_id'), 'bulk_row_attempts', ['row_id'], unique=False)
    op.create_index(op.f('ix_bulk_row_attempts_workspace_id'), 'bulk_row_attempts', ['workspace_id'], unique=False)
    op.create_foreign_key(
        'fk_media_asset_current_version',
        'media_assets',
        'media_versions',
        ['workspace_id', 'id', 'current_version_id'],
        ['workspace_id', 'asset_id', 'id'],
        ondelete='RESTRICT',
        deferrable=True,
        initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_media_asset_original_version',
        'media_assets',
        'media_versions',
        ['workspace_id', 'id', 'original_version_id'],
        ['workspace_id', 'asset_id', 'id'],
        ondelete='RESTRICT',
        deferrable=True,
        initially='DEFERRED',
    )
    op.create_foreign_key(
        'fk_media_license_current_revision',
        'media_licenses',
        'media_license_revisions',
        ['workspace_id', 'asset_id', 'current_revision_id'],
        ['workspace_id', 'asset_id', 'id'],
        ondelete='RESTRICT',
        deferrable=True,
        initially='DEFERRED',
    )
    for table_name in TENANT_TABLES:
        op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY')
        op.execute(
            f'''
            CREATE POLICY {table_name}_workspace_isolation ON {table_name}
            USING (workspace_id = app.current_workspace_id())
            WITH CHECK (workspace_id = app.current_workspace_id())
            '''
        )

    for table_name in IMMUTABLE_TABLES:
        op.execute(
            f'''
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
            '''
        )

    for table_name, columns in FROZEN_COLUMNS.items():
        changed = ' OR '.join(
            f'OLD.{column} IS DISTINCT FROM NEW.{column}' for column in columns
        )
        op.execute(
            f'''
            CREATE TRIGGER {table_name}_frozen_snapshot
            BEFORE UPDATE ON {table_name}
            FOR EACH ROW WHEN ({changed})
            EXECUTE FUNCTION app.reject_snapshot_update()
            '''
        )

    op.execute(
        f'''
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_app') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_app;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(TENANT_TABLES)} TO blogops_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_worker') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_worker;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(TENANT_TABLES)} TO blogops_worker;
            END IF;
        END
        $$
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_media_asset_current_version', 'media_assets', type_='foreignkey')
    op.drop_constraint('fk_media_asset_original_version', 'media_assets', type_='foreignkey')
    op.drop_constraint('fk_media_license_current_revision', 'media_licenses', type_='foreignkey')
    op.drop_index(op.f('ix_bulk_row_attempts_workspace_id'), table_name='bulk_row_attempts')
    op.drop_index(op.f('ix_bulk_row_attempts_row_id'), table_name='bulk_row_attempts')
    op.drop_index(op.f('ix_bulk_row_attempts_job_id'), table_name='bulk_row_attempts')
    op.drop_index(op.f('ix_bulk_row_attempts_generation_job_id'), table_name='bulk_row_attempts')
    op.drop_index(op.f('ix_bulk_row_attempts_content_version_id'), table_name='bulk_row_attempts')
    op.drop_index(op.f('ix_bulk_row_attempts_content_id'), table_name='bulk_row_attempts')
    op.drop_index('ix_bulk_attempt_row', table_name='bulk_row_attempts')
    op.drop_table('bulk_row_attempts')
    op.drop_index('ix_bulk_callback_state', table_name='bulk_callback_deliveries')
    op.drop_index(op.f('ix_bulk_callback_deliveries_workspace_id'), table_name='bulk_callback_deliveries')
    op.drop_index(op.f('ix_bulk_callback_deliveries_row_id'), table_name='bulk_callback_deliveries')
    op.drop_index(op.f('ix_bulk_callback_deliveries_job_id'), table_name='bulk_callback_deliveries')
    op.drop_table('bulk_callback_deliveries')
    op.drop_index(op.f('ix_bulk_rows_workspace_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_quality_assessment_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_job_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_generation_job_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_duplicate_of_row_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_content_version_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_content_id'), table_name='bulk_rows')
    op.drop_index(op.f('ix_bulk_rows_approval_request_id'), table_name='bulk_rows')
    op.drop_index('ix_bulk_row_state', table_name='bulk_rows')
    op.drop_index('ix_bulk_row_input_hash', table_name='bulk_rows')
    op.drop_index('ix_bulk_row_content', table_name='bulk_rows')
    op.drop_table('bulk_rows')
    op.drop_index(op.f('ix_media_plan_items_workspace_id'), table_name='media_plan_items')
    op.drop_index(op.f('ix_media_plan_items_selected_version_id'), table_name='media_plan_items')
    op.drop_index(op.f('ix_media_plan_items_selected_asset_id'), table_name='media_plan_items')
    op.drop_index(op.f('ix_media_plan_items_plan_id'), table_name='media_plan_items')
    op.drop_index('ix_media_plan_item_plan', table_name='media_plan_items')
    op.drop_table('media_plan_items')
    op.drop_index(op.f('ix_media_usages_workspace_id'), table_name='media_usages')
    op.drop_index(op.f('ix_media_usages_media_version_id'), table_name='media_usages')
    op.drop_index(op.f('ix_media_usages_license_revision_id'), table_name='media_usages')
    op.drop_index(op.f('ix_media_usages_content_version_id'), table_name='media_usages')
    op.drop_index(op.f('ix_media_usages_content_id'), table_name='media_usages')
    op.drop_index(op.f('ix_media_usages_asset_id'), table_name='media_usages')
    op.drop_index('ix_media_usage_content', table_name='media_usages')
    op.drop_index('ix_media_usage_asset', table_name='media_usages')
    op.drop_table('media_usages')
    op.drop_index(op.f('ix_media_plan_versions_workspace_id'), table_name='media_plan_versions')
    op.drop_index(op.f('ix_media_plan_versions_content_version_id'), table_name='media_plan_versions')
    op.drop_index(op.f('ix_media_plan_versions_content_id'), table_name='media_plan_versions')
    op.drop_index('ix_media_plan_content', table_name='media_plan_versions')
    op.drop_table('media_plan_versions')
    op.drop_index(op.f('ix_bulk_job_commands_workspace_id'), table_name='bulk_job_commands')
    op.drop_index(op.f('ix_bulk_job_commands_job_id'), table_name='bulk_job_commands')
    op.drop_index('ix_bulk_command_job', table_name='bulk_job_commands')
    op.drop_table('bulk_job_commands')
    op.drop_index('ix_bulk_export_job', table_name='bulk_export_artifacts')
    op.drop_index(op.f('ix_bulk_export_artifacts_workspace_id'), table_name='bulk_export_artifacts')
    op.drop_index(op.f('ix_bulk_export_artifacts_job_id'), table_name='bulk_export_artifacts')
    op.drop_table('bulk_export_artifacts')
    op.drop_index(op.f('ix_media_job_commands_workspace_id'), table_name='media_job_commands')
    op.drop_index(op.f('ix_media_job_commands_job_id'), table_name='media_job_commands')
    op.drop_index('ix_media_command_job', table_name='media_job_commands')
    op.drop_table('media_job_commands')
    op.drop_index(op.f('ix_bulk_schedules_workspace_id'), table_name='bulk_schedules')
    op.drop_index('ix_bulk_schedule_due', table_name='bulk_schedules')
    op.drop_table('bulk_schedules')
    op.drop_index(op.f('ix_bulk_jobs_workspace_id'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_template_version_id'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_requested_by'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_mapping_id'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_input_file_id'), table_name='bulk_jobs')
    op.drop_index(op.f('ix_bulk_jobs_campaign_id'), table_name='bulk_jobs')
    op.drop_index('ix_bulk_job_state', table_name='bulk_jobs')
    op.drop_index('ix_bulk_job_campaign', table_name='bulk_jobs')
    op.drop_table('bulk_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_workspace_id'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_source_version_id'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_source_asset_id'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_result_version_id'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_result_asset_id'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_requested_by'), table_name='media_operation_jobs')
    op.drop_index(op.f('ix_media_operation_jobs_provider_connection_id'), table_name='media_operation_jobs')
    op.drop_index('ix_media_job_state', table_name='media_operation_jobs')
    op.drop_table('media_operation_jobs')
    op.drop_index(op.f('ix_media_license_revisions_workspace_id'), table_name='media_license_revisions')
    op.drop_index(op.f('ix_media_license_revisions_license_id'), table_name='media_license_revisions')
    op.drop_index(op.f('ix_media_license_revisions_asset_id'), table_name='media_license_revisions')
    op.drop_index('ix_media_license_revision_asset', table_name='media_license_revisions')
    op.drop_table('media_license_revisions')
    op.drop_index(op.f('ix_media_inspections_workspace_id'), table_name='media_inspections')
    op.drop_index(op.f('ix_media_inspections_scan_result_id'), table_name='media_inspections')
    op.drop_index(op.f('ix_media_inspections_asset_id'), table_name='media_inspections')
    op.drop_index('ix_media_inspection_asset', table_name='media_inspections')
    op.drop_table('media_inspections')
    op.drop_index(op.f('ix_media_versions_workspace_id'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_parent_version_id'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_model_run_id'), table_name='media_versions')
    op.drop_index(op.f('ix_media_versions_asset_id'), table_name='media_versions')
    op.drop_index('ix_media_version_hash', table_name='media_versions')
    op.drop_index('ix_media_version_asset', table_name='media_versions')
    op.drop_table('media_versions')
    op.drop_index(op.f('ix_media_scan_results_workspace_id'), table_name='media_scan_results')
    op.drop_index(op.f('ix_media_scan_results_asset_id'), table_name='media_scan_results')
    op.drop_index('ix_media_scan_asset', table_name='media_scan_results')
    op.drop_table('media_scan_results')
    op.drop_index(op.f('ix_media_licenses_workspace_id'), table_name='media_licenses')
    op.drop_index(op.f('ix_media_licenses_valid_until'), table_name='media_licenses')
    op.drop_index(op.f('ix_media_licenses_current_revision_id'), table_name='media_licenses')
    op.drop_index(op.f('ix_media_licenses_asset_id'), table_name='media_licenses')
    op.drop_index('ix_media_license_expiry', table_name='media_licenses')
    op.drop_table('media_licenses')
    op.drop_index('ix_media_provider_state', table_name='media_provider_connections')
    op.drop_index(op.f('ix_media_provider_connections_workspace_id'), table_name='media_provider_connections')
    op.drop_table('media_provider_connections')
    op.drop_index(op.f('ix_media_assets_workspace_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_original_version_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_deleted_at'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_current_version_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_created_by'), table_name='media_assets')
    op.drop_index('ix_media_asset_state', table_name='media_assets')
    op.drop_index('ix_media_asset_original_hash', table_name='media_assets')
    op.drop_index('ix_media_asset_folder', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_bulk_mappings_workspace_id'), table_name='bulk_mappings')
    op.drop_index('ix_bulk_mapping_workspace_name', table_name='bulk_mappings')
    op.drop_table('bulk_mappings')
    op.drop_index('ix_bulk_input_workspace_time', table_name='bulk_input_files')
    op.drop_index(op.f('ix_bulk_input_files_workspace_id'), table_name='bulk_input_files')
    op.drop_table('bulk_input_files')
    op.drop_constraint(
        'quality_assessment_exact_identity',
        'quality_assessments',
        type_='unique',
    )
    op.drop_constraint(
        'content_version_exact_identity',
        'content_versions',
        type_='unique',
    )
    op.drop_constraint(
        'approval_request_exact_identity',
        'content_approval_requests',
        type_='unique',
    )
    # ### end Alembic commands ###
