"""quality approval

Revision ID: f56325b3586e
Revises: 4fd7a4ed3cfb
Create Date: 2026-08-23 13:54:45.355965
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f56325b3586e'
down_revision: str | None = '4fd7a4ed3cfb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TENANT_TABLES = (
    'content_approval_decisions',
    'content_approval_requests',
    'content_approval_state_events',
    'duplication_reports',
    'fact_citation_reports',
    'morphology_reports',
    'naturalness_reports',
    'policy_events',
    'quality_activity_events',
    'quality_assessment_reports',
    'quality_assessments',
    'quality_comments',
    'quality_mentions',
    'quality_policy_overrides',
    'quality_reports',
    'quality_rule_sets',
    'safety_policy_reports',
    'seo_reports',
    'workspace_quality_configs',
)

IMMUTABLE_TABLES = (
    'content_approval_decisions',
    'content_approval_state_events',
    'duplication_reports',
    'fact_citation_reports',
    'morphology_reports',
    'naturalness_reports',
    'policy_events',
    'quality_activity_events',
    'quality_assessment_reports',
    'quality_assessments',
    'quality_mentions',
    'quality_policy_overrides',
    'quality_reports',
    'quality_rule_sets',
    'safety_policy_reports',
    'seo_reports',
    'workspace_quality_configs',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'content_version_workspace_id_hash',
        'content_versions',
        ['workspace_id', 'id', 'content_hash'],
    )
    op.create_table('quality_rule_sets',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('layer', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzer_requirements_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version > 0', name=op.f('ck_quality_rule_sets_quality_rule_set_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_rule_sets')),
    sa.UniqueConstraint('workspace_id', 'id', name='quality_rule_set_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'layer', 'name', 'snapshot_hash', name='quality_rule_set_hash'),
    sa.UniqueConstraint('workspace_id', 'layer', 'name', 'version', name='quality_rule_set_version')
    )
    op.create_index('ix_quality_rule_sets_lookup', 'quality_rule_sets', ['workspace_id', 'layer', 'name', 'version'], unique=False)
    op.create_index(op.f('ix_quality_rule_sets_workspace_id'), 'quality_rule_sets', ['workspace_id'], unique=False)
    op.create_table('workspace_quality_configs',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('minimum_total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('minimum_component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_report_kinds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('threshold_override_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('minimum_total_score >= 0 AND minimum_total_score <= 100', name=op.f('ck_workspace_quality_configs_quality_config_total_range')),
    sa.CheckConstraint('version > 0', name=op.f('ck_workspace_quality_configs_quality_config_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_quality_configs')),
    sa.UniqueConstraint('workspace_id', 'config_hash', name='quality_config_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='quality_config_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'version', name='quality_config_version')
    )
    op.create_index('ix_quality_config_latest', 'workspace_quality_configs', ['workspace_id', 'version'], unique=False)
    op.create_index(op.f('ix_workspace_quality_configs_workspace_id'), 'workspace_quality_configs', ['workspace_id'], unique=False)
    op.create_table('quality_activity_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('content_version_id', sa.Uuid(), nullable=True),
    sa.Column('activity_kind', sa.String(length=48), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_quality_activity_events_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_quality_activity_events_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_activity_events'))
    )
    op.create_index('ix_quality_activity_content_time', 'quality_activity_events', ['workspace_id', 'content_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quality_activity_events_content_id'), 'quality_activity_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_quality_activity_events_content_version_id'), 'quality_activity_events', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_quality_activity_events_target_id'), 'quality_activity_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_quality_activity_events_workspace_id'), 'quality_activity_events', ['workspace_id'], unique=False)
    op.create_index('ix_quality_activity_workspace_time', 'quality_activity_events', ['workspace_id', 'created_at'], unique=False)
    op.create_table('quality_assessments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_config_id', sa.Uuid(), nullable=False),
    sa.Column('quality_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_config_hash', sa.String(length=64), nullable=False),
    sa.Column('report_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('component_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weighted_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('formula_version', sa.String(length=40), nullable=False),
    sa.Column('failed_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_policy_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('non_overrideable_policy_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('assessment_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('total_score >= 0 AND total_score <= 100', name=op.f('ck_quality_assessments_quality_assessment_total_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_quality_assessments_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_quality_assessment_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'quality_config_id'], ['workspace_quality_configs.workspace_id', 'workspace_quality_configs.id'], name=op.f('fk_quality_assessments_workspace_id_workspace_quality_configs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_assessments')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'assessment_hash', name='quality_assessment_version_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='quality_assessment_workspace_id')
    )
    op.create_index('ix_quality_assessment_content_version', 'quality_assessments', ['workspace_id', 'content_version_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quality_assessments_content_id'), 'quality_assessments', ['content_id'], unique=False)
    op.create_index(op.f('ix_quality_assessments_content_version_id'), 'quality_assessments', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_quality_assessments_workspace_id'), 'quality_assessments', ['workspace_id'], unique=False)
    op.create_table('quality_comments',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=True),
    sa.Column('content_version_id', sa.Uuid(), nullable=True),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_quality_comments_quality_comment_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_quality_comments_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id'], ['content_versions.workspace_id', 'content_versions.id'], name=op.f('fk_quality_comments_workspace_id_content_versions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'parent_comment_id'], ['quality_comments.workspace_id', 'quality_comments.id'], name=op.f('fk_quality_comments_workspace_id_quality_comments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_comments')),
    sa.UniqueConstraint('workspace_id', 'id', name='quality_comment_workspace_id')
    )
    op.create_index('ix_quality_comment_target', 'quality_comments', ['workspace_id', 'target_type', 'target_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quality_comments_content_id'), 'quality_comments', ['content_id'], unique=False)
    op.create_index(op.f('ix_quality_comments_content_version_id'), 'quality_comments', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_quality_comments_parent_comment_id'), 'quality_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_quality_comments_target_id'), 'quality_comments', ['target_id'], unique=False)
    op.create_index(op.f('ix_quality_comments_workspace_id'), 'quality_comments', ['workspace_id'], unique=False)
    op.create_table('quality_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('report_kind', sa.String(length=32), nullable=False),
    sa.Column('analyzer_name', sa.String(length=120), nullable=False),
    sa.Column('analyzer_version', sa.String(length=80), nullable=False),
    sa.Column('model_name', sa.String(length=160), nullable=True),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('dictionary_name', sa.String(length=160), nullable=True),
    sa.Column('dictionary_version', sa.String(length=120), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('analyzer_config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzer_config_hash', sa.String(length=64), nullable=False),
    sa.Column('rule_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('findings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hard_blockers_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_quality_reports_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_quality_report_exact_content_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_reports')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'report_kind', 'report_hash', name='quality_report_version_kind_hash'),
    sa.UniqueConstraint('workspace_id', 'id', name='quality_report_workspace_id')
    )
    op.create_index('ix_quality_report_content_version', 'quality_reports', ['workspace_id', 'content_version_id', 'report_kind', 'created_at'], unique=False)
    op.create_index(op.f('ix_quality_reports_content_id'), 'quality_reports', ['content_id'], unique=False)
    op.create_index(op.f('ix_quality_reports_content_version_id'), 'quality_reports', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_quality_reports_workspace_id'), 'quality_reports', ['workspace_id'], unique=False)
    op.create_table('content_approval_requests',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_hash', sa.String(length=64), nullable=False),
    sa.Column('quality_config_id', sa.Uuid(), nullable=False),
    sa.Column('quality_config_hash', sa.String(length=64), nullable=False),
    sa.Column('approval_stages_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_stages_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_request_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_content_version_id', sa.Uuid(), nullable=True),
    sa.Column('approved_content_hash', sa.String(length=64), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_by', sa.Uuid(), nullable=True),
    sa.Column('invalidation_reason', sa.Text(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_stage_index >= 0', name=op.f('ck_content_approval_requests_approval_stage_index_nonnegative')),
    sa.CheckConstraint('lock_version > 0', name=op.f('ck_content_approval_requests_approval_request_lock_positive')),
    sa.ForeignKeyConstraint(['workspace_id', 'approved_content_version_id', 'approved_content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_approval_request_approved_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'assessment_id'], ['quality_assessments.workspace_id', 'quality_assessments.id'], name=op.f('fk_content_approval_requests_workspace_id_quality_assessments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_content_approval_requests_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_approval_request_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'quality_config_id'], ['workspace_quality_configs.workspace_id', 'workspace_quality_configs.id'], name=op.f('fk_content_approval_requests_workspace_id_workspace_quality_configs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'supersedes_request_id'], ['content_approval_requests.workspace_id', 'content_approval_requests.id'], name=op.f('fk_content_approval_requests_workspace_id_content_approval_requests'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_approval_requests')),
    sa.UniqueConstraint('workspace_id', 'content_version_id', 'assessment_id', name='approval_request_version_assessment'),
    sa.UniqueConstraint('workspace_id', 'id', name='approval_request_workspace_id')
    )
    op.create_index('ix_approval_request_content', 'content_approval_requests', ['workspace_id', 'content_id', 'status'], unique=False)
    op.create_index(op.f('ix_content_approval_requests_content_id'), 'content_approval_requests', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_approval_requests_content_version_id'), 'content_approval_requests', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_content_approval_requests_supersedes_request_id'), 'content_approval_requests', ['supersedes_request_id'], unique=False)
    op.create_index(op.f('ix_content_approval_requests_workspace_id'), 'content_approval_requests', ['workspace_id'], unique=False)
    op.create_table('duplication_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('originality_score', sa.Float(), nullable=False),
    sa.Column('duplicate_ratio', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=120), nullable=False),
    sa.Column('algorithm_version', sa.String(length=80), nullable=False),
    sa.Column('corpus_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('near_duplicates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cannibalization_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('duplicate_ratio >= 0 AND duplicate_ratio <= 1', name=op.f('ck_duplication_reports_duplication_ratio_range')),
    sa.CheckConstraint('originality_score >= 0 AND originality_score <= 100', name=op.f('ck_duplication_reports_duplication_originality_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_duplication_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duplication_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='duplication_report_parent')
    )
    op.create_index(op.f('ix_duplication_reports_report_id'), 'duplication_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_duplication_reports_workspace_id'), 'duplication_reports', ['workspace_id'], unique=False)
    op.create_table('fact_citation_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('supported_claim_count', sa.Integer(), nullable=False),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('linked_citation_count', sa.Integer(), nullable=False),
    sa.Column('citation_link_rate', sa.Float(), nullable=False),
    sa.Column('claim_citation_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unsupported_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalid_citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('accuracy_score >= 0 AND accuracy_score <= 100', name=op.f('ck_fact_citation_reports_fact_citation_accuracy_range')),
    sa.CheckConstraint('citation_link_rate >= 0 AND citation_link_rate <= 100', name=op.f('ck_fact_citation_reports_fact_citation_link_rate_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_fact_citation_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fact_citation_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='fact_citation_report_parent')
    )
    op.create_index(op.f('ix_fact_citation_reports_report_id'), 'fact_citation_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_fact_citation_reports_workspace_id'), 'fact_citation_reports', ['workspace_id'], unique=False)
    op.create_table('morphology_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('sentence_count', sa.Integer(), nullable=False),
    sa.Column('unknown_token_rate', sa.Float(), nullable=False),
    sa.Column('spacing_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammar_issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_morphology_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_morphology_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='morphology_report_parent')
    )
    op.create_index(op.f('ix_morphology_reports_report_id'), 'morphology_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_morphology_reports_workspace_id'), 'morphology_reports', ['workspace_id'], unique=False)
    op.create_table('naturalness_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('naturalness_score', sa.Float(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('brand_fit_score', sa.Float(), nullable=False),
    sa.Column('fluency_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sentence_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('awkward_expressions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('naturalness_score >= 0 AND naturalness_score <= 100', name=op.f('ck_naturalness_reports_naturalness_score_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_naturalness_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_naturalness_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='naturalness_report_parent')
    )
    op.create_index(op.f('ix_naturalness_reports_report_id'), 'naturalness_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_naturalness_reports_workspace_id'), 'naturalness_reports', ['workspace_id'], unique=False)
    op.create_table('policy_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('event_key', sa.String(length=160), nullable=False),
    sa.Column('layer', sa.String(length=24), nullable=False),
    sa.Column('rule_code', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('hard_block', sa.Boolean(), nullable=False),
    sa.Column('override_allowed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('policy_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'assessment_id'], ['quality_assessments.workspace_id', 'quality_assessments.id'], name=op.f('fk_policy_events_workspace_id_quality_assessments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_id'], ['contents.workspace_id', 'contents.id'], name=op.f('fk_policy_events_workspace_id_contents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_policy_event_exact_content_version', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_policy_events_workspace_id_quality_reports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_events')),
    sa.UniqueConstraint('workspace_id', 'id', name='policy_event_workspace_id'),
    sa.UniqueConstraint('workspace_id', 'report_id', 'event_key', name='policy_event_report_key')
    )
    op.create_index('ix_policy_event_content_version', 'policy_events', ['workspace_id', 'content_version_id', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_policy_events_assessment_id'), 'policy_events', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_policy_events_content_id'), 'policy_events', ['content_id'], unique=False)
    op.create_index(op.f('ix_policy_events_content_version_id'), 'policy_events', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_policy_events_report_id'), 'policy_events', ['report_id'], unique=False)
    op.create_index(op.f('ix_policy_events_workspace_id'), 'policy_events', ['workspace_id'], unique=False)
    op.create_table('quality_assessment_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('report_kind', sa.String(length=32), nullable=False),
    sa.Column('report_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'assessment_id'], ['quality_assessments.workspace_id', 'quality_assessments.id'], name=op.f('fk_quality_assessment_reports_workspace_id_quality_assessments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_quality_assessment_reports_workspace_id_quality_reports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_assessment_reports')),
    sa.UniqueConstraint('workspace_id', 'assessment_id', 'report_kind', name='quality_assessment_report_kind')
    )
    op.create_index(op.f('ix_quality_assessment_reports_assessment_id'), 'quality_assessment_reports', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_quality_assessment_reports_report_id'), 'quality_assessment_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_quality_assessment_reports_workspace_id'), 'quality_assessment_reports', ['workspace_id'], unique=False)
    op.create_table('quality_mentions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('mentioned_user_id', sa.Uuid(), nullable=False),
    sa.Column('mentioned_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'comment_id'], ['quality_comments.workspace_id', 'quality_comments.id'], name=op.f('fk_quality_mentions_workspace_id_quality_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_mentions')),
    sa.UniqueConstraint('workspace_id', 'comment_id', 'mentioned_user_id', name='quality_mention_user')
    )
    op.create_index(op.f('ix_quality_mentions_comment_id'), 'quality_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_quality_mentions_mentioned_user_id'), 'quality_mentions', ['mentioned_user_id'], unique=False)
    op.create_index(op.f('ix_quality_mentions_workspace_id'), 'quality_mentions', ['workspace_id'], unique=False)
    op.create_table('safety_policy_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('policy_findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_disclosures', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banned_claim_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('compliance_score >= 0 AND compliance_score <= 100', name=op.f('ck_safety_policy_reports_safety_compliance_score_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_safety_policy_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_policy_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='safety_policy_report_parent')
    )
    op.create_index(op.f('ix_safety_policy_reports_report_id'), 'safety_policy_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_safety_policy_reports_workspace_id'), 'safety_policy_reports', ['workspace_id'], unique=False)
    op.create_table('seo_reports',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('search_intent_score', sa.Float(), nullable=False),
    sa.Column('primary_keyword', sa.String(length=1000), nullable=True),
    sa.Column('keyword_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('heading_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('meta_checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('search_intent_score >= 0 AND search_intent_score <= 100', name=op.f('ck_seo_reports_seo_intent_score_range')),
    sa.ForeignKeyConstraint(['workspace_id', 'report_id'], ['quality_reports.workspace_id', 'quality_reports.id'], name=op.f('fk_seo_reports_workspace_id_quality_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_reports')),
    sa.UniqueConstraint('workspace_id', 'report_id', name='seo_report_parent')
    )
    op.create_index(op.f('ix_seo_reports_report_id'), 'seo_reports', ['report_id'], unique=False)
    op.create_index(op.f('ix_seo_reports_workspace_id'), 'seo_reports', ['workspace_id'], unique=False)
    op.create_table('content_approval_decisions',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('stage_key', sa.String(length=80), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=False),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('authentication_method', sa.String(length=40), nullable=False),
    sa.Column('decided_by', sa.Uuid(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'approval_request_id'], ['content_approval_requests.workspace_id', 'content_approval_requests.id'], name=op.f('fk_content_approval_decisions_workspace_id_content_approval_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_approval_decision_exact_content_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_approval_decisions')),
    sa.UniqueConstraint('workspace_id', 'approval_request_id', 'stage_key', 'decided_by', name='approval_decision_actor_stage')
    )
    op.create_index('ix_approval_decision_timeline', 'content_approval_decisions', ['workspace_id', 'approval_request_id', 'decided_at'], unique=False)
    op.create_index(op.f('ix_content_approval_decisions_approval_request_id'), 'content_approval_decisions', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_content_approval_decisions_workspace_id'), 'content_approval_decisions', ['workspace_id'], unique=False)
    op.create_table('content_approval_state_events',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'approval_request_id'], ['content_approval_requests.workspace_id', 'content_approval_requests.id'], name=op.f('fk_content_approval_state_events_workspace_id_content_approval_requests'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id', 'content_version_id', 'content_hash'], ['content_versions.workspace_id', 'content_versions.id', 'content_versions.content_hash'], name='fk_approval_state_event_exact_content_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_approval_state_events'))
    )
    op.create_index('ix_approval_state_event_timeline', 'content_approval_state_events', ['workspace_id', 'approval_request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_content_approval_state_events_approval_request_id'), 'content_approval_state_events', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_content_approval_state_events_workspace_id'), 'content_approval_state_events', ['workspace_id'], unique=False)
    op.create_table('quality_policy_overrides',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('policy_event_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('event_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('overridden_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id', 'policy_event_id'], ['policy_events.workspace_id', 'policy_events.id'], name=op.f('fk_quality_policy_overrides_workspace_id_policy_events'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_policy_overrides')),
    sa.UniqueConstraint('workspace_id', 'policy_event_id', name='quality_policy_override_event')
    )
    op.create_index(op.f('ix_quality_policy_overrides_policy_event_id'), 'quality_policy_overrides', ['policy_event_id'], unique=False)
    op.create_index(op.f('ix_quality_policy_overrides_workspace_id'), 'quality_policy_overrides', ['workspace_id'], unique=False)
    for table_name in TENANT_TABLES:
        op.execute(f'ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY')
        op.execute(
            f'''
            CREATE POLICY {table_name}_workspace_isolation ON {table_name}
            USING (workspace_id = app.current_workspace_id())
            WITH CHECK (workspace_id = app.current_workspace_id())
            '''
        )

    for table_name in IMMUTABLE_TABLES:
        op.execute(
            f'''
            CREATE TRIGGER {table_name}_immutable
            BEFORE UPDATE OR DELETE ON {table_name}
            FOR EACH ROW EXECUTE FUNCTION app.reject_snapshot_update()
            '''
        )

    op.execute(
        f'''
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_app') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_app;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(TENANT_TABLES)} TO blogops_app;
            END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'blogops_worker') THEN
                GRANT USAGE ON SCHEMA public, app TO blogops_worker;
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON {', '.join(TENANT_TABLES)} TO blogops_worker;
            END IF;
        END
        $$
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_policy_overrides_workspace_id'), table_name='quality_policy_overrides')
    op.drop_index(op.f('ix_quality_policy_overrides_policy_event_id'), table_name='quality_policy_overrides')
    op.drop_table('quality_policy_overrides')
    op.drop_index(op.f('ix_content_approval_state_events_workspace_id'), table_name='content_approval_state_events')
    op.drop_index(op.f('ix_content_approval_state_events_approval_request_id'), table_name='content_approval_state_events')
    op.drop_index('ix_approval_state_event_timeline', table_name='content_approval_state_events')
    op.drop_table('content_approval_state_events')
    op.drop_index(op.f('ix_content_approval_decisions_workspace_id'), table_name='content_approval_decisions')
    op.drop_index(op.f('ix_content_approval_decisions_approval_request_id'), table_name='content_approval_decisions')
    op.drop_index('ix_approval_decision_timeline', table_name='content_approval_decisions')
    op.drop_table('content_approval_decisions')
    op.drop_index(op.f('ix_seo_reports_workspace_id'), table_name='seo_reports')
    op.drop_index(op.f('ix_seo_reports_report_id'), table_name='seo_reports')
    op.drop_table('seo_reports')
    op.drop_index(op.f('ix_safety_policy_reports_workspace_id'), table_name='safety_policy_reports')
    op.drop_index(op.f('ix_safety_policy_reports_report_id'), table_name='safety_policy_reports')
    op.drop_table('safety_policy_reports')
    op.drop_index(op.f('ix_quality_mentions_workspace_id'), table_name='quality_mentions')
    op.drop_index(op.f('ix_quality_mentions_mentioned_user_id'), table_name='quality_mentions')
    op.drop_index(op.f('ix_quality_mentions_comment_id'), table_name='quality_mentions')
    op.drop_table('quality_mentions')
    op.drop_index(op.f('ix_quality_assessment_reports_workspace_id'), table_name='quality_assessment_reports')
    op.drop_index(op.f('ix_quality_assessment_reports_report_id'), table_name='quality_assessment_reports')
    op.drop_index(op.f('ix_quality_assessment_reports_assessment_id'), table_name='quality_assessment_reports')
    op.drop_table('quality_assessment_reports')
    op.drop_index(op.f('ix_policy_events_workspace_id'), table_name='policy_events')
    op.drop_index(op.f('ix_policy_events_report_id'), table_name='policy_events')
    op.drop_index(op.f('ix_policy_events_content_version_id'), table_name='policy_events')
    op.drop_index(op.f('ix_policy_events_content_id'), table_name='policy_events')
    op.drop_index(op.f('ix_policy_events_assessment_id'), table_name='policy_events')
    op.drop_index('ix_policy_event_content_version', table_name='policy_events')
    op.drop_table('policy_events')
    op.drop_index(op.f('ix_naturalness_reports_workspace_id'), table_name='naturalness_reports')
    op.drop_index(op.f('ix_naturalness_reports_report_id'), table_name='naturalness_reports')
    op.drop_table('naturalness_reports')
    op.drop_index(op.f('ix_morphology_reports_workspace_id'), table_name='morphology_reports')
    op.drop_index(op.f('ix_morphology_reports_report_id'), table_name='morphology_reports')
    op.drop_table('morphology_reports')
    op.drop_index(op.f('ix_fact_citation_reports_workspace_id'), table_name='fact_citation_reports')
    op.drop_index(op.f('ix_fact_citation_reports_report_id'), table_name='fact_citation_reports')
    op.drop_table('fact_citation_reports')
    op.drop_index(op.f('ix_duplication_reports_workspace_id'), table_name='duplication_reports')
    op.drop_index(op.f('ix_duplication_reports_report_id'), table_name='duplication_reports')
    op.drop_table('duplication_reports')
    op.drop_index(op.f('ix_content_approval_requests_workspace_id'), table_name='content_approval_requests')
    op.drop_index(op.f('ix_content_approval_requests_supersedes_request_id'), table_name='content_approval_requests')
    op.drop_index(op.f('ix_content_approval_requests_content_version_id'), table_name='content_approval_requests')
    op.drop_index(op.f('ix_content_approval_requests_content_id'), table_name='content_approval_requests')
    op.drop_index('ix_approval_request_content', table_name='content_approval_requests')
    op.drop_table('content_approval_requests')
    op.drop_index(op.f('ix_quality_reports_workspace_id'), table_name='quality_reports')
    op.drop_index(op.f('ix_quality_reports_content_version_id'), table_name='quality_reports')
    op.drop_index(op.f('ix_quality_reports_content_id'), table_name='quality_reports')
    op.drop_index('ix_quality_report_content_version', table_name='quality_reports')
    op.drop_table('quality_reports')
    op.drop_index(op.f('ix_quality_comments_workspace_id'), table_name='quality_comments')
    op.drop_index(op.f('ix_quality_comments_target_id'), table_name='quality_comments')
    op.drop_index(op.f('ix_quality_comments_parent_comment_id'), table_name='quality_comments')
    op.drop_index(op.f('ix_quality_comments_content_version_id'), table_name='quality_comments')
    op.drop_index(op.f('ix_quality_comments_content_id'), table_name='quality_comments')
    op.drop_index('ix_quality_comment_target', table_name='quality_comments')
    op.drop_table('quality_comments')
    op.drop_index(op.f('ix_quality_assessments_workspace_id'), table_name='quality_assessments')
    op.drop_index(op.f('ix_quality_assessments_content_version_id'), table_name='quality_assessments')
    op.drop_index(op.f('ix_quality_assessments_content_id'), table_name='quality_assessments')
    op.drop_index('ix_quality_assessment_content_version', table_name='quality_assessments')
    op.drop_table('quality_assessments')
    op.drop_index('ix_quality_activity_workspace_time', table_name='quality_activity_events')
    op.drop_index(op.f('ix_quality_activity_events_workspace_id'), table_name='quality_activity_events')
    op.drop_index(op.f('ix_quality_activity_events_target_id'), table_name='quality_activity_events')
    op.drop_index(op.f('ix_quality_activity_events_content_version_id'), table_name='quality_activity_events')
    op.drop_index(op.f('ix_quality_activity_events_content_id'), table_name='quality_activity_events')
    op.drop_index('ix_quality_activity_content_time', table_name='quality_activity_events')
    op.drop_table('quality_activity_events')
    op.drop_index(op.f('ix_workspace_quality_configs_workspace_id'), table_name='workspace_quality_configs')
    op.drop_index('ix_quality_config_latest', table_name='workspace_quality_configs')
    op.drop_table('workspace_quality_configs')
    op.drop_index(op.f('ix_quality_rule_sets_workspace_id'), table_name='quality_rule_sets')
    op.drop_index('ix_quality_rule_sets_lookup', table_name='quality_rule_sets')
    op.drop_table('quality_rule_sets')
    op.drop_constraint(
        'content_version_workspace_id_hash',
        'content_versions',
        type_='unique',
    )
    # ### end Alembic commands ###
