"""Platform operations vocabulary."""

from enum import StrEnum


class ComponentKind(StrEnum):
    API = "API"
    QUEUE = "QUEUE"
    DATABASE = "DATABASE"
    STORAGE = "STORAGE"
    SEARCH = "SEARCH"
    MODEL_PROVIDER = "MODEL_PROVIDER"
    CONNECTOR = "CONNECTOR"


class HealthStatus(StrEnum):
    OPERATIONAL = "OPERATIONAL"
    DEGRADED = "DEGRADED"
    MAJOR_OUTAGE = "MAJOR_OUTAGE"
    MAINTENANCE = "MAINTENANCE"
    UNKNOWN = "UNKNOWN"


class OperationalIncidentState(StrEnum):
    INVESTIGATING = "INVESTIGATING"
    IDENTIFIED = "IDENTIFIED"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"


class OperationalIncidentEventKind(StrEnum):
    OPENED = "OPENED"
    UPDATE = "UPDATE"
    MITIGATION = "MITIGATION"
    CUSTOMER_NOTICE = "CUSTOMER_NOTICE"
    RESOLVED = "RESOLVED"


class BackupRunState(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    VERIFYING = "VERIFYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class RecoveryExerciseState(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    RETRYING = "RETRYING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class GAAssessmentState(StrEnum):
    QUEUED = "QUEUED"
    VERIFYING = "VERIFYING"
    RETRYING = "RETRYING"
    PASSED = "PASSED"
    BLOCKED = "BLOCKED"
    FAILED = "FAILED"


class GAGate(StrEnum):
    C0_C1_AUTOMATION = "C0_C1_AUTOMATION"
    SECURITY_FINDINGS = "SECURITY_FINDINGS"
    TENANT_ISOLATION = "TENANT_ISOLATION"
    BILLING_LEDGER = "BILLING_LEDGER"
    PUBLISHING_IDEMPOTENCY = "PUBLISHING_IDEMPOTENCY"
    BACKUP_RESTORE = "BACKUP_RESTORE"
    DATA_LIFECYCLE = "DATA_LIFECYCLE"
    POLICY_LEGAL_REVIEW = "POLICY_LEGAL_REVIEW"
    LOAD_CHAOS = "LOAD_CHAOS"
    RUNBOOK_ONCALL_ALERTS = "RUNBOOK_ONCALL_ALERTS"
