"""Stable vocabulary for tenant-owned media assets and image workflows."""

from enum import StrEnum


class MediaAssetState(StrEnum):
    AWAITING_UPLOAD = "AWAITING_UPLOAD"
    QUARANTINED = "QUARANTINED"
    SCANNING = "SCANNING"
    INSPECTING = "INSPECTING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY = "READY"
    BLOCKED = "BLOCKED"
    DELETED = "DELETED"


class MediaOrigin(StrEnum):
    USER_UPLOAD = "USER_UPLOAD"
    STOCK_IMPORT = "STOCK_IMPORT"
    PROVIDER_IMPORT = "PROVIDER_IMPORT"
    AI_GENERATED = "AI_GENERATED"


class MediaVersionKind(StrEnum):
    ORIGINAL = "ORIGINAL"
    DERIVED = "DERIVED"


class MediaOperation(StrEnum):
    TEXT_TO_IMAGE = "TEXT_TO_IMAGE"
    REFERENCE_EDIT = "REFERENCE_EDIT"
    BACKGROUND_REMOVE = "BACKGROUND_REMOVE"
    BACKGROUND_REPLACE = "BACKGROUND_REPLACE"
    OBJECT_REMOVE = "OBJECT_REMOVE"
    OUTPAINT = "OUTPAINT"
    COLOR_ADJUST = "COLOR_ADJUST"
    UPSCALE = "UPSCALE"
    THUMBNAIL = "THUMBNAIL"
    CARD_NEWS = "CARD_NEWS"
    INFOGRAPHIC = "INFOGRAPHIC"
    SPLIT = "SPLIT"
    WATERMARK = "WATERMARK"
    STOCK_SEARCH = "STOCK_SEARCH"
    STOCK_IMPORT = "STOCK_IMPORT"
    ALT_CAPTION = "ALT_CAPTION"
    CHANNEL_CONVERT = "CHANNEL_CONVERT"


class MediaProviderState(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    CREDENTIAL_EXPIRED = "CREDENTIAL_EXPIRED"
    LICENSE_EXPIRED = "LICENSE_EXPIRED"
    CIRCUIT_OPEN = "CIRCUIT_OPEN"


class MalwareScanStatus(StrEnum):
    CLEAN = "CLEAN"
    INFECTED = "INFECTED"
    UNAVAILABLE = "UNAVAILABLE"


class InspectionStatus(StrEnum):
    SAFE = "SAFE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BLOCKED = "BLOCKED"
    UNAVAILABLE = "UNAVAILABLE"


class ExifPolicy(StrEnum):
    REMOVE_PRIVATE = "REMOVE_PRIVATE"
    REMOVE_ALL = "REMOVE_ALL"
    PRESERVE_NON_PRIVATE = "PRESERVE_NON_PRIVATE"


class LicenseType(StrEnum):
    OWNED = "OWNED"
    STOCK = "STOCK"
    AI_GENERATED = "AI_GENERATED"
    THIRD_PARTY = "THIRD_PARTY"
    PUBLIC_DOMAIN = "PUBLIC_DOMAIN"


class LicenseState(StrEnum):
    ACTIVE = "ACTIVE"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    EXPIRED = "EXPIRED"
    REVOKED = "REVOKED"


class UsageMode(StrEnum):
    INTERNAL = "INTERNAL"
    EDITORIAL = "EDITORIAL"
    COMMERCIAL = "COMMERCIAL"


class ImagePlanStatus(StrEnum):
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"


class ImageNeedKind(StrEnum):
    COVER = "COVER"
    SECTION = "SECTION"
    REAL_PHOTO_EVIDENCE = "REAL_PHOTO_EVIDENCE"
    DATA_VISUALIZATION = "DATA_VISUALIZATION"
    QUOTED_SOURCE = "QUOTED_SOURCE"
    DECORATIVE = "DECORATIVE"


class ImageSelectionState(StrEnum):
    PROPOSED = "PROPOSED"
    SELECTED = "SELECTED"
    REJECTED = "REJECTED"


AI_ORIGINS = frozenset({MediaOrigin.AI_GENERATED})
