"""Security, privacy, and copyright vocabulary."""

from enum import StrEnum


class DataClass(StrEnum):
    ACCOUNT = "ACCOUNT"
    CONTENT = "CONTENT"
    KNOWLEDGE = "KNOWLEDGE"
    MEDIA = "MEDIA"
    SEARCH_INDEX = "SEARCH_INDEX"
    VECTOR = "VECTOR"
    ANALYTICS = "ANALYTICS"
    CREDENTIAL = "CREDENTIAL"
    AUDIT = "AUDIT"
    BILLING = "BILLING"
    BACKUP = "BACKUP"


class PrivacyRequestKind(StrEnum):
    ACCESS = "ACCESS"
    EXPORT = "EXPORT"
    CORRECT = "CORRECT"
    DELETE = "DELETE"
    RESTRICT_PROCESSING = "RESTRICT_PROCESSING"


class PrivacyRequestState(StrEnum):
    IDENTITY_PENDING = "IDENTITY_PENDING"
    VERIFIED = "VERIFIED"
    ON_HOLD = "ON_HOLD"
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    PARTIAL = "PARTIAL"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class VerificationOutcome(StrEnum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    EXPIRED = "EXPIRED"


class PrivacyActionKind(StrEnum):
    EXPORT = "EXPORT"
    CORRECT = "CORRECT"
    DELETE_DATABASE = "DELETE_DATABASE"
    DELETE_SEARCH = "DELETE_SEARCH"
    DELETE_VECTOR = "DELETE_VECTOR"
    DELETE_OBJECTS = "DELETE_OBJECTS"
    REVOKE_CREDENTIALS = "REVOKE_CREDENTIALS"
    ANONYMIZE_ANALYTICS = "ANONYMIZE_ANALYTICS"
    RESTRICT_PROCESSING = "RESTRICT_PROCESSING"
    SCHEDULE_BACKUP_ERASURE = "SCHEDULE_BACKUP_ERASURE"


class PrivacyActionState(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    SKIPPED_LEGAL_HOLD = "SKIPPED_LEGAL_HOLD"
    FAILED = "FAILED"


class LegalHoldState(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"


class LegalHoldEventKind(StrEnum):
    ACTIVATED = "ACTIVATED"
    SCOPE_EXTENDED = "SCOPE_EXTENDED"
    RELEASED = "RELEASED"


class RetentionSweepState(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"


class ConsentPurpose(StrEnum):
    TERMS = "TERMS"
    MARKETING = "MARKETING"
    AI_PROCESSING = "AI_PROCESSING"
    MODEL_TRAINING = "MODEL_TRAINING"
    CROSS_BORDER_TRANSFER = "CROSS_BORDER_TRANSFER"
    DPA = "DPA"
    AGE_ATTESTATION = "AGE_ATTESTATION"


class ConsentDecision(StrEnum):
    GRANTED = "GRANTED"
    WITHDRAWN = "WITHDRAWN"


class CopyrightCaseState(StrEnum):
    RECEIVED = "RECEIVED"
    VALIDATING = "VALIDATING"
    TEMPORARY_ACTION = "TEMPORARY_ACTION"
    WAITING_COUNTER_NOTICE = "WAITING_COUNTER_NOTICE"
    LEGAL_REVIEW = "LEGAL_REVIEW"
    RESTORED = "RESTORED"
    REMOVED = "REMOVED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class CopyrightEventKind(StrEnum):
    NOTICE_RECEIVED = "NOTICE_RECEIVED"
    VALIDATED = "VALIDATED"
    TEMPORARY_ACTION_APPLIED = "TEMPORARY_ACTION_APPLIED"
    COUNTER_NOTICE_RECEIVED = "COUNTER_NOTICE_RECEIVED"
    LEGAL_REVIEWED = "LEGAL_REVIEWED"
    CONTENT_RESTORED = "CONTENT_RESTORED"
    CONTENT_REMOVED = "CONTENT_REMOVED"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class SecurityIncidentSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class SecurityIncidentState(StrEnum):
    DETECTED = "DETECTED"
    TRIAGED = "TRIAGED"
    CONTAINING = "CONTAINING"
    CONTAINED = "CONTAINED"
    RECOVERING = "RECOVERING"
    MONITORING = "MONITORING"
    RESOLVED = "RESOLVED"


class SecurityIncidentEventKind(StrEnum):
    DETECTED = "DETECTED"
    TRIAGE = "TRIAGE"
    CONTAINMENT = "CONTAINMENT"
    EVIDENCE = "EVIDENCE"
    IMPACT_CHANGED = "IMPACT_CHANGED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    RECOVERY = "RECOVERY"
    RESOLVED = "RESOLVED"


class NotificationAudience(StrEnum):
    DATA_SUBJECT = "DATA_SUBJECT"
    WORKSPACE = "WORKSPACE"
    REGULATOR = "REGULATOR"
    SUBPROCESSOR = "SUBPROCESSOR"


class ComplianceAssessmentKind(StrEnum):
    DPIA = "DPIA"
    PENETRATION_TEST = "PENETRATION_TEST"
    DEPENDENCY_SCAN = "DEPENDENCY_SCAN"
    SBOM = "SBOM"
    CONTAINER_SCAN = "CONTAINER_SCAN"
    TENANT_ISOLATION = "TENANT_ISOLATION"
    CHILD_DATA_REVIEW = "CHILD_DATA_REVIEW"


class ComplianceDecision(StrEnum):
    PASSED = "PASSED"
    BLOCKED = "BLOCKED"
    EXPIRED = "EXPIRED"
