"""Stable generation vocabulary derived from the functional specification."""

from enum import StrEnum


class ContentType(StrEnum):
    INFORMATIONAL = "INFORMATIONAL"
    INFORMATIONAL_V2 = "INFORMATIONAL_V2"
    NAVER_HOME_FEED = "NAVER_HOME_FEED"
    PROBLEM_SOLUTION = "PROBLEM_SOLUTION"
    GUIDE_TUTORIAL = "GUIDE_TUTORIAL"
    FAQ = "FAQ"
    LISTICLE = "LISTICLE"
    COMPARISON = "COMPARISON"
    DEFINITION_GLOSSARY = "DEFINITION_GLOSSARY"
    LOCAL_INFORMATION = "LOCAL_INFORMATION"
    PRODUCT_EXPERIENCE_REVIEW = "PRODUCT_EXPERIENCE_REVIEW"
    VISIT_REVIEW = "VISIT_REVIEW"
    TRAVEL_REVIEW = "TRAVEL_REVIEW"
    SPONSORED_REVIEW_BRIEF = "SPONSORED_REVIEW_BRIEF"
    PROS_CONS_REVIEW = "PROS_CONS_REVIEW"
    REPURCHASE_REVIEW = "REPURCHASE_REVIEW"
    SPONSORED_DISCLOSURE = "SPONSORED_DISCLOSURE"
    REAL_PHOTO_REVIEW = "REAL_PHOTO_REVIEW"
    EXPERIENCE_QUESTIONNAIRE = "EXPERIENCE_QUESTIONNAIRE"
    EXPERIENCE_INTEGRITY_REVIEW = "EXPERIENCE_INTEGRITY_REVIEW"
    PRODUCT_PROMOTION = "PRODUCT_PROMOTION"
    SMART_STORE = "SMART_STORE"
    AFFILIATE_COMMERCE = "AFFILIATE_COMMERCE"
    BUYING_GUIDE = "BUYING_GUIDE"
    PRODUCT_COMPARISON = "PRODUCT_COMPARISON"
    PRODUCT_HOW_TO = "PRODUCT_HOW_TO"
    PRODUCT_FAQ = "PRODUCT_FAQ"
    LANDING_BLOG = "LANDING_BLOG"
    PROMOTION = "PROMOTION"
    TRACKED_LINK_CONTENT = "TRACKED_LINK_CONTENT"
    YOUTUBE_BASED = "YOUTUBE_BASED"
    VIDEO_SUMMARY = "VIDEO_SUMMARY"
    NEWS_BASED = "NEWS_BASED"
    NEWS_OPINION = "NEWS_OPINION"
    PDF_REPORT_BASED = "PDF_REPORT_BASED"
    INTERVIEW_BASED = "INTERVIEW_BASED"
    PRESS_RELEASE_BASED = "PRESS_RELEASE_BASED"
    RSS_BASED = "RSS_BASED"
    URL_BASED = "URL_BASED"
    MULTI_SOURCE_SYNTHESIS = "MULTI_SOURCE_SYNTHESIS"
    OWNED_CONTENT_REWRITE = "OWNED_CONTENT_REWRITE"
    CONTENT_REFRESH = "CONTENT_REFRESH"
    STRUCTURE_IMPROVEMENT = "STRUCTURE_IMPROVEMENT"
    VOICE_TRANSFORMATION = "VOICE_TRANSFORMATION"
    LENGTH_TRANSFORMATION = "LENGTH_TRANSFORMATION"
    CONTENT_MERGE = "CONTENT_MERGE"
    CONTENT_SPLIT = "CONTENT_SPLIT"
    DEDUPLICATION = "DEDUPLICATION"
    CHANNEL_REFORMAT = "CHANNEL_REFORMAT"
    THIRD_PARTY_LIMITED_TRANSFORM = "THIRD_PARTY_LIMITED_TRANSFORM"


class GenerationQuality(StrEnum):
    FAST = "FAST"
    BALANCED = "BALANCED"
    PREMIUM = "PREMIUM"


class GenerationOperation(StrEnum):
    CREATE = "CREATE"
    REGENERATE = "REGENERATE"
    EDIT_SELECTION = "EDIT_SELECTION"
    LOCALIZE = "LOCALIZE"
    REPURPOSE = "REPURPOSE"


class GenerationStepKind(StrEnum):
    VALIDATE_INPUT = "VALIDATE_INPUT"
    RESEARCH = "RESEARCH"
    PLAN_OUTLINE = "PLAN_OUTLINE"
    GENERATE_SECTION = "GENERATE_SECTION"
    VERIFY_CLAIMS = "VERIFY_CLAIMS"
    VERIFY_POLICY = "VERIFY_POLICY"
    OPTIMIZE = "OPTIMIZE"
    PREPARE_REVIEW = "PREPARE_REVIEW"


class ContentChangeKind(StrEnum):
    GENERATED = "GENERATED"
    MANUAL = "MANUAL"
    AUTOSAVE = "AUTOSAVE"
    RESTORE = "RESTORE"
    AI_EDIT = "AI_EDIT"
    IMPORT = "IMPORT"


class TemplateScope(StrEnum):
    OFFICIAL = "OFFICIAL"
    WORKSPACE = "WORKSPACE"
    PERSONAL = "PERSONAL"


class VersionStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    DEPRECATED = "DEPRECATED"


class ModelCatalogStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DEGRADED = "DEGRADED"
    DISABLED = "DISABLED"
    DEPRECATED = "DEPRECATED"


class CommandKind(StrEnum):
    CANCEL = "CANCEL"
    RETRY = "RETRY"


class CollaborationEventKind(StrEnum):
    EDIT = "EDIT"
    COMMENT = "COMMENT"
    COMMENT_RESOLVED = "COMMENT_RESOLVED"
    COMMENT_REOPENED = "COMMENT_REOPENED"
    SUGGESTION_ACCEPTED = "SUGGESTION_ACCEPTED"
    SUGGESTION_REJECTED = "SUGGESTION_REJECTED"
    VERSION_CREATED = "VERSION_CREATED"
    VERSION_RESTORED = "VERSION_RESTORED"
    LOCK_ACQUIRED = "LOCK_ACQUIRED"
    LOCK_RELEASED = "LOCK_RELEASED"


class LineageKind(StrEnum):
    REWRITE = "REWRITE"
    REFRESH = "REFRESH"
    MERGE = "MERGE"
    SPLIT = "SPLIT"
    REFORMAT = "REFORMAT"
    DUPLICATE = "DUPLICATE"


class FeedbackKind(StrEnum):
    USEFUL = "USEFUL"
    INACCURATE = "INACCURATE"
    VOICE_MISMATCH = "VOICE_MISMATCH"
    UNSAFE = "UNSAFE"
    OTHER = "OTHER"
